class_name UnitDefs
## Data definitions for every unit. Pure data — no logic.
## role: worker | melee | defender | ranged | flanker | antiarmor | caster | healer | siege | hero
## armor_class: unarmored | light | medium | heavy
## dmg_type: slash | pierce | blunt | arcane | siege

static func _char(id: String) -> String:
	return "res://assets/characters/%s/%s.glb" % [id, id]

static func get_all() -> Dictionary:
	return {
	# ---------------- BARROSAN CLANS ----------------
	"barrosan_worker": {
		"race": "barrosan", "name": "Highland Worker", "role": "worker", "tier": 1,
		"portrait": "res://assets/ui/portraits/barrosan/a08_portrait_worker.jpg",
		"model": _char("barrosan_highlander_worker"), "height": 1.8,
		"hp": 60, "dmg": 5, "dmg_type": "blunt", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 1.2, "speed": 3.6, "vision": 18.0,
		"cost": {"food": 45}, "build_time": 11, "pop": 1,
		"desc": "Shepherd, charcoal-burner and quarryman in one. Gathers, builds and repairs; every loaf the village bakes feeds the Lume.",
	},
	"barrosan_clan_levy": {
		"race": "barrosan", "name": "Clan Levy", "role": "melee", "tier": 1,
		"portrait": "res://assets/ui/portraits/barrosan/a08_b1_portrait_clan_levy.jpg",
		"model": _char("barrosan_clan_levy"), "height": 1.8,
		"hp": 130, "dmg": 14, "dmg_type": "slash", "armor_class": "light", "armor": 1,
		"range": 0.0, "attack_cd": 1.1, "speed": 3.7, "vision": 20.0,
		"cost": {"food": 45, "timber": 10}, "build_time": 11, "pop": 1, "produced_by": "barracks",
		"desc": "Farmers who fight in family blocks under the village banner. Cheap and stubborn; good against unarmored foes.",
	},
	"barrosan_spear_guard": {
		"race": "barrosan", "name": "Stoneward Spears", "role": "defender", "tier": 1,
		"portrait": "res://assets/ui/portraits/barrosan/a08_b1_portrait_stoneward_spears.jpg",
		"model": "res://assets/characters/barrosan_stoneward_spears_r696_compat/barrosan_stoneward_spears_r696_compat.glb", "height": 1.85,
		"hp": 180, "dmg": 17, "dmg_type": "pierce", "armor_class": "heavy", "armor": 4,
		"range": 0.0, "attack_cd": 1.3, "speed": 3.0, "vision": 20.0,
		"cost": {"food": 55, "timber": 20, "stone": 10, "gold": 15}, "build_time": 18, "pop": 2, "produced_by": "barracks",
		"desc": "Granite-steady pikemen who have held the mountain passes for three hundred years. Anchor the line and shred cavalry.",
	},
	"barrosan_crag_archer": {
		"race": "barrosan", "name": "Crag Archer", "role": "ranged", "tier": 1,
		"portrait": "res://assets/ui/portraits/barrosan/astra_r1/crag_archer.png",
		"model": _char("barrosan_crag_archer"), "height": 1.8,
		"hp": 90, "dmg": 19, "dmg_type": "pierce", "armor_class": "light", "armor": 0,
		"range": 16.0, "attack_cd": 1.4, "speed": 3.5, "vision": 24.0, "projectile": "arrow",
		"cost": {"food": 45, "timber": 30}, "build_time": 16, "pop": 1, "produced_by": "barracks",
		"desc": "Wolf-hunters of the high crags, who learned their aim on the fojo walls. Deadly from the heights, fragile up close.",
	},
	"barrosan_outrider": {
		"race": "barrosan", "name": "Garrano Outrider", "role": "flanker", "tier": 2,
		"portrait": "res://assets/ui/portraits/barrosan/astra_r1/highland_outrider.png",
		"model": _char("barrosan_outrider"), "height": 1.8,
		"hp": 150, "dmg": 17, "dmg_type": "slash", "armor_class": "light", "armor": 1,
		"range": 0.0, "attack_cd": 1.0, "speed": 5.4, "vision": 26.0,
		"cost": {"food": 65, "gold": 35}, "build_time": 18, "pop": 2, "produced_by": "barracks",
		"desc": "Riders on the small, sure-footed wild ponies of the Gerês. Run down archers and harry the enemy's workers.",
	},
	"barrosan_anvil_breaker": {
		"race": "barrosan", "name": "Anvil Breaker", "role": "antiarmor", "tier": 3,
		"portrait": "res://assets/ui/portraits/barrosan/astra_r1/anvil_breaker.png",
		"model": _char("barrosan_anvil_breaker"), "height": 1.95,
		"hp": 240, "dmg": 30, "dmg_type": "blunt", "armor_class": "heavy", "armor": 5,
		"range": 0.0, "attack_cd": 1.7, "speed": 2.8, "vision": 20.0,
		"cost": {"food": 90, "stone": 40, "gold": 60}, "build_time": 26, "pop": 3, "produced_by": "barracks",
		"desc": "The village smiths, marching with the sledgehammers that shaped every plow in the valley. Crush heavy armor and walls.",
	},
	"barrosan_ballista": {
		"race": "barrosan", "name": "Clan Ballista", "role": "siege", "tier": 3, "is_siege": true,
		"portrait": "res://assets/ui/portraits/barrosan/astra_r1/clan_ballista.png",
		"model": "res://assets/props/vehicles/barrosan_ballista.glb", "height": 2.2,
		"hp": 160, "dmg": 55, "dmg_type": "siege", "armor_class": "medium", "armor": 2,
		"range": 22.0, "attack_cd": 2.6, "speed": 2.4, "vision": 26.0, "projectile": "bolt",
		"cost": {"timber": 120, "gold": 60}, "build_time": 30, "pop": 3, "produced_by": "barracks",
		"desc": "A clan bolt-thrower hauled up the passes by Barrosã oxen. Devastating against buildings, helpless in melee.",
	},

	# ---------------- LIORAEN CONCORD ----------------
	"lioraen_worker": {
		"race": "lioraen", "name": "Seedkeeper", "role": "worker", "tier": 1,
		"model": _char("lioraen_seedkeeper_worker"), "height": 1.75,
		"hp": 55, "dmg": 5, "dmg_type": "blunt", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 1.2, "speed": 3.9, "vision": 18.0,
		"cost": {"food": 50}, "build_time": 12, "pop": 1,
		"desc": "Tends the springs and grows living halls from seed. Village women still leave bread for them at the fountains.",
	},
	# 125 health and 1 armour (was 115 and 0, the frailest soldier at its
	# price): without heroes or healers the Lioraen's tier-one army lost
	# equal-cost open fights 1-5 to the Aurean Dominion and 0-6 to the
	# Granitborn and the Moura Court (plan 174).
	"lioraen_bloomdancer": {
		"race": "lioraen", "name": "Bloomdancer", "role": "melee", "tier": 1,
		"model": _char("lioraen_bloomdancer"), "height": 1.8,
		"hp": 125, "dmg": 14, "dmg_type": "slash", "armor_class": "light", "armor": 1,
		"range": 0.0, "attack_cd": 0.95, "speed": 4.2, "vision": 20.0,
		"cost": {"food": 60, "timber": 10}, "build_time": 12, "pop": 1, "produced_by": "barracks",
		"desc": "A spring-dancer of the Concord who strikes and is gone like light on water.",
	},
	"lioraen_rootwarden_guard": {
		"race": "lioraen", "name": "Rootwarden", "role": "defender", "tier": 1,
		"model": _char("lioraen_rootwarden_guard"), "height": 1.9,
		"hp": 200, "dmg": 12, "dmg_type": "blunt", "armor_class": "heavy", "armor": 4,
		"range": 0.0, "attack_cd": 1.4, "speed": 2.9, "vision": 20.0,
		"cost": {"food": 70, "timber": 30}, "build_time": 18, "pop": 2, "produced_by": "barracks",
		"desc": "An ancient guardian half turned to oak. Soaks up punishment so the swift can strike.",
	},
	"lioraen_thorn_ranger": {
		"race": "lioraen", "name": "Thornrunner", "role": "ranged", "tier": 1,
		"model": _char("lioraen_thorn_ranger"), "height": 1.78,
		"hp": 85, "dmg": 15, "dmg_type": "pierce", "armor_class": "light", "armor": 0,
		"range": 17.0, "attack_cd": 1.3, "speed": 3.9, "vision": 25.0, "projectile": "thorn",
		"cost": {"food": 50, "timber": 30}, "build_time": 16, "pop": 1, "produced_by": "barracks",
		"desc": "A spring-guard archer who kites the enemy through the bloomfields.",
	},
	"lioraen_windstrider": {
		"race": "lioraen", "name": "Windstrider", "role": "flanker", "tier": 2,
		"model": _char("lioraen_windstrider"), "height": 1.8,
		"hp": 130, "dmg": 18, "dmg_type": "pierce", "armor_class": "light", "armor": 1,
		"range": 0.0, "attack_cd": 0.9, "speed": 5.8, "vision": 28.0,
		"cost": {"food": 90, "gold": 20}, "build_time": 18, "pop": 2, "produced_by": "barracks",
		"desc": "The fastest rider in the highlands, a lancer on a stag of living wood.",
	},
	# Healers heal 11 a cast (was 14) now that they heal in a fight and not
	# only at rest (plan 174): at 14 the three other healer peoples won 13-5
	# each on the small maps.
	"lioraen_canopy_mender": {
		"race": "lioraen", "name": "Canopy Mender", "role": "healer", "tier": 2,
		"model": _char("lioraen_canopy_mender"), "height": 1.8,
		"hp": 95, "dmg": 8, "dmg_type": "arcane", "armor_class": "light", "armor": 0,
		"range": 14.0, "attack_cd": 1.5, "speed": 3.6, "vision": 24.0, "projectile": "lume_bolt",
		"heal": 11.0, "heal_range": 13.0, "heal_cd": 1.2,
		"cost": {"food": 80, "gold": 30}, "build_time": 20, "pop": 2, "produced_by": "arcane",
		"desc": "Sings the wounded whole with the old spring songs. Turns every skirmish into a war you outlast.",
	},
	"lioraen_thornthrower": {
		"race": "lioraen", "name": "Thornthrower", "role": "siege", "tier": 3, "is_siege": true,
		"model": "res://assets/props/vehicles/lioraen_thornthrower.glb", "height": 2.2,
		"hp": 150, "dmg": 48, "dmg_type": "siege", "armor_class": "medium", "armor": 1,
		"range": 21.0, "attack_cd": 2.4, "speed": 2.6, "vision": 26.0, "projectile": "thornpod", "splash": 4.0,
		"cost": {"timber": 130, "gold": 50}, "build_time": 28, "pop": 3, "produced_by": "arcane",
		"desc": "A living catapult that lobs bursting thorn-pods over the walls.",
	},

	# ---------------- VORTHAK CABAL ----------------
	"vorthak_worker": {
		"race": "vorthak", "name": "Bondservant", "role": "worker", "tier": 1,
		"model": _char("vorthak_bondservant_worker"), "height": 1.75,
		"portrait": "res://assets/ui/portraits/vorthak/astra_r1/bondservant.png",
		"hp": 50, "dmg": 5, "dmg_type": "blunt", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 1.2, "speed": 3.7, "vision": 18.0,
		"cost": {"food": 45}, "build_time": 11, "pop": 1,
		"desc": "A drowned villager's child, driven by glass-scarred masters. Gathers and raises the Cabal's dark halls.",
	},
	"vorthak_ash_thrall": {
		"race": "vorthak", "name": "Ash Thrall", "role": "melee", "tier": 1,
		"model": _char("vorthak_ash_thrall"), "height": 1.8,
		"portrait": "res://assets/ui/portraits/vorthak/astra_r1/ash_thrall.png",
		"hp": 88, "dmg": 11, "dmg_type": "slash", "armor_class": "unarmored", "armor": 0,
		"range": 0.0, "attack_cd": 1.0, "speed": 4.0, "vision": 20.0,
		"cost": {"food": 50, "gold": 5}, "build_time": 9, "pop": 1, "produced_by": "barracks",
		"desc": "Once a farmer of Furna, now an ash-glass husk that remembers only anger. Cheap, fast and endless.",
	},
	"vorthak_rift_blade": {
		"race": "vorthak", "name": "Rift Blade", "role": "melee", "tier": 2,
		"model": _char("vorthak_rift_blade"), "height": 1.82,
		"portrait": "res://assets/ui/portraits/vorthak/astra_r1/rift_blade.png",
		"hp": 160, "dmg": 24, "dmg_type": "slash", "armor_class": "medium", "armor": 2,
		"range": 0.0, "attack_cd": 0.9, "speed": 4.4, "vision": 22.0,
		"cost": {"food": 90, "gold": 40}, "build_time": 18, "pop": 2, "produced_by": "barracks",
		"desc": "A duelist armored in violet glass. Strikes hard and fast, and costs the Cabal dearly.",
	},
	"vorthak_cinder_spitter": {
		"race": "vorthak", "name": "Cinder Spitter", "role": "ranged", "tier": 1,
		"model": _char("vorthak_cinder_spitter"), "height": 1.78,
		"portrait": "res://assets/ui/portraits/vorthak/astra_r1/cinder_spitter.png",
		"hp": 80, "dmg": 15, "dmg_type": "arcane", "armor_class": "unarmored", "armor": 0,
		"range": 16.0, "attack_cd": 1.4, "speed": 3.5, "vision": 24.0, "projectile": "cinder",
		"cost": {"food": 65, "gold": 20}, "build_time": 16, "pop": 1, "produced_by": "barracks",
		"desc": "Spits burning ash-glass. Its arcane fire bites hard into heavy armor.",
	},
	"vorthak_gloom_hound": {
		"race": "vorthak", "name": "Gloom Hound", "role": "flanker", "tier": 2,
		"model": _char("vorthak_gloom_hound"), "height": 1.3,
		"portrait": "res://assets/ui/portraits/vorthak/astra_r1/gloom_hound.png",
		"hp": 110, "dmg": 16, "dmg_type": "slash", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 0.8, "speed": 6.0, "vision": 30.0,
		"cost": {"food": 70, "gold": 15}, "build_time": 14, "pop": 1, "produced_by": "barracks",
		"desc": "The village dogs of Furna, drowned and risen. They outrun everything and never stop hunting.",
	},
	"vorthak_veil_warlock": {
		"race": "vorthak", "name": "Veil Warlock", "role": "caster", "tier": 3,
		"model": _char("vorthak_veil_warlock"), "height": 1.85,
		"portrait": "res://assets/ui/portraits/vorthak/astra_r1/veil_warlock.png",
		"hp": 100, "dmg": 30, "dmg_type": "arcane", "armor_class": "unarmored", "armor": 0,
		"range": 18.0, "attack_cd": 2.0, "speed": 3.3, "vision": 26.0, "projectile": "void_bolt", "splash": 3.5,
		"cost": {"food": 90, "gold": 70}, "build_time": 24, "pop": 2, "produced_by": "arcane",
		"desc": "Sings the drowned bells of Furna into void fire. Melts clustered armies.",
	},
	"vorthak_fracture_engine": {
		"race": "vorthak", "name": "Fracture Engine", "role": "siege", "tier": 3, "is_siege": true,
		"model": "res://assets/props/vehicles/vorthak_fracture_engine.glb", "height": 2.3,
		"hp": 170, "dmg": 60, "dmg_type": "siege", "armor_class": "medium", "armor": 2,
		"range": 22.0, "attack_cd": 2.8, "speed": 2.3, "vision": 26.0, "projectile": "rift_shell", "splash": 5.0,
		"cost": {"timber": 90, "gold": 90}, "build_time": 30, "pop": 3, "produced_by": "arcane",
		"desc": "An unstable mortar that hurls raw ash-glass. Enormous splash siege damage.",
	},

	# ---------------- HEROES ----------------
	"barrosan_hero_thane": {
		"race": "barrosan", "name": "Jardas", "role": "hero", "tier": 1, "is_hero": true,
		"portrait": "res://assets/ui/portraits/barrosan/a08_portrait_warthane.jpg",
		"model": _char("barrosan_hero_thane"), "height": 2.0,
		"hp": 400, "dmg": 34, "dmg_type": "slash", "armor_class": "heavy", "armor": 6,
		"range": 0.0, "attack_cd": 1.1, "speed": 3.9, "vision": 28.0, "pop": 0,
		"desc": "The carrier of the Lume, risen at the Spring of Seven Mouths. Rallies the clans around them and leads from the front.",
	},
	"lioraen_hero_warden": {
		"race": "lioraen", "name": "Grove Warden", "role": "hero", "tier": 1, "is_hero": true,
		"model": _char("lioraen_hero_warden"), "height": 1.95,
		"hp": 380, "dmg": 30, "dmg_type": "arcane", "armor_class": "medium", "armor": 3,
		"range": 15.0, "attack_cd": 1.2, "speed": 4.3, "vision": 30.0, "projectile": "lume_bolt", "pop": 0,
		"desc": "Ilduara's line of spring-wardens: heals allies and roots the enemy where they stand.",
	},
	"vorthak_hero_binder": {
		"race": "vorthak", "name": "Rift Binder", "role": "hero", "tier": 1, "is_hero": true,
		"model": _char("vorthak_hero_binder"), "height": 2.0,
		"portrait": "res://assets/ui/portraits/vorthak/astra_r1/rift_binder.png",
		"hp": 300, "dmg": 28, "dmg_type": "arcane", "armor_class": "light", "armor": 2,
		"range": 13.0, "attack_cd": 1.3, "speed": 4.0, "vision": 30.0, "projectile": "void_bolt", "splash": 3.0, "pop": 0,
		"desc": "An ash-glass sorcerer of drowned Furna who binds rotten Lume into violet fire. Enormous burst magic, fragile if caught.",
	},

	# ---------------- GRIMTUSK HORDE ----------------
	"grimtusk_peon": {
		"race": "grimtusk", "name": "Ironmaw Hauler", "role": "worker", "tier": 1,
		"model": _char("orc_grunt"), "height": 1.85,
		"hp": 58, "dmg": 5, "dmg_type": "blunt", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 1.2, "speed": 3.7, "vision": 18.0,
		"cost": {"food": 50}, "build_time": 12, "pop": 1,
		"desc": "A freed mine slave who still carries twice his weight, now for himself.",
	},
	"grimtusk_grunt": {
		"race": "grimtusk", "name": "Ironmaw Breaker", "role": "melee", "tier": 1,
		"model": _char("orc_grunt"), "height": 1.9,
		"hp": 100, "dmg": 11, "dmg_type": "slash", "armor_class": "light", "armor": 1,
		"range": 0.0, "attack_cd": 1.0, "speed": 4.0, "vision": 20.0,
		# "Cheap, fearless and everywhere" at 55 for 100 health, when a Clan
		# Levy gave 130 health for the same 55. 40 food and 8 seconds:
		# 20-14 over 35 matches where the Ironmaw had been 11-23.
		# Then 23-11 over the two full checks of plans 116 and 117: 45 food.
		"cost": {"food": 45}, "build_time": 8, "pop": 1, "produced_by": "grimtusk_warcamp",
		"desc": "Iron in the jaw, chains wrapped round the fists. Cheap, fearless and everywhere.",
	},
	"grimtusk_bowcrusha": {
		"race": "grimtusk", "name": "Ironmaw Slinger", "role": "ranged", "tier": 1,
		"model": _char("grimtusk_bowcrusha_r704c"), "height": 1.9,
		"hp": 90, "dmg": 16, "dmg_type": "pierce", "armor_class": "light", "armor": 0,
		"range": 16.0, "attack_cd": 1.4, "speed": 3.5, "vision": 24.0, "projectile": "arrow",
		"cost": {"food": 50, "timber": 30}, "build_time": 16, "pop": 1, "produced_by": "grimtusk_warcamp",
		"desc": "Hurls mine-iron with a sling made from an overseer's belt. Rarely misses.",
	},
	"grimtusk_wolfrider": {
		"race": "grimtusk", "name": "Tunnel Rider", "role": "flanker", "tier": 2,
		"model": _char("vorthak_gloom_hound"), "height": 1.4,
		"hp": 115, "dmg": 17, "dmg_type": "slash", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 0.8, "speed": 6.0, "vision": 30.0,
		"cost": {"food": 70, "gold": 15}, "build_time": 14, "pop": 1, "produced_by": "grimtusk_warcamp",
		"desc": "Rides a pit-bred war-hound through the Dominion's own mine tunnels. Runs down the fleeing.",
	},
	# The Chainbreaker "fights with the chain that held him": blunt, not
	# slash (plan 179). Every Ironmaw soldier below the third age cut or
	# pierced, both weak against heavy armour, and once the computer learned
	# to wear what the enemy's weapons bite least the Horde fell to 9-27.
	"grimtusk_berserker": {
		"race": "grimtusk", "name": "Chainbreaker", "role": "melee", "tier": 2,
		"model": _char("orc_grunt"), "height": 2.0,
		"hp": 165, "dmg": 23, "dmg_type": "blunt", "armor_class": "medium", "armor": 2,
		"range": 0.0, "attack_cd": 0.9, "speed": 4.5, "vision": 22.0,
		"cost": {"food": 90, "gold": 40}, "build_time": 18, "pop": 2, "produced_by": "grimtusk_warcamp",
		"desc": "Fights with the chain that held him. Blood-drunk, nearly impossible to bring down.",
	},
	"grimtusk_ogre": {
		"race": "grimtusk", "name": "Pit Giant", "role": "antiarmor", "tier": 3,
		"model": _char("grimtusk_ogre_r709b"), "height": 2.5,
		"hp": 245, "dmg": 30, "dmg_type": "blunt", "armor_class": "heavy", "armor": 5,
		"range": 0.0, "attack_cd": 1.7, "speed": 2.8, "vision": 20.0,
		"cost": {"food": 110, "stone": 40, "gold": 40}, "build_time": 26, "pop": 3, "produced_by": "grimtusk_warcamp",
		"desc": "A mine slave the Lume-iron made enormous. Crushes armor, walls, and anything that stands still.",
	},
	"grimtusk_slag_thrower": {
		"race": "grimtusk", "name": "Slag Thrower", "role": "siege", "tier": 3, "is_siege": true,
		"model": "res://assets/props/vehicles/barrosan_ballista.glb", "height": 2.2,
		"hp": 180, "dmg": 55, "dmg_type": "siege", "armor_class": "medium", "armor": 2,
		"range": 21.0, "attack_cd": 2.8, "speed": 2.3, "vision": 26.0, "projectile": "bolt", "splash": 4.0,
		"cost": {"timber": 120, "gold": 60}, "build_time": 30, "pop": 3, "produced_by": "grimtusk_warcamp",
		"desc": "A counterweight arm from the pit head, loaded with slag. The Ironmaw dug the mines; now they throw them back.",
	},
	"grimtusk_hero_warlord": {
		"race": "grimtusk", "name": "Warboss Brasa", "role": "hero", "tier": 1, "is_hero": true,
		"model": _char("grimtusk_hero_warlord"), "height": 2.2,
		"hp": 400, "dmg": 34, "dmg_type": "slash", "armor_class": "heavy", "armor": 6,
		"range": 0.0, "attack_cd": 1.1, "speed": 3.9, "vision": 28.0, "pop": 0,
		"desc": "Leader of the Ironmaw revolt. Her battle-cry alone breaks an enemy's nerve.",
	},

	# ---------------- SYLVAN COURT ----------------
	"sylvan_acolyte": {
		"race": "sylvan", "name": "Silver Handmaid", "role": "worker", "tier": 1,
		"model": _char("lioraen_seedkeeper_worker"), "height": 1.75,
		"hp": 55, "dmg": 5, "dmg_type": "blunt", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 1.2, "speed": 3.9, "vision": 18.0,
		"cost": {"food": 50}, "build_time": 12, "pop": 1,
		"desc": "A Moura servant who tends the Court's frozen gardens.",
	},
	"sylvan_bladesinger": {
		"race": "sylvan", "name": "Silver Duelist", "role": "melee", "tier": 1,
		"model": _char("lioraen_bloomdancer"), "height": 1.8,
		"hp": 130, "dmg": 15, "dmg_type": "slash", "armor_class": "light", "armor": 1,
		"range": 0.0, "attack_cd": 1.1, "speed": 3.7, "vision": 20.0,
		"cost": {"food": 60, "timber": 10}, "build_time": 12, "pop": 1, "produced_by": "sylvan_bladehall",
		"desc": "Blade and spell woven into one cold, perfect song.",
	},
	"sylvan_warden": {
		"race": "sylvan", "name": "Silver Warden", "role": "defender", "tier": 1,
		"model": _char("lioraen_rootwarden_guard"), "height": 1.9,
		"hp": 180, "dmg": 14, "dmg_type": "pierce", "armor_class": "heavy", "armor": 4,
		"range": 0.0, "attack_cd": 1.3, "speed": 3.0, "vision": 20.0,
		"cost": {"food": 70, "timber": 30}, "build_time": 18, "pop": 2, "produced_by": "sylvan_bladehall",
		"desc": "An armored Moura guardian: a wall of silver and bark that does not bleed.",
	},
	"sylvan_longbow": {
		"race": "sylvan", "name": "Coal-Gold Archer", "role": "ranged", "tier": 1,
		"model": _char("highelf_archer"), "height": 1.78,
		"hp": 88, "dmg": 17, "dmg_type": "pierce", "armor_class": "light", "armor": 0,
		"range": 18.0, "attack_cd": 1.4, "speed": 3.5, "vision": 27.0, "projectile": "arrow",
		"cost": {"food": 50, "timber": 30}, "build_time": 16, "pop": 1, "produced_by": "sylvan_bladehall",
		"desc": "Arrows tipped with the Moura gold that turns to coal in greedy hands. Unmatched range.",
	},
	"sylvan_windrunner": {
		"race": "sylvan", "name": "Fountain Rider", "role": "flanker", "tier": 2,
		"model": _char("lioraen_windstrider"), "height": 1.8,
		"hp": 130, "dmg": 18, "dmg_type": "pierce", "armor_class": "light", "armor": 1,
		"range": 0.0, "attack_cd": 0.9, "speed": 5.8, "vision": 28.0,
		"cost": {"food": 90, "gold": 20}, "build_time": 18, "pop": 2, "produced_by": "sylvan_bladehall",
		"desc": "A blur of silver that crosses a battlefield like water.",
	},
	"sylvan_silver_colossus": {
		"race": "sylvan", "name": "Silver Colossus", "role": "antiarmor", "tier": 3,
		"model": _char("barrosan_anvil_breaker"), "height": 2.2,
		"hp": 310, "dmg": 35, "dmg_type": "arcane", "armor_class": "heavy", "armor": 4,
		"range": 0.0, "attack_cd": 1.7, "speed": 2.7, "vision": 22.0,
		"cost": {"food": 110, "stone": 40, "gold": 50}, "build_time": 28, "pop": 3, "produced_by": "sylvan_bladehall",
		"desc": "A Moura's guardian woken from a silver-veined rock. It walks slowly and never forgets an insult.",
	},
	"sylvan_lightweaver": {
		"race": "sylvan", "name": "Silver Chorister", "role": "healer", "tier": 2,
		"model": _char("lioraen_canopy_mender"), "height": 1.8,
		"hp": 110, "dmg": 10, "dmg_type": "arcane", "armor_class": "light", "armor": 0,
		"range": 14.0, "attack_cd": 1.5, "speed": 3.6, "vision": 24.0, "projectile": "lume_bolt",
		"heal": 11.0, "heal_range": 13.0, "heal_cd": 1.2,
		"cost": {"food": 80, "gold": 30}, "build_time": 20, "pop": 2, "produced_by": "sylvan_arcanum",
		"desc": "Mends wounds with bought light. It never quite feels warm.",
	},
	"sylvan_hero_archon": {
		"race": "sylvan", "name": "High Moura", "role": "hero", "tier": 1, "is_hero": true,
		"model": _char("sylvan_hero_archon"), "height": 1.95,
		"hp": 380, "dmg": 30, "dmg_type": "arcane", "armor_class": "medium", "armor": 3,
		"range": 15.0, "attack_cd": 1.2, "speed": 4.3, "vision": 30.0, "projectile": "lume_bolt", "pop": 0,
		"desc": "Queen of the Moura Court, perfect and ageless, who sold her Lume for eternity.",
	},

	# ---------------- KARAK DWARVES ----------------
	"karak_miner": {
		"race": "karak", "name": "Castro Quarrier", "role": "worker", "tier": 1,
		"model": _char("barrosan_highlander_worker"), "height": 1.55,
		"hp": 60, "dmg": 5, "dmg_type": "blunt", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 1.2, "speed": 3.6, "vision": 18.0,
		"cost": {"food": 50}, "build_time": 12, "pop": 1,
		"desc": "A Granitborn stoneworker who hews rock and raises hillfort walls that never fall.",
	},
	"karak_warrior": {
		"race": "karak", "name": "Castro Warrior", "role": "melee", "tier": 1,
		"model": _char("dwarf_warrior"), "height": 1.6,
		"hp": 140, "dmg": 15, "dmg_type": "blunt", "armor_class": "medium", "armor": 2,
		"range": 0.0, "attack_cd": 1.1, "speed": 3.4, "vision": 20.0,
		"cost": {"food": 60, "timber": 10}, "build_time": 12, "pop": 1, "produced_by": "karak_warforge",
		"desc": "Half flesh, half granite. Slower than most, tougher than all.",
	},
	"karak_ironbreaker": {
		"race": "karak", "name": "Ironbreaker", "role": "defender", "tier": 1,
		"model": _char("barrosan_spear_guard"), "height": 1.65,
		"hp": 195, "dmg": 17, "dmg_type": "blunt", "armor_class": "heavy", "armor": 4,
		"range": 0.0, "attack_cd": 1.3, "speed": 2.8, "vision": 20.0,
		"cost": {"food": 70, "timber": 20, "stone": 10}, "build_time": 18, "pop": 2, "produced_by": "karak_warforge",
		"desc": "A Granitborn veteran who has stood in the same shield-wall for two hundred years.",
	},
	"karak_quarreler": {
		"race": "karak", "name": "Quarreler", "role": "ranged", "tier": 1,
		"model": _char("barrosan_crag_archer"), "height": 1.6,
		"hp": 90, "dmg": 17, "dmg_type": "pierce", "armor_class": "light", "armor": 0,
		"range": 17.0, "attack_cd": 1.4, "speed": 3.5, "vision": 24.0, "projectile": "bolt",
		"cost": {"food": 50, "timber": 30}, "build_time": 16, "pop": 1, "produced_by": "karak_warforge",
		"desc": "A stone-skinned crossbowman whose bolts crack armor like slate.",
	},
	"karak_castro_rider": {
		"race": "karak", "name": "Castro Rider", "role": "flanker", "tier": 2,
		"model": _char("barrosan_outrider"), "height": 1.8,
		"hp": 160, "dmg": 17, "dmg_type": "blunt", "armor_class": "medium", "armor": 2,
		"range": 0.0, "attack_cd": 1.0, "speed": 5.0, "vision": 26.0,
		"cost": {"food": 85, "stone": 15, "gold": 20}, "build_time": 20, "pop": 2, "produced_by": "karak_warforge",
		"desc": "Granitborn outriders on shaggy garranos, riding the old castro roads that only stone remembers.",
	},
	"karak_hammerer": {
		"race": "karak", "name": "Hammerer", "role": "antiarmor", "tier": 3,
		"model": _char("barrosan_anvil_breaker"), "height": 1.7,
		"hp": 255, "dmg": 32, "dmg_type": "blunt", "armor_class": "heavy", "armor": 5,
		"range": 0.0, "attack_cd": 1.7, "speed": 2.8, "vision": 20.0,
		"cost": {"food": 110, "stone": 40, "gold": 40}, "build_time": 26, "pop": 3, "produced_by": "karak_warforge",
		"desc": "Swings a hammer carved from a standing stone. Every blow echoes old battles.",
	},
	"karak_cannon": {
		"race": "karak", "name": "Stone Mortar", "role": "siege", "tier": 3, "is_siege": true,
		"model": "res://assets/props/vehicles/barrosan_ballista.glb", "height": 2.0,
		"hp": 165, "dmg": 58, "dmg_type": "siege", "armor_class": "medium", "armor": 2,
		"range": 22.0, "attack_cd": 2.8, "speed": 2.2, "vision": 26.0, "projectile": "bolt", "splash": 4.0,
		"cost": {"timber": 120, "gold": 60}, "build_time": 30, "pop": 3, "produced_by": "karak_warforge",
		"desc": "Lobs carved boulders from the castro walls. Each one breaks apart among whoever stands close together.",
	},
	"karak_hero_thanelord": {
		"race": "karak", "name": "Thane-Lord Carvalho", "role": "hero", "tier": 1, "is_hero": true,
		"model": _char("karak_hero_thanelord"), "height": 1.75,
		"hp": 440, "dmg": 34, "dmg_type": "blunt", "armor_class": "heavy", "armor": 7,
		"range": 0.0, "attack_cd": 1.1, "speed": 3.6, "vision": 28.0, "pop": 0,
		"desc": "Keeper of the ledger of the dead, who has read every name the highlands ever lost.",
	},

	# ---------------- SUNSPEAR DOMINION ----------------
	"sunspear_laborer": {
		"race": "sunspear", "name": "Dominion Engineer", "role": "worker", "tier": 1,
		"model": _char("barrosan_highlander_worker"), "height": 1.8,
		"hp": 60, "dmg": 5, "dmg_type": "blunt", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 1.2, "speed": 3.6, "vision": 18.0,
		"cost": {"food": 50}, "build_time": 12, "pop": 1,
		"desc": "Surveys valleys, drives stakes and builds the dams. Nothing personal. The water has to go somewhere.",
	},
	"sunspear_legion": {
		"race": "sunspear", "name": "Bronze Legionary", "role": "melee", "tier": 1,
		"model": _char("sunspear_legionary"), "height": 1.8,
		"hp": 140, "dmg": 14, "dmg_type": "slash", "armor_class": "light", "armor": 2,
		"range": 0.0, "attack_cd": 1.1, "speed": 3.7, "vision": 20.0,
		"cost": {"food": 60, "timber": 10}, "build_time": 12, "pop": 1, "produced_by": "sunspear_legion_hall",
		"desc": "The backbone of seventy-seven years of victory. Disciplined to the last.",
	},
	"sunspear_phalanx": {
		"race": "sunspear", "name": "Bronze Phalanx", "role": "defender", "tier": 1,
		"model": _char("barrosan_spear_guard"), "height": 1.85,
		"hp": 200, "dmg": 16, "dmg_type": "pierce", "armor_class": "heavy", "armor": 4,
		"range": 0.0, "attack_cd": 1.3, "speed": 3.0, "vision": 20.0,
		"cost": {"food": 70, "timber": 20, "stone": 10}, "build_time": 18, "pop": 2, "produced_by": "sunspear_legion_hall",
		"desc": "A wall of bronze shields that never breaks and never retreats.",
	},
	"sunspear_bowman": {
		"race": "sunspear", "name": "Dominion Archer", "role": "ranged", "tier": 1,
		"model": _char("barrosan_crag_archer"), "height": 1.8,
		"hp": 90, "dmg": 18, "dmg_type": "pierce", "armor_class": "light", "armor": 0,
		"range": 16.0, "attack_cd": 1.4, "speed": 3.5, "vision": 24.0, "projectile": "arrow",
		"cost": {"food": 50, "timber": 30}, "build_time": 16, "pop": 1, "produced_by": "sunspear_legion_hall",
		"desc": "Volleys fired on the whistle, in perfect time.",
	},
	"sunspear_charioteer": {
		"race": "sunspear", "name": "Sun Charioteer", "role": "flanker", "tier": 2,
		"model": _char("barrosan_outrider"), "height": 1.8,
		"hp": 145, "dmg": 19, "dmg_type": "slash", "armor_class": "light", "armor": 1,
		"range": 0.0, "attack_cd": 1.0, "speed": 5.5, "vision": 26.0,
		"cost": {"food": 80, "gold": 20}, "build_time": 18, "pop": 2, "produced_by": "sunspear_legion_hall",
		"desc": "Bronze chariots that cut through open ground like a scythe.",
	},
	"sunspear_scorpion": {
		"race": "sunspear", "name": "Sun Scorpion", "role": "siege", "tier": 3,
		"model": "res://assets/props/vehicles/barrosan_ballista.glb", "height": 2.2,
		"hp": 170, "dmg": 56, "dmg_type": "siege", "armor_class": "medium", "armor": 2,
		"range": 22.0, "attack_cd": 2.7, "speed": 2.4, "vision": 26.0, "projectile": "bolt", "is_siege": true,
		"cost": {"timber": 120, "gold": 60}, "build_time": 30, "pop": 3, "produced_by": "sunspear_legion_hall",
		"desc": "The Dominion's bronze bolt-thrower. Built to break walls; the Rabagão was its first test.",
	},
	"sunspear_sunpriest": {
		"race": "sunspear", "name": "Sun Priest", "role": "healer", "tier": 2,
		"model": _char("lioraen_canopy_mender"), "height": 1.8,
		"hp": 95, "dmg": 8, "dmg_type": "arcane", "armor_class": "light", "armor": 0,
		"range": 14.0, "attack_cd": 1.5, "speed": 3.6, "vision": 24.0, "projectile": "lume_bolt",
		"heal": 11.0, "heal_range": 13.0, "heal_cd": 1.2,
		"cost": {"food": 80, "gold": 30}, "build_time": 20, "pop": 2, "produced_by": "sunspear_temple",
		"desc": "Preaches a world without Ascensions, and heals those who fight for it.",
	},
	"sunspear_hero_pharaoh": {
		"race": "sunspear", "name": "Sun Legate", "role": "hero", "tier": 1, "is_hero": true,
		"model": _char("sunspear_hero_pharaoh"), "height": 2.0,
		"hp": 400, "dmg": 34, "dmg_type": "slash", "armor_class": "heavy", "armor": 6,
		"range": 0.0, "attack_cd": 1.1, "speed": 3.9, "vision": 28.0, "pop": 0,
		"desc": "A field commander of the Aurean Dominion, sworn to the Regent's dream of a world without Ascensions.",
	},

	# ---------------- WYLDKIN ----------------
	"wyldkin_forager": {
		"race": "wyldkin", "name": "Wolfveil Tracker", "role": "worker", "tier": 1,
		"model": _char("lioraen_seedkeeper_worker"), "height": 1.7,
		"hp": 55, "dmg": 5, "dmg_type": "blunt", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 1.2, "speed": 3.9, "vision": 18.0,
		"cost": {"food": 50}, "build_time": 12, "pop": 1,
		"desc": "A seventh son who reads the forest like a letter.",
	},
	"wyldkin_clawwarrior": {
		"race": "wyldkin", "name": "Moonclaw", "role": "melee", "tier": 1,
		"model": _char("beastfolk_wolf_warrior"), "height": 1.85,
		"hp": 130, "dmg": 13, "dmg_type": "slash", "armor_class": "light", "armor": 1,
		"range": 0.0, "attack_cd": 1.0, "speed": 4.3, "vision": 20.0,
		"cost": {"food": 60, "timber": 10}, "build_time": 11, "pop": 1, "produced_by": "wyldkin_hunt_lodge",
		"desc": "When the moon is up, the seventh son stops being a man.",
	},
	"wyldkin_packguard": {
		"race": "wyldkin", "name": "Pack Guardian", "role": "defender", "tier": 1,
		"model": _char("lioraen_rootwarden_guard"), "height": 1.9,
		"hp": 185, "dmg": 12, "dmg_type": "blunt", "armor_class": "heavy", "armor": 4,
		"range": 0.0, "attack_cd": 1.4, "speed": 2.9, "vision": 20.0,
		"cost": {"food": 70, "timber": 30}, "build_time": 18, "pop": 2, "produced_by": "wyldkin_hunt_lodge",
		"desc": "The big wolf who stands between the pack and the hunters.",
	},
	"wyldkin_spinethrower": {
		"race": "wyldkin", "name": "Trap-Breaker", "role": "ranged", "tier": 1,
		"model": _char("lioraen_thorn_ranger"), "height": 1.8,
		"hp": 87, "dmg": 15, "dmg_type": "pierce", "armor_class": "light", "armor": 0,
		"range": 17.0, "attack_cd": 1.3, "speed": 3.9, "vision": 25.0, "projectile": "thorn",
		"cost": {"food": 50, "timber": 30}, "build_time": 14, "pop": 1, "produced_by": "wyldkin_hunt_lodge",
		"desc": "Hurls splinters of the stone wolf-traps back at those who built them.",
	},
	"wyldkin_direwolf": {
		"race": "wyldkin", "name": "Direwolf", "role": "flanker", "tier": 2,
		"model": _char("vorthak_gloom_hound"), "height": 1.3,
		"hp": 112, "dmg": 17, "dmg_type": "slash", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 0.8, "speed": 6.3, "vision": 30.0,
		"cost": {"food": 70, "gold": 15}, "build_time": 14, "pop": 1, "produced_by": "wyldkin_hunt_lodge",
		"desc": "A highland wolf the size of a garrano pony. Nothing outruns it.",
	},
	"wyldkin_moon_bear": {
		"race": "wyldkin", "name": "Moon Bear", "role": "antiarmor", "tier": 3,
		"model": _char("grimtusk_ogre_r709b"), "height": 2.3,
		"hp": 280, "dmg": 31, "dmg_type": "slash", "armor_class": "medium", "armor": 3,
		"range": 0.0, "attack_cd": 1.5, "speed": 3.6, "vision": 24.0,
		"cost": {"food": 120, "gold": 50}, "build_time": 26, "pop": 3, "produced_by": "wyldkin_hunt_lodge",
		"desc": "Once in a lifetime the full moon wakes a bear the size of a hut. The pack follows it.",
	},
	"wyldkin_shaman": {
		"race": "wyldkin", "name": "Moon-Singer", "role": "healer", "tier": 2,
		"model": _char("lioraen_canopy_mender"), "height": 1.8,
		"hp": 95, "dmg": 8, "dmg_type": "arcane", "armor_class": "light", "armor": 0,
		"range": 14.0, "attack_cd": 1.5, "speed": 3.6, "vision": 24.0, "projectile": "lume_bolt",
		"heal": 11.0, "heal_range": 13.0, "heal_cd": 1.2,
		"cost": {"food": 80, "gold": 30}, "build_time": 20, "pop": 2, "produced_by": "wyldkin_shaman_grove",
		"desc": "Howls the pack into a frenzy under the full moon.",
	},
	"wyldkin_hero_alpha": {
		"race": "wyldkin", "name": "Sétimo, the Seventh", "role": "hero", "tier": 1, "is_hero": true,
		"model": _char("wyldkin_hero_alpha"), "height": 2.0,
		"hp": 400, "dmg": 34, "dmg_type": "slash", "armor_class": "heavy", "armor": 6,
		"range": 0.0, "attack_cd": 1.0, "speed": 4.5, "vision": 28.0, "pop": 0,
		"desc": "The seventh son of a seventh son, loyal to whoever frees the wolves.",
	},

	# ---------------- HOLLOW LEGION ----------------
	"hollow_gravedigger": {
		"race": "hollow", "name": "Candle-Keeper", "role": "worker", "tier": 1,
		"model": _char("vorthak_bondservant_worker"), "height": 1.75,
		"hp": 50, "dmg": 5, "dmg_type": "blunt", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 1.2, "speed": 3.7, "vision": 18.0,
		"cost": {"food": 45}, "build_time": 11, "pop": 1,
		"desc": "Tends the procession's candles and the graves of the forgotten.",
	},
	"hollow_skeleton": {
		"race": "hollow", "name": "Forgotten Dead", "role": "melee", "tier": 1,
		"model": _char("undead_skeleton"), "height": 1.8,
		"hp": 85, "dmg": 11, "dmg_type": "slash", "armor_class": "unarmored", "armor": 0,
		"range": 0.0, "attack_cd": 1.0, "speed": 4.0, "vision": 20.0,
		"cost": {"food": 40, "gold": 5}, "build_time": 9, "pop": 1, "produced_by": "hollow_ossuary",
		"desc": "A soul no one remembers the name of. It walks, and walks, and walks.",
	},
	"hollow_boneguard": {
		"race": "hollow", "name": "Procession Guard", "role": "defender", "tier": 1,
		"model": _char("barrosan_spear_guard"), "height": 1.85,
		"hp": 175, "dmg": 12, "dmg_type": "pierce", "armor_class": "heavy", "armor": 4,
		"range": 0.0, "attack_cd": 1.3, "speed": 2.9, "vision": 20.0,
		"cost": {"food": 70, "timber": 20, "stone": 10}, "build_time": 18, "pop": 2, "produced_by": "hollow_ossuary",
		"desc": "An armored dead knight who keeps the living away from the cross.",
	},
	"hollow_bonearcher": {
		"race": "hollow", "name": "Grave Archer", "role": "ranged", "tier": 1,
		"model": _char("barrosan_crag_archer"), "height": 1.8,
		"hp": 88, "dmg": 15, "dmg_type": "pierce", "armor_class": "light", "armor": 0,
		"range": 16.0, "attack_cd": 1.4, "speed": 3.5, "vision": 24.0, "projectile": "arrow",
		"cost": {"food": 50, "timber": 30}, "build_time": 16, "pop": 1, "produced_by": "hollow_ossuary",
		"desc": "Loosing arrows cut from coffin wood.",
	},
	"hollow_wraith": {
		"race": "hollow", "name": "Drowned Wraith", "role": "flanker", "tier": 2,
		"model": _char("vorthak_gloom_hound"), "height": 1.5,
		"hp": 108, "dmg": 16, "dmg_type": "slash", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 0.8, "speed": 6.0, "vision": 30.0,
		"cost": {"food": 70, "gold": 15}, "build_time": 14, "pop": 1, "produced_by": "hollow_ossuary",
		"desc": "A soul from a drowned village, cold as the reservoir floor.",
	},
	"hollow_necromancer": {
		"race": "hollow", "name": "Dirge-Singer", "role": "caster", "tier": 3,
		"model": _char("vorthak_veil_warlock"), "height": 1.85,
		"hp": 100, "dmg": 30, "dmg_type": "arcane", "armor_class": "unarmored", "armor": 0,
		"range": 18.0, "attack_cd": 2.0, "speed": 3.3, "vision": 26.0, "projectile": "void_bolt", "splash": 3.5,
		"cost": {"food": 90, "gold": 70}, "build_time": 24, "pop": 2, "produced_by": "hollow_bone_spire",
		"desc": "Sings the procession's hymn. Its cold fire falls on whole ranks at once.",
	},
	"hollow_passing_bell": {
		"race": "hollow", "name": "Passing Bell", "role": "siege", "tier": 3, "is_siege": true,
		"model": "res://assets/props/vehicles/barrosan_ballista.glb", "height": 2.2,
		"hp": 160, "dmg": 56, "dmg_type": "siege", "armor_class": "medium", "armor": 2,
		"range": 22.0, "attack_cd": 2.8, "speed": 2.3, "vision": 26.0, "projectile": "void_bolt",
		"cost": {"timber": 110, "gold": 70}, "build_time": 30, "pop": 3, "produced_by": "hollow_bone_spire",
		"desc": "The bell the Compaña rings for whoever is to die next, carried on a bier. Walls that hear it crack.",
	},
	"hollow_hero_lich": {
		"race": "hollow", "name": "Candle-King", "role": "hero", "tier": 1, "is_hero": true,
		"model": _char("hollow_hero_lich"), "height": 2.1,
		"hp": 300, "dmg": 28, "dmg_type": "arcane", "armor_class": "light", "armor": 2,
		"range": 13.0, "attack_cd": 1.3, "speed": 4.0, "vision": 30.0, "projectile": "void_bolt", "splash": 3.0, "pop": 0,
		"desc": "The oldest of the forgotten dead, who leads the procession by candlelight. A living soul is always made to carry the cross before him.",
	},

	# ---------------- FROSTBORN JARLS ----------------
	"frostborn_thrall": {
		"race": "frostborn", "name": "Careto Page", "role": "worker", "tier": 1,
		"model": _char("barrosan_highlander_worker"), "height": 1.85,
		"hp": 60, "dmg": 5, "dmg_type": "blunt", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 1.2, "speed": 3.6, "vision": 18.0,
		"cost": {"food": 50}, "build_time": 12, "pop": 1,
		"desc": "A young masker who carries the bells and learns the steps.",
	},
	"frostborn_reaver": {
		"race": "frostborn", "name": "Careto Runner", "role": "melee", "tier": 1,
		"model": _char("frostborn_warrior"), "height": 1.9,
		"hp": 130, "dmg": 14, "dmg_type": "slash", "armor_class": "light", "armor": 1,
		"range": 0.0, "attack_cd": 1.1, "speed": 3.7, "vision": 20.0,
		# 70 for the stats a Clan Levy has for 55, and the Careto Host won
		# 16 of 52 over the three checks of plans 116 to 118 (270 matches).
		# 55 food and 11 seconds: 15-17 over 36 focus matches.
		"cost": {"food": 55}, "build_time": 11, "pop": 1, "produced_by": "frostborn_war_hall",
		"desc": "Red-and-green fringes, iron cowbells and a horned mask. Chases winter out of the villages.",
	},
	"frostborn_shieldmaiden": {
		"race": "frostborn", "name": "Larouco Shield", "role": "defender", "tier": 1,
		"model": _char("barrosan_spear_guard"), "height": 1.85,
		"hp": 185, "dmg": 14, "dmg_type": "pierce", "armor_class": "heavy", "armor": 4,
		"range": 0.0, "attack_cd": 1.3, "speed": 3.0, "vision": 20.0,
		"cost": {"food": 70, "timber": 20, "stone": 10}, "build_time": 18, "pop": 2, "produced_by": "frostborn_war_hall",
		"desc": "Holds the mountain road with an iron-rimmed shield painted with suns.",
	},
	"frostborn_hunter": {
		"race": "frostborn", "name": "Snow Hunter", "role": "ranged", "tier": 1,
		"model": _char("barrosan_crag_archer"), "height": 1.85,
		"hp": 90, "dmg": 16, "dmg_type": "pierce", "armor_class": "light", "armor": 0,
		"range": 16.0, "attack_cd": 1.4, "speed": 3.5, "vision": 24.0, "projectile": "arrow",
		"cost": {"food": 50, "timber": 30}, "build_time": 16, "pop": 1, "produced_by": "frostborn_war_hall",
		"desc": "Hunts on the Larouco where no one else can breathe.",
	},
	"frostborn_berserker": {
		"race": "frostborn", "name": "Wild Careto", "role": "melee", "tier": 2,
		"model": _char("frostborn_warrior"), "height": 2.0,
		"hp": 162, "dmg": 24, "dmg_type": "slash", "armor_class": "medium", "armor": 2,
		"range": 0.0, "attack_cd": 0.9, "speed": 4.4, "vision": 22.0,
		"cost": {"food": 90, "gold": 40}, "build_time": 18, "pop": 2, "produced_by": "frostborn_war_hall",
		"desc": "A masker who has danced so long that the mask has danced back.",
	},
	"frostborn_jotun": {
		"race": "frostborn", "name": "Winter Giant", "role": "antiarmor", "tier": 3,
		"model": _char("barrosan_anvil_breaker"), "height": 2.6,
		"hp": 260, "dmg": 30, "dmg_type": "blunt", "armor_class": "heavy", "armor": 5,
		"range": 0.0, "attack_cd": 1.7, "speed": 2.8, "vision": 20.0,
		"cost": {"food": 110, "stone": 40, "gold": 40}, "build_time": 26, "pop": 3, "produced_by": "frostborn_war_hall",
		"desc": "The oldest mask, carried by something that was never a man.",
	},
	# The three peoples that had neither a siege engine nor a healer (Careto,
	# Compaña, Ironmaw) sat at the bottom of every balance check and lost the
	# long matches: nothing of theirs outranged a tower. Each has an engine
	# now. All three borrow the Barrosan ballista model, as the Stone Mortar
	# and the Sun Scorpion do, until they get their own.
	"frostborn_pyre_cart": {
		"race": "frostborn", "name": "Entrudo Pyre", "role": "siege", "tier": 3, "is_siege": true,
		"model": "res://assets/props/vehicles/barrosan_ballista.glb", "height": 2.2,
		"hp": 175, "dmg": 54, "dmg_type": "siege", "armor_class": "medium", "armor": 2,
		"range": 21.0, "attack_cd": 2.7, "speed": 2.3, "vision": 26.0, "projectile": "cinder", "splash": 4.0,
		"cost": {"timber": 130, "gold": 50}, "build_time": 30, "pop": 3, "produced_by": "frostborn_war_hall",
		"desc": "The cart that carries the Entrudo to the fire on the last night of carnival. Now it throws the fire instead, over walls and onto whoever stands close together.",
	},
	"frostborn_hero_jarl": {
		"race": "frostborn", "name": "O Velho, the Eldest Mask", "role": "hero", "tier": 1, "is_hero": true,
		"model": _char("frostborn_hero_jarl"), "height": 2.1,
		"hp": 410, "dmg": 38, "dmg_type": "slash", "armor_class": "heavy", "armor": 6,
		"range": 0.0, "attack_cd": 1.1, "speed": 3.9, "vision": 28.0, "pop": 0,
		"desc": "Beneath the mask, another mask. He knows the truth and tells it only in riddles.",
	},
	}
