class_name UnitDefs
## Data definitions for every unit. Pure data — no logic.
## role: worker | melee | defender | ranged | flanker | antiarmor | caster | healer | siege | hero
## armor_class: unarmored | light | medium | heavy
## dmg_type: slash | pierce | blunt | arcane | siege

static func _char(id: String) -> String:
	return "res://assets/characters/%s/%s.glb" % [id, id]

static func get_all() -> Dictionary:
	return {
	# ---------------- BARROSAN CLANS ----------------
	"barrosan_worker": {
		"race": "barrosan", "name": "Highland Worker", "role": "worker", "tier": 1,
		"model": _char("barrosan_highlander_worker"), "height": 1.8, "visual_scale": 0.90,
		"hp": 60, "dmg": 5, "dmg_type": "blunt", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 1.2, "speed": 3.6, "vision": 18.0,
		"cost": {"food": 50}, "build_time": 12, "pop": 1,
		"desc": "Gathers resources and raises buildings. Backbone of the clan economy.",
	},
	"barrosan_clan_levy": {
		"race": "barrosan", "name": "Clan Levy", "role": "melee", "tier": 1,
		"model": _char("barrosan_clan_levy"), "height": 1.8,
		"hp": 130, "dmg": 12, "dmg_type": "slash", "armor_class": "light", "armor": 1,
		"range": 0.0, "attack_cd": 1.1, "speed": 3.7, "vision": 20.0,
		"cost": {"food": 60, "timber": 10}, "build_time": 14, "pop": 1, "produced_by": "barracks",
		"desc": "Cheap, sturdy frontline warrior. Good against unarmored foes.",
	},
	"barrosan_spear_guard": {
		"race": "barrosan", "name": "Stoneward Spears", "role": "defender", "tier": 1,
		"model": _char("barrosan_spear_guard"), "height": 1.85, "visual_scale": 1.0,
		"hp": 180, "dmg": 14, "dmg_type": "pierce", "armor_class": "heavy", "armor": 4,
		"range": 0.0, "attack_cd": 1.3, "speed": 3.0, "vision": 20.0,
		"cost": {"food": 70, "timber": 20, "stone": 10}, "build_time": 18, "pop": 2, "produced_by": "barracks",
		"desc": "Heavily armored anchor. Excels at holding the line and shredding large units.",
	},
	"barrosan_crag_archer": {
		"race": "barrosan", "name": "Crag Archer", "role": "ranged", "tier": 1,
		"model": _char("barrosan_crag_archer"), "height": 1.8,
		"hp": 90, "dmg": 16, "dmg_type": "pierce", "armor_class": "light", "armor": 0,
		"range": 16.0, "attack_cd": 1.4, "speed": 3.5, "vision": 24.0, "projectile": "arrow",
		"cost": {"food": 50, "timber": 30}, "build_time": 16, "pop": 1, "produced_by": "barracks",
		"desc": "Ranged pierce damage from the high ground. Fragile up close.",
	},
	"barrosan_outrider": {
		"race": "barrosan", "name": "Highland Outrider", "role": "flanker", "tier": 2,
		"model": _char("barrosan_outrider"), "height": 1.8,
		"hp": 120, "dmg": 15, "dmg_type": "slash", "armor_class": "light", "armor": 1,
		"range": 0.0, "attack_cd": 1.0, "speed": 5.4, "vision": 26.0,
		"cost": {"food": 80, "gold": 20}, "build_time": 18, "pop": 2, "produced_by": "barracks",
		"desc": "Fast raider that runs down archers and harasses workers.",
	},
	"barrosan_anvil_breaker": {
		"race": "barrosan", "name": "Anvil Breaker", "role": "antiarmor", "tier": 3,
		"model": _char("barrosan_anvil_breaker"), "height": 1.95,
		"hp": 240, "dmg": 30, "dmg_type": "blunt", "armor_class": "heavy", "armor": 5,
		"range": 0.0, "attack_cd": 1.7, "speed": 2.8, "vision": 20.0,
		"cost": {"food": 110, "stone": 40, "gold": 40}, "build_time": 26, "pop": 3, "produced_by": "barracks",
		"desc": "Slow siege-fist elite. Crushes heavy armor and structures.",
	},
	"barrosan_ballista": {
		"race": "barrosan", "name": "Clan Ballista", "role": "siege", "tier": 3, "is_siege": true,
		"model": "res://assets/props/vehicles/barrosan_ballista.glb", "height": 2.2,
		"hp": 160, "dmg": 55, "dmg_type": "siege", "armor_class": "medium", "armor": 2,
		"range": 22.0, "attack_cd": 2.6, "speed": 2.4, "vision": 26.0, "projectile": "bolt",
		"cost": {"timber": 120, "gold": 60}, "build_time": 30, "pop": 3, "produced_by": "barracks",
		"desc": "Long-range siege bolt-thrower. Devastating on buildings, weak in melee.",
	},

	# ---------------- LIORAEN CONCORD ----------------
	"lioraen_worker": {
		"race": "lioraen", "name": "Seedkeeper", "role": "worker", "tier": 1,
		"model": _char("lioraen_seedkeeper_worker"), "height": 1.75,
		"hp": 55, "dmg": 5, "dmg_type": "blunt", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 1.2, "speed": 3.9, "vision": 18.0,
		"cost": {"food": 50}, "build_time": 12, "pop": 1,
		"desc": "Tends resources and grows living structures. Nimble and quick.",
	},
	"lioraen_bloomdancer": {
		"race": "lioraen", "name": "Bloomdancer", "role": "melee", "tier": 1,
		"model": _char("lioraen_bloomdancer"), "height": 1.8,
		"hp": 115, "dmg": 14, "dmg_type": "slash", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 0.95, "speed": 4.2, "vision": 20.0,
		"cost": {"food": 60, "timber": 10}, "build_time": 13, "pop": 1, "produced_by": "barracks",
		"desc": "Swift blade-dancer that strikes fast and repositions faster.",
	},
	"lioraen_rootwarden_guard": {
		"race": "lioraen", "name": "Rootwarden", "role": "defender", "tier": 1,
		"model": _char("lioraen_rootwarden_guard"), "height": 1.9,
		"hp": 200, "dmg": 12, "dmg_type": "blunt", "armor_class": "heavy", "armor": 4,
		"range": 0.0, "attack_cd": 1.4, "speed": 2.9, "vision": 20.0,
		"cost": {"food": 70, "timber": 30}, "build_time": 18, "pop": 2, "produced_by": "barracks",
		"desc": "Living bark bulwark. Soaks damage so the swift units can flank.",
	},
	"lioraen_thorn_ranger": {
		"race": "lioraen", "name": "Thornrunner", "role": "ranged", "tier": 1,
		"model": _char("lioraen_thorn_ranger"), "height": 1.78,
		"hp": 85, "dmg": 15, "dmg_type": "pierce", "armor_class": "light", "armor": 0,
		"range": 17.0, "attack_cd": 1.3, "speed": 3.9, "vision": 25.0, "projectile": "thorn",
		"cost": {"food": 50, "timber": 30}, "build_time": 16, "pop": 1, "produced_by": "barracks",
		"desc": "Mobile guerrilla archer. Kites enemies through the bloomfields.",
	},
	"lioraen_windstrider": {
		"race": "lioraen", "name": "Windstrider", "role": "flanker", "tier": 2,
		"model": _char("lioraen_windstrider"), "height": 1.8,
		"hp": 130, "dmg": 18, "dmg_type": "pierce", "armor_class": "light", "armor": 1,
		"range": 0.0, "attack_cd": 0.9, "speed": 5.8, "vision": 28.0,
		"cost": {"food": 90, "gold": 20}, "build_time": 18, "pop": 2, "produced_by": "barracks",
		"desc": "The fastest unit in the realm. Deadly charging lancer.",
	},
	"lioraen_canopy_mender": {
		"race": "lioraen", "name": "Canopy Mender", "role": "healer", "tier": 2,
		"model": _char("lioraen_canopy_mender"), "height": 1.8,
		"hp": 95, "dmg": 8, "dmg_type": "arcane", "armor_class": "light", "armor": 0,
		"range": 14.0, "attack_cd": 1.5, "speed": 3.6, "vision": 24.0, "projectile": "lume_bolt",
		"heal": 14.0, "heal_range": 13.0, "heal_cd": 1.2,
		"cost": {"food": 80, "gold": 30}, "build_time": 20, "pop": 2, "produced_by": "arcane",
		"desc": "Restores health to nearby allies. Turns skirmishes into wars of attrition you win.",
	},
	"lioraen_thornthrower": {
		"race": "lioraen", "name": "Thornthrower", "role": "siege", "tier": 3, "is_siege": true,
		"model": "res://assets/props/vehicles/lioraen_thornthrower.glb", "height": 2.2,
		"hp": 150, "dmg": 48, "dmg_type": "siege", "armor_class": "medium", "armor": 1,
		"range": 21.0, "attack_cd": 2.4, "speed": 2.6, "vision": 26.0, "projectile": "thornpod", "splash": 4.0,
		"cost": {"timber": 130, "gold": 50}, "build_time": 28, "pop": 3, "produced_by": "arcane",
		"desc": "Living catapult that lobs bursting thorn-pods with splash damage.",
	},

	# ---------------- VORTHAK CABAL ----------------
	"vorthak_worker": {
		"race": "vorthak", "name": "Bondservant", "role": "worker", "tier": 1,
		"model": _char("vorthak_bondservant_worker"), "height": 1.75,
		"hp": 50, "dmg": 5, "dmg_type": "blunt", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 1.2, "speed": 3.7, "vision": 18.0,
		"cost": {"food": 45}, "build_time": 11, "pop": 1,
		"desc": "Driven drudge that gathers and raises the Cabal's dark structures.",
	},
	"vorthak_ash_thrall": {
		"race": "vorthak", "name": "Ash Thrall", "role": "melee", "tier": 1,
		"model": _char("vorthak_ash_thrall"), "height": 1.8,
		"hp": 95, "dmg": 11, "dmg_type": "slash", "armor_class": "unarmored", "armor": 0,
		"range": 0.0, "attack_cd": 1.0, "speed": 4.0, "vision": 20.0,
		"cost": {"food": 40, "gold": 5}, "build_time": 9, "pop": 1, "produced_by": "barracks",
		"desc": "Expendable swarm body. Cheap and fast — bury the enemy in numbers.",
	},
	"vorthak_rift_blade": {
		"race": "vorthak", "name": "Rift Blade", "role": "melee", "tier": 2,
		"model": _char("vorthak_rift_blade"), "height": 1.82,
		"hp": 160, "dmg": 24, "dmg_type": "slash", "armor_class": "medium", "armor": 2,
		"range": 0.0, "attack_cd": 0.9, "speed": 4.4, "vision": 22.0,
		"cost": {"food": 90, "gold": 40}, "build_time": 18, "pop": 2, "produced_by": "barracks",
		"desc": "Elite glass-armored striker. Hits hard and fast, but bleeds gold.",
	},
	"vorthak_cinder_spitter": {
		"race": "vorthak", "name": "Cinder Spitter", "role": "ranged", "tier": 1,
		"model": _char("vorthak_cinder_spitter"), "height": 1.78,
		"hp": 80, "dmg": 17, "dmg_type": "arcane", "armor_class": "unarmored", "armor": 0,
		"range": 16.0, "attack_cd": 1.4, "speed": 3.5, "vision": 24.0, "projectile": "cinder",
		"cost": {"food": 55, "gold": 20}, "build_time": 16, "pop": 1, "produced_by": "barracks",
		"desc": "Spits burning Lume-fire. Ignores heavy armor with arcane damage.",
	},
	"vorthak_gloom_hound": {
		"race": "vorthak", "name": "Gloom Hound", "role": "flanker", "tier": 2,
		"model": _char("vorthak_gloom_hound"), "height": 1.3,
		"hp": 110, "dmg": 16, "dmg_type": "slash", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 0.8, "speed": 6.0, "vision": 30.0,
		"cost": {"food": 70, "gold": 15}, "build_time": 14, "pop": 1, "produced_by": "barracks",
		"desc": "Feral beast that outruns everything and savages fleeing units.",
	},
	"vorthak_veil_warlock": {
		"race": "vorthak", "name": "Veil Warlock", "role": "caster", "tier": 3,
		"model": _char("vorthak_veil_warlock"), "height": 1.85,
		"hp": 100, "dmg": 30, "dmg_type": "arcane", "armor_class": "unarmored", "armor": 0,
		"range": 18.0, "attack_cd": 2.0, "speed": 3.3, "vision": 26.0, "projectile": "void_bolt", "splash": 3.5,
		"cost": {"food": 90, "gold": 70}, "build_time": 24, "pop": 2, "produced_by": "arcane",
		"desc": "Devastating area caster. Melts clustered armies with void magic.",
	},
	"vorthak_fracture_engine": {
		"race": "vorthak", "name": "Fracture Engine", "role": "siege", "tier": 3, "is_siege": true,
		"model": "res://assets/props/vehicles/vorthak_fracture_engine.glb", "height": 2.3,
		"hp": 170, "dmg": 60, "dmg_type": "siege", "armor_class": "medium", "armor": 2,
		"range": 22.0, "attack_cd": 2.8, "speed": 2.3, "vision": 26.0, "projectile": "rift_shell", "splash": 5.0,
		"cost": {"timber": 90, "gold": 90}, "build_time": 30, "pop": 3, "produced_by": "arcane",
		"desc": "Unstable mortar that hurls raw Lume. Enormous splash siege damage.",
	},

	# ---------------- HEROES ----------------
	"barrosan_hero_thane": {
		"race": "barrosan", "name": "War-Thane", "role": "hero", "tier": 1, "is_hero": true,
		"model": _char("barrosan_hero_thane"), "height": 2.0, "visual_scale": 1.13,
		"hp": 400, "dmg": 34, "dmg_type": "slash", "armor_class": "heavy", "armor": 6,
		"range": 0.0, "attack_cd": 1.1, "speed": 3.9, "vision": 28.0, "pop": 0,
		"desc": "Frontline commander. Rally aura strengthens nearby allies.",
	},
	"lioraen_hero_warden": {
		"race": "lioraen", "name": "Grove Warden", "role": "hero", "tier": 1, "is_hero": true,
		"model": _char("lioraen_hero_warden"), "height": 1.95,
		"hp": 340, "dmg": 26, "dmg_type": "arcane", "armor_class": "medium", "armor": 3,
		"range": 15.0, "attack_cd": 1.2, "speed": 4.3, "vision": 30.0, "projectile": "lume_bolt", "pop": 0,
		"desc": "Ranger-mystic. Heals allies and roots enemies in place.",
	},
	"vorthak_hero_binder": {
		"race": "vorthak", "name": "Rift Binder", "role": "hero", "tier": 1, "is_hero": true,
		"model": _char("vorthak_hero_binder"), "height": 2.0,
		"hp": 300, "dmg": 44, "dmg_type": "arcane", "armor_class": "light", "armor": 2,
		"range": 17.0, "attack_cd": 1.3, "speed": 4.0, "vision": 30.0, "projectile": "void_bolt", "splash": 3.0, "pop": 0,
		"desc": "Glass-cannon battlemage. Enormous burst magic, fragile if caught.",
	},

	# ---------------- GRIMTUSK HORDE ----------------
	"grimtusk_peon": {
		"race": "grimtusk", "name": "Grimtusk Peon", "role": "worker", "tier": 1,
		"model": _char("orc_grunt"), "height": 1.85,
		"hp": 58, "dmg": 5, "dmg_type": "blunt", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 1.2, "speed": 3.7, "vision": 18.0,
		"cost": {"food": 50}, "build_time": 12, "pop": 1,
		"desc": "Tough orc laborer who gathers resources and raises the Horde's crude but effective buildings.",
	},
	"grimtusk_grunt": {
		"race": "grimtusk", "name": "Grimtusk Grunt", "role": "melee", "tier": 1,
		"model": _char("orc_grunt"), "height": 1.9,
		"hp": 110, "dmg": 11, "dmg_type": "slash", "armor_class": "light", "armor": 1,
		"range": 0.0, "attack_cd": 1.0, "speed": 4.0, "vision": 20.0,
		"cost": {"food": 40, "gold": 5}, "build_time": 9, "pop": 1, "produced_by": "grimtusk_warcamp",
		"desc": "The green tide in person. Cheap, fearless, and absolutely everywhere.",
	},
	"grimtusk_bowcrusha": {
		"race": "grimtusk", "name": "Bow-Crusha", "role": "ranged", "tier": 1,
		"model": _char("barrosan_crag_archer"), "height": 1.9,
		"hp": 90, "dmg": 16, "dmg_type": "pierce", "armor_class": "light", "armor": 0,
		"range": 16.0, "attack_cd": 1.4, "speed": 3.5, "vision": 24.0, "projectile": "arrow",
		"cost": {"food": 50, "timber": 30}, "build_time": 16, "pop": 1, "produced_by": "grimtusk_warcamp",
		"desc": "Orc archer who draws a bow as big as most humans. Doesn't miss much.",
	},
	"grimtusk_wolfrider": {
		"race": "grimtusk", "name": "Wolf Rider", "role": "flanker", "tier": 2,
		"model": _char("vorthak_gloom_hound"), "height": 1.4,
		"hp": 115, "dmg": 17, "dmg_type": "slash", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 0.8, "speed": 6.0, "vision": 30.0,
		"cost": {"food": 70, "gold": 15}, "build_time": 14, "pop": 1, "produced_by": "grimtusk_warcamp",
		"desc": "Orc astride a massive war-wolf. Runs down anything that tries to flee.",
	},
	"grimtusk_berserker": {
		"race": "grimtusk", "name": "Grimtusk Berserker", "role": "melee", "tier": 2,
		"model": _char("orc_grunt"), "height": 2.0,
		"hp": 165, "dmg": 26, "dmg_type": "slash", "armor_class": "medium", "armor": 2,
		"range": 0.0, "attack_cd": 0.9, "speed": 4.5, "vision": 22.0,
		"cost": {"food": 90, "gold": 40}, "build_time": 18, "pop": 2, "produced_by": "grimtusk_warcamp",
		"desc": "Blood-drunk elite whose rage makes him nearly impossible to bring down.",
	},
	"grimtusk_ogre": {
		"race": "grimtusk", "name": "Grimtusk Ogre", "role": "antiarmor", "tier": 3,
		"model": _char("barrosan_anvil_breaker"), "height": 2.5,
		"hp": 245, "dmg": 30, "dmg_type": "blunt", "armor_class": "heavy", "armor": 5,
		"range": 0.0, "attack_cd": 1.7, "speed": 2.8, "vision": 20.0,
		"cost": {"food": 110, "stone": 40, "gold": 40}, "build_time": 26, "pop": 3, "produced_by": "grimtusk_warcamp",
		"desc": "Club-swinging giant. Crushes armor, walls, and anything that dares stand still.",
	},
	"grimtusk_hero_warlord": {
		"race": "grimtusk", "name": "Warboss", "role": "hero", "tier": 1, "is_hero": true,
		"model": _char("grimtusk_hero_warlord"), "height": 2.2,
		"hp": 400, "dmg": 34, "dmg_type": "slash", "armor_class": "heavy", "armor": 6,
		"range": 0.0, "attack_cd": 1.1, "speed": 3.9, "vision": 28.0, "pop": 0,
		"desc": "The biggest, meanest orc alive. His battle-cry alone costs the enemy a third of their morale.",
	},

	# ---------------- SYLVAN COURT ----------------
	"sylvan_acolyte": {
		"race": "sylvan", "name": "Court Acolyte", "role": "worker", "tier": 1,
		"model": _char("lioraen_seedkeeper_worker"), "height": 1.75,
		"hp": 55, "dmg": 5, "dmg_type": "blunt", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 1.2, "speed": 3.9, "vision": 18.0,
		"cost": {"food": 50}, "build_time": 12, "pop": 1,
		"desc": "Graceful elven acolyte who tends the Court's forests and raises its shimmering structures.",
	},
	"sylvan_bladesinger": {
		"race": "sylvan", "name": "Bladesinger", "role": "melee", "tier": 1,
		"model": _char("lioraen_bloomdancer"), "height": 1.8,
		"hp": 130, "dmg": 12, "dmg_type": "slash", "armor_class": "light", "armor": 1,
		"range": 0.0, "attack_cd": 1.1, "speed": 3.7, "vision": 20.0,
		"cost": {"food": 60, "timber": 10}, "build_time": 14, "pop": 1, "produced_by": "sylvan_bladehall",
		"desc": "Elven sword-dancer who weaves blade and spell into a lethal aria.",
	},
	"sylvan_warden": {
		"race": "sylvan", "name": "Grove Warden", "role": "defender", "tier": 1,
		"model": _char("lioraen_rootwarden_guard"), "height": 1.9,
		"hp": 180, "dmg": 14, "dmg_type": "pierce", "armor_class": "heavy", "armor": 4,
		"range": 0.0, "attack_cd": 1.3, "speed": 3.0, "vision": 20.0,
		"cost": {"food": 70, "timber": 20, "stone": 10}, "build_time": 18, "pop": 2, "produced_by": "sylvan_bladehall",
		"desc": "Armored elven guardian who forms an unbreakable wall of silver and bark.",
	},
	"sylvan_longbow": {
		"race": "sylvan", "name": "Starwood Longbow", "role": "ranged", "tier": 1,
		"model": _char("highelf_archer"), "height": 1.78,
		"hp": 88, "dmg": 17, "dmg_type": "pierce", "armor_class": "light", "armor": 0,
		"range": 18.0, "attack_cd": 1.4, "speed": 3.5, "vision": 27.0, "projectile": "arrow",
		"cost": {"food": 50, "timber": 30}, "build_time": 16, "pop": 1, "produced_by": "sylvan_bladehall",
		"desc": "Elven longbow master with unmatched range and eagle-sharp vision.",
	},
	"sylvan_windrunner": {
		"race": "sylvan", "name": "Windrunner", "role": "flanker", "tier": 2,
		"model": _char("lioraen_windstrider"), "height": 1.8,
		"hp": 130, "dmg": 18, "dmg_type": "pierce", "armor_class": "light", "armor": 1,
		"range": 0.0, "attack_cd": 0.9, "speed": 5.8, "vision": 28.0,
		"cost": {"food": 90, "gold": 20}, "build_time": 18, "pop": 2, "produced_by": "sylvan_bladehall",
		"desc": "Blur of silver and steel that flanks faster than the eye can track.",
	},
	"sylvan_lightweaver": {
		"race": "sylvan", "name": "Lightweaver", "role": "healer", "tier": 2,
		"model": _char("lioraen_canopy_mender"), "height": 1.8,
		"hp": 95, "dmg": 8, "dmg_type": "arcane", "armor_class": "light", "armor": 0,
		"range": 14.0, "attack_cd": 1.5, "speed": 3.6, "vision": 24.0, "projectile": "lume_bolt",
		"heal": 14.0, "heal_range": 13.0, "heal_cd": 1.2,
		"cost": {"food": 80, "gold": 30}, "build_time": 20, "pop": 2, "produced_by": "sylvan_arcanum",
		"desc": "Weaves golden light to mend wounds mid-battle, keeping your finest warriors alive.",
	},
	"sylvan_hero_archon": {
		"race": "sylvan", "name": "High Archon", "role": "hero", "tier": 1, "is_hero": true,
		"model": _char("sylvan_hero_archon"), "height": 1.95,
		"hp": 340, "dmg": 26, "dmg_type": "arcane", "armor_class": "medium", "armor": 3,
		"range": 15.0, "attack_cd": 1.2, "speed": 4.3, "vision": 30.0, "projectile": "lume_bolt", "pop": 0,
		"desc": "The pinnacle of elven mastery — heals allies, devastates foes, and sees all.",
	},

	# ---------------- KARAK DWARVES ----------------
	"karak_miner": {
		"race": "karak", "name": "Karak Miner", "role": "worker", "tier": 1,
		"model": _char("barrosan_highlander_worker"), "height": 1.55,
		"hp": 60, "dmg": 5, "dmg_type": "blunt", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 1.2, "speed": 3.6, "vision": 18.0,
		"cost": {"food": 50}, "build_time": 12, "pop": 1,
		"desc": "Stout dwarven miner who hews stone, hauls timber, and raises the Hold's immovable structures.",
	},
	"karak_warrior": {
		"race": "karak", "name": "Karak Warrior", "role": "melee", "tier": 1,
		"model": _char("dwarf_warrior"), "height": 1.6,
		"hp": 150, "dmg": 12, "dmg_type": "blunt", "armor_class": "medium", "armor": 2,
		"range": 0.0, "attack_cd": 1.1, "speed": 3.2, "vision": 20.0,
		"cost": {"food": 60, "timber": 10}, "build_time": 14, "pop": 1, "produced_by": "karak_warforge",
		"desc": "Compact powerhouse clad in layered plate. Slower than most, tougher than all.",
	},
	"karak_ironbreaker": {
		"race": "karak", "name": "Ironbreaker", "role": "defender", "tier": 1,
		"model": _char("barrosan_spear_guard"), "height": 1.65,
		"hp": 195, "dmg": 14, "dmg_type": "blunt", "armor_class": "heavy", "armor": 5,
		"range": 0.0, "attack_cd": 1.3, "speed": 2.8, "vision": 20.0,
		"cost": {"food": 70, "timber": 20, "stone": 10}, "build_time": 18, "pop": 2, "produced_by": "karak_warforge",
		"desc": "Wall of rune-forged iron. Nearly impossible to move and even harder to kill.",
	},
	"karak_quarreler": {
		"race": "karak", "name": "Quarreler", "role": "ranged", "tier": 1,
		"model": _char("barrosan_crag_archer"), "height": 1.6,
		"hp": 90, "dmg": 16, "dmg_type": "pierce", "armor_class": "light", "armor": 0,
		"range": 16.0, "attack_cd": 1.4, "speed": 3.5, "vision": 24.0, "projectile": "bolt",
		"cost": {"food": 50, "timber": 30}, "build_time": 16, "pop": 1, "produced_by": "karak_warforge",
		"desc": "Dwarven crossbowman with a windlass crank. Punches through armor like tin foil.",
	},
	"karak_hammerer": {
		"race": "karak", "name": "Hammerer", "role": "antiarmor", "tier": 3,
		"model": _char("barrosan_anvil_breaker"), "height": 1.7,
		"hp": 245, "dmg": 32, "dmg_type": "blunt", "armor_class": "heavy", "armor": 5,
		"range": 0.0, "attack_cd": 1.7, "speed": 2.8, "vision": 20.0,
		"cost": {"food": 110, "stone": 40, "gold": 40}, "build_time": 26, "pop": 3, "produced_by": "karak_warforge",
		"desc": "Elite warrior whose great hammer deforms any armor it touches. The gate-breaker.",
	},
	"karak_cannon": {
		"race": "karak", "name": "Karak Cannon", "role": "siege", "tier": 3, "is_siege": true,
		"model": "res://assets/props/vehicles/barrosan_ballista.glb", "height": 2.0,
		"hp": 165, "dmg": 58, "dmg_type": "siege", "armor_class": "medium", "armor": 2,
		"range": 22.0, "attack_cd": 2.8, "speed": 2.2, "vision": 26.0, "projectile": "bolt",
		"cost": {"timber": 120, "gold": 60}, "build_time": 30, "pop": 3, "produced_by": "karak_warforge",
		"desc": "Squat iron cannon that fires stone balls through fortifications. Reloads slowly; fires once, wins.",
	},
	"karak_hero_thanelord": {
		"race": "karak", "name": "Thane-Lord", "role": "hero", "tier": 1, "is_hero": true,
		"model": _char("karak_hero_thanelord"), "height": 1.75,
		"hp": 440, "dmg": 34, "dmg_type": "blunt", "armor_class": "heavy", "armor": 7,
		"range": 0.0, "attack_cd": 1.1, "speed": 3.6, "vision": 28.0, "pop": 0,
		"desc": "Ancient lord of the deep hold. His rune-covered armor shrugs off blows that would flatten a troll.",
	},

	# ---------------- SUNSPEAR DOMINION ----------------
	"sunspear_laborer": {
		"race": "sunspear", "name": "Sunspear Laborer", "role": "worker", "tier": 1,
		"model": _char("barrosan_highlander_worker"), "height": 1.8,
		"hp": 60, "dmg": 5, "dmg_type": "blunt", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 1.2, "speed": 3.6, "vision": 18.0,
		"cost": {"food": 50}, "build_time": 12, "pop": 1,
		"desc": "Industrious desert laborer who raises the Dominion's imposing stone structures.",
	},
	"sunspear_legion": {
		"race": "sunspear", "name": "Sunspear Legionary", "role": "melee", "tier": 1,
		"model": _char("sunspear_legionary"), "height": 1.8,
		"hp": 130, "dmg": 12, "dmg_type": "slash", "armor_class": "light", "armor": 1,
		"range": 0.0, "attack_cd": 1.1, "speed": 3.7, "vision": 20.0,
		"cost": {"food": 60, "timber": 10}, "build_time": 14, "pop": 1, "produced_by": "sunspear_legion_hall",
		"desc": "Disciplined desert soldier who fights in tight formation with sun-bronze sword and shield.",
	},
	"sunspear_phalanx": {
		"race": "sunspear", "name": "Sunspear Phalanx", "role": "defender", "tier": 1,
		"model": _char("barrosan_spear_guard"), "height": 1.85,
		"hp": 180, "dmg": 14, "dmg_type": "pierce", "armor_class": "heavy", "armor": 4,
		"range": 0.0, "attack_cd": 1.3, "speed": 3.0, "vision": 20.0,
		"cost": {"food": 70, "timber": 20, "stone": 10}, "build_time": 18, "pop": 2, "produced_by": "sunspear_legion_hall",
		"desc": "Heavy spearmen who lock shields and hold the line under scorching desert sun.",
	},
	"sunspear_bowman": {
		"race": "sunspear", "name": "Sunspear Bowman", "role": "ranged", "tier": 1,
		"model": _char("barrosan_crag_archer"), "height": 1.8,
		"hp": 90, "dmg": 16, "dmg_type": "pierce", "armor_class": "light", "armor": 0,
		"range": 16.0, "attack_cd": 1.4, "speed": 3.5, "vision": 24.0, "projectile": "arrow",
		"cost": {"food": 50, "timber": 30}, "build_time": 16, "pop": 1, "produced_by": "sunspear_legion_hall",
		"desc": "Composite bow archer trained to strike in synchronized volleys on command.",
	},
	"sunspear_charioteer": {
		"race": "sunspear", "name": "Sun Charioteer", "role": "flanker", "tier": 2,
		"model": _char("barrosan_outrider"), "height": 1.8,
		"hp": 125, "dmg": 16, "dmg_type": "slash", "armor_class": "light", "armor": 1,
		"range": 0.0, "attack_cd": 1.0, "speed": 5.5, "vision": 26.0,
		"cost": {"food": 80, "gold": 20}, "build_time": 18, "pop": 2, "produced_by": "sunspear_legion_hall",
		"desc": "Desert charioteer who crashes through enemy flanks in a storm of blades and hooves.",
	},
	"sunspear_sunpriest": {
		"race": "sunspear", "name": "Sun Priest", "role": "healer", "tier": 2,
		"model": _char("lioraen_canopy_mender"), "height": 1.8,
		"hp": 95, "dmg": 8, "dmg_type": "arcane", "armor_class": "light", "armor": 0,
		"range": 14.0, "attack_cd": 1.5, "speed": 3.6, "vision": 24.0, "projectile": "lume_bolt",
		"heal": 14.0, "heal_range": 13.0, "heal_cd": 1.2,
		"cost": {"food": 80, "gold": 30}, "build_time": 20, "pop": 2, "produced_by": "sunspear_temple",
		"desc": "Channels solar radiance to mend wounds, granting the legion the endurance of the desert sun.",
	},
	"sunspear_hero_pharaoh": {
		"race": "sunspear", "name": "Sun Pharaoh", "role": "hero", "tier": 1, "is_hero": true,
		"model": _char("sunspear_hero_pharaoh"), "height": 2.0,
		"hp": 400, "dmg": 34, "dmg_type": "slash", "armor_class": "heavy", "armor": 6,
		"range": 0.0, "attack_cd": 1.1, "speed": 3.9, "vision": 28.0, "pop": 0,
		"desc": "God-king of the desert. His golden presence inspires the legion to feats beyond mortal endurance.",
	},

	# ---------------- WYLDKIN ----------------
	"wyldkin_forager": {
		"race": "wyldkin", "name": "Wyldkin Forager", "role": "worker", "tier": 1,
		"model": _char("lioraen_seedkeeper_worker"), "height": 1.7,
		"hp": 55, "dmg": 5, "dmg_type": "blunt", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 1.2, "speed": 3.9, "vision": 18.0,
		"cost": {"food": 50}, "build_time": 12, "pop": 1,
		"desc": "Nimble beastfolk who gathers with quick claws and raises the pack's living dens.",
	},
	"wyldkin_clawwarrior": {
		"race": "wyldkin", "name": "Clawwarrior", "role": "melee", "tier": 1,
		"model": _char("beastfolk_wolf_warrior"), "height": 1.85,
		"hp": 130, "dmg": 13, "dmg_type": "slash", "armor_class": "light", "armor": 1,
		"range": 0.0, "attack_cd": 1.0, "speed": 4.3, "vision": 20.0,
		"cost": {"food": 60, "timber": 10}, "build_time": 14, "pop": 1, "produced_by": "wyldkin_hunt_lodge",
		"desc": "Furred pack warrior who closes distance terrifyingly fast and fights with vicious claw-blades.",
	},
	"wyldkin_packguard": {
		"race": "wyldkin", "name": "Packguard", "role": "defender", "tier": 1,
		"model": _char("lioraen_rootwarden_guard"), "height": 1.9,
		"hp": 185, "dmg": 12, "dmg_type": "blunt", "armor_class": "heavy", "armor": 4,
		"range": 0.0, "attack_cd": 1.4, "speed": 2.9, "vision": 20.0,
		"cost": {"food": 70, "timber": 30}, "build_time": 18, "pop": 2, "produced_by": "wyldkin_hunt_lodge",
		"desc": "Hulking beastguard who shields the pack with hide as tough as iron bark.",
	},
	"wyldkin_spinethrower": {
		"race": "wyldkin", "name": "Spinethrower", "role": "ranged", "tier": 1,
		"model": _char("lioraen_thorn_ranger"), "height": 1.8,
		"hp": 87, "dmg": 15, "dmg_type": "pierce", "armor_class": "light", "armor": 0,
		"range": 17.0, "attack_cd": 1.3, "speed": 3.9, "vision": 25.0, "projectile": "thorn",
		"cost": {"food": 50, "timber": 30}, "build_time": 16, "pop": 1, "produced_by": "wyldkin_hunt_lodge",
		"desc": "Launches razor-sharp quills with surprising accuracy from thick forest cover.",
	},
	"wyldkin_direwolf": {
		"race": "wyldkin", "name": "Direwolf", "role": "flanker", "tier": 2,
		"model": _char("vorthak_gloom_hound"), "height": 1.3,
		"hp": 112, "dmg": 17, "dmg_type": "slash", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 0.8, "speed": 6.3, "vision": 30.0,
		"cost": {"food": 70, "gold": 15}, "build_time": 14, "pop": 1, "produced_by": "wyldkin_hunt_lodge",
		"desc": "The alpha-bred direwolf. Faster than anything else in the field and twice as hungry.",
	},
	"wyldkin_shaman": {
		"race": "wyldkin", "name": "Wyldkin Shaman", "role": "healer", "tier": 2,
		"model": _char("lioraen_canopy_mender"), "height": 1.8,
		"hp": 95, "dmg": 8, "dmg_type": "arcane", "armor_class": "light", "armor": 0,
		"range": 14.0, "attack_cd": 1.5, "speed": 3.6, "vision": 24.0, "projectile": "lume_bolt",
		"heal": 14.0, "heal_range": 13.0, "heal_cd": 1.2,
		"cost": {"food": 80, "gold": 30}, "build_time": 20, "pop": 2, "produced_by": "wyldkin_shaman_grove",
		"desc": "Spirit-bonded healer who calls on beast-totems to mend the pack between skirmishes.",
	},
	"wyldkin_hero_alpha": {
		"race": "wyldkin", "name": "Pack Alpha", "role": "hero", "tier": 1, "is_hero": true,
		"model": _char("wyldkin_hero_alpha"), "height": 2.0,
		"hp": 400, "dmg": 34, "dmg_type": "slash", "armor_class": "heavy", "armor": 6,
		"range": 0.0, "attack_cd": 1.0, "speed": 4.5, "vision": 28.0, "pop": 0,
		"desc": "The fastest alpha in history. Where he runs the pack follows — and nothing outpaces the pack.",
	},

	# ---------------- HOLLOW LEGION ----------------
	"hollow_gravedigger": {
		"race": "hollow", "name": "Grave Digger", "role": "worker", "tier": 1,
		"model": _char("vorthak_bondservant_worker"), "height": 1.75,
		"hp": 50, "dmg": 5, "dmg_type": "blunt", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 1.2, "speed": 3.7, "vision": 18.0,
		"cost": {"food": 45}, "build_time": 11, "pop": 1,
		"desc": "Shambling undead laborer who scrapes resources from bone-dry earth and raises dark structures.",
	},
	"hollow_skeleton": {
		"race": "hollow", "name": "Hollow Skeleton", "role": "melee", "tier": 1,
		"model": _char("undead_skeleton"), "height": 1.8,
		"hp": 95, "dmg": 11, "dmg_type": "slash", "armor_class": "unarmored", "armor": 0,
		"range": 0.0, "attack_cd": 1.0, "speed": 4.0, "vision": 20.0,
		"cost": {"food": 40, "gold": 5}, "build_time": 9, "pop": 1, "produced_by": "hollow_ossuary",
		"desc": "Re-animated bones with rusty weapons. Frighteningly cheap and utterly fearless.",
	},
	"hollow_boneguard": {
		"race": "hollow", "name": "Boneguard", "role": "defender", "tier": 1,
		"model": _char("barrosan_spear_guard"), "height": 1.85,
		"hp": 175, "dmg": 12, "dmg_type": "pierce", "armor_class": "heavy", "armor": 4,
		"range": 0.0, "attack_cd": 1.3, "speed": 2.9, "vision": 20.0,
		"cost": {"food": 70, "timber": 20, "stone": 10}, "build_time": 18, "pop": 2, "produced_by": "hollow_ossuary",
		"desc": "Armored skeletal guardian that feels no pain and knows no retreat.",
	},
	"hollow_bonearcher": {
		"race": "hollow", "name": "Bone Archer", "role": "ranged", "tier": 1,
		"model": _char("barrosan_crag_archer"), "height": 1.8,
		"hp": 88, "dmg": 15, "dmg_type": "pierce", "armor_class": "light", "armor": 0,
		"range": 16.0, "attack_cd": 1.4, "speed": 3.5, "vision": 24.0, "projectile": "arrow",
		"cost": {"food": 50, "timber": 30}, "build_time": 16, "pop": 1, "produced_by": "hollow_ossuary",
		"desc": "Skeletal archer with bony fingers that never tire, loosing arrows without rest.",
	},
	"hollow_wraith": {
		"race": "hollow", "name": "Hollow Wraith", "role": "flanker", "tier": 2,
		"model": _char("vorthak_gloom_hound"), "height": 1.5,
		"hp": 108, "dmg": 16, "dmg_type": "slash", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 0.8, "speed": 6.0, "vision": 30.0,
		"cost": {"food": 70, "gold": 15}, "build_time": 14, "pop": 1, "produced_by": "hollow_ossuary",
		"desc": "Spectral flanker that drifts through the battlefield and strikes without warning.",
	},
	"hollow_necromancer": {
		"race": "hollow", "name": "Necromancer", "role": "caster", "tier": 3,
		"model": _char("vorthak_veil_warlock"), "height": 1.85,
		"hp": 100, "dmg": 30, "dmg_type": "arcane", "armor_class": "unarmored", "armor": 0,
		"range": 18.0, "attack_cd": 2.0, "speed": 3.3, "vision": 26.0, "projectile": "void_bolt", "splash": 3.5,
		"cost": {"food": 90, "gold": 70}, "build_time": 24, "pop": 2, "produced_by": "hollow_bone_spire",
		"desc": "Architect of undeath. Melts enemy formations with cascading dark-matter spells.",
	},
	"hollow_hero_lich": {
		"race": "hollow", "name": "Lich King", "role": "hero", "tier": 1, "is_hero": true,
		"model": _char("hollow_hero_lich"), "height": 2.1,
		"hp": 300, "dmg": 44, "dmg_type": "arcane", "armor_class": "light", "armor": 2,
		"range": 17.0, "attack_cd": 1.3, "speed": 4.0, "vision": 30.0, "projectile": "void_bolt", "splash": 3.0, "pop": 0,
		"desc": "The undying sorcerer-king. His mere presence unravels the living; no amount of damage keeps him down for long.",
	},

	# ---------------- FROSTBORN JARLS ----------------
	"frostborn_thrall": {
		"race": "frostborn", "name": "Frostborn Thrall", "role": "worker", "tier": 1,
		"model": _char("barrosan_highlander_worker"), "height": 1.85,
		"hp": 60, "dmg": 5, "dmg_type": "blunt", "armor_class": "light", "armor": 0,
		"range": 0.0, "attack_cd": 1.2, "speed": 3.6, "vision": 18.0,
		"cost": {"food": 50}, "build_time": 12, "pop": 1,
		"desc": "Burly northern thrall who hauls resources across frozen ground and raises the Jarls' mead halls.",
	},
	"frostborn_reaver": {
		"race": "frostborn", "name": "Frostborn Reaver", "role": "melee", "tier": 1,
		"model": _char("frostborn_warrior"), "height": 1.9,
		"hp": 130, "dmg": 14, "dmg_type": "slash", "armor_class": "light", "armor": 1,
		"range": 0.0, "attack_cd": 1.1, "speed": 3.7, "vision": 20.0,
		"cost": {"food": 60, "timber": 10}, "build_time": 14, "pop": 1, "produced_by": "frostborn_war_hall",
		"desc": "Hard-swinging northern raider who hits harder than comparable soldiers and celebrates every wound.",
	},
	"frostborn_shieldmaiden": {
		"race": "frostborn", "name": "Shield Maiden", "role": "defender", "tier": 1,
		"model": _char("barrosan_spear_guard"), "height": 1.85,
		"hp": 185, "dmg": 14, "dmg_type": "pierce", "armor_class": "heavy", "armor": 4,
		"range": 0.0, "attack_cd": 1.3, "speed": 3.0, "vision": 20.0,
		"cost": {"food": 70, "timber": 20, "stone": 10}, "build_time": 18, "pop": 2, "produced_by": "frostborn_war_hall",
		"desc": "Iron-willed defender who holds the shield wall through blizzard and siege alike.",
	},
	"frostborn_hunter": {
		"race": "frostborn", "name": "Frostborn Hunter", "role": "ranged", "tier": 1,
		"model": _char("barrosan_crag_archer"), "height": 1.85,
		"hp": 90, "dmg": 16, "dmg_type": "pierce", "armor_class": "light", "armor": 0,
		"range": 16.0, "attack_cd": 1.4, "speed": 3.5, "vision": 24.0, "projectile": "arrow",
		"cost": {"food": 50, "timber": 30}, "build_time": 16, "pop": 1, "produced_by": "frostborn_war_hall",
		"desc": "Fur-clad hunter who stalks prey across tundra and battlefield with equal patience.",
	},
	"frostborn_berserker": {
		"race": "frostborn", "name": "Frostborn Berserker", "role": "melee", "tier": 2,
		"model": _char("frostborn_warrior"), "height": 2.0,
		"hp": 162, "dmg": 24, "dmg_type": "slash", "armor_class": "medium", "armor": 2,
		"range": 0.0, "attack_cd": 0.9, "speed": 4.4, "vision": 22.0,
		"cost": {"food": 90, "gold": 40}, "build_time": 18, "pop": 2, "produced_by": "frostborn_war_hall",
		"desc": "Stripped to the waist in a blizzard and still fighting. Fear means nothing; glory means everything.",
	},
	"frostborn_jotun": {
		"race": "frostborn", "name": "Frostborn Jotun", "role": "antiarmor", "tier": 3,
		"model": _char("barrosan_anvil_breaker"), "height": 2.6,
		"hp": 260, "dmg": 30, "dmg_type": "blunt", "armor_class": "heavy", "armor": 5,
		"range": 0.0, "attack_cd": 1.7, "speed": 2.8, "vision": 20.0,
		"cost": {"food": 110, "stone": 40, "gold": 40}, "build_time": 26, "pop": 3, "produced_by": "frostborn_war_hall",
		"desc": "Ancient giant-kin conscripted by the Jarls. Its boulder-fists collapse walls in two blows.",
	},
	"frostborn_hero_jarl": {
		"race": "frostborn", "name": "Frost Jarl", "role": "hero", "tier": 1, "is_hero": true,
		"model": _char("frostborn_hero_jarl"), "height": 2.1,
		"hp": 410, "dmg": 38, "dmg_type": "slash", "armor_class": "heavy", "armor": 6,
		"range": 0.0, "attack_cd": 1.1, "speed": 3.9, "vision": 28.0, "pop": 0,
		"desc": "Legendary frost-blessed warlord. His axe cleaves through champions and his war-cry sends frost through enemy veins.",
	},
	}
