import type { ResourceBag, StrongholdUpgradeId } from "../core/GameTypes";
import { formatTime } from "../core/MathUtils";
import { CAMPAIGN_CHAPTER_BY_ID, CAMPAIGN_NODE_BY_ID, REWARD_TABLE_BY_ID } from "../data/contentIndex";
import { STRONGHOLD_UPGRADE_BY_ID, type StrongholdBattleEffects } from "../data/strongholdUpgrades";
import { formatSummaryLabel } from "./PlaytestAnalyzer";
import { formatResources } from "./PlaytestTelemetry";
import type {
  PlaytestReport,
  PlaytestRewardTelemetry,
  PlaytestScriptId,
  PlaytestTelemetry
} from "./PlaytestTypes";

export function renderPlaytestMarkdownReport(report: PlaytestReport): string {
  const lines: string[] = [];
  lines.push("# Automated Playtest Telemetry");
  lines.push("");
  lines.push(`Generated by: ${report.generatedBy}`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(listLine("Too easy", report.analysis.tooEasyNodes));
  lines.push(listLine("Too hard", report.analysis.tooHardNodes));
  lines.push(
    listLine(
      "Needs human review",
      report.analysis.nodeSummaries.filter((summary) => summary.verdict === "needs_human_review").map(formatSummaryLabel)
    )
  );
  lines.push(listLine("Fair first attack timing", report.analysis.fairFirstAttackNodes));
  lines.push(listLine("Late Barracks pressure risk", report.analysis.barracksLateBeforePressure));
  lines.push(listLine("Useful rewards observed", report.analysis.usefulRewardNodes));
  lines.push(`- Ashen Outpost beatable: ${report.analysis.ashenOutpostBeatable ? "yes" : "no"}`);
  lines.push(listLine("Stronghold warnings", report.analysis.strongholdWarnings));
  lines.push("");
  lines.push("## Tuning Applied");
  lines.push("");
  lines.push("- The simulator now uses the same per-map enemy AI config as the live `EnemyAIController`, including initial attack delay, attack interval, wave size, train interval, expansion cadence, and unit plan.");
  lines.push("- First Claim pacing was softened after the config alignment exposed earlier Easy contact: first attack 180s to 210s, attack interval 62s to 68s, wave target 7 to 6, train interval 5.4s to 5.6s.");
  lines.push("- Hexfire Cult and Fortress Keeper assault caps were reduced to 5 because remaining losses happened after first-wave survival, not before Barracks completion.");
  lines.push("- Ashen Outpost now starts with one extra Militia and Ranger, one fewer enemy Watchtower, lower enemy income/training/pressure, and a smaller defense squad/radius.");
  lines.push("- The Ashen simulator model now treats capturing the Burned Shrine as a staged approach advantage, which lets Safe Beginner beat the fortress while Greedy Economy and Fast Army still fail or time out.");
  lines.push("- Live Ashen Outpost now matches that telemetry assumption: completing Burned Shrine weakens the gate Watchtower and the in-battle HUD lists all three secondary objectives.");
  lines.push("- The report now separates structural too-hard failures from strategy-spread review when Safe Beginner wins with fair Barracks and first-wave timing.");
  lines.push("- Stronghold profiles are telemetry-only simulation paths: upgrades are purchased from simulated campaign-node resources when affordable, then applied as battle-launch effects.");
  lines.push("- Stronghold telemetry now covers every Tier I path plus a Tier II Quartermaster path for no-upgrade, Tier I, and Tier II comparison.");
  lines.push("- Watch Post now models earlier first-wave warning and better Watchtower reach; Quartermaster now models a broader starter bundle and faster first player building construction.");
  lines.push("- Retinue telemetry now covers no retinue, one Veteran Militia, one Veteran Ranger, mixed retinue, mixed retinue plus Training Yard II, and mixed retinue plus Quartermaster II.");
  lines.push("- The simulator now applies the same active retinue capacity used by campaign launches: 2 units by default, +1 only after Training Yard II is purchased.");
  lines.push("- Unit Veterancy thresholds were raised to 55 / 130 / 230 XP, rank stat multipliers were softened to +4% / +8% / +12%, and the armor bonus now starts at Elite.");
  lines.push("- Enemy Hero V1 telemetry now records assigned rival commander id, defeated state, attack-join timing, and losses involving the rival.");
  lines.push("- Rival Persistence balance reporting now calls first-defeat rewards one-time, keeps +5% HP/+5% damage rematch modifiers unchanged, and surfaces reward/trophy duplicate-prevention signals.");
  lines.push("- Chapter 2 telemetry now includes `cinderfen_crossing` and `cinderfen_watch` as the current playable Cinderfen Road battles and keeps them visibly separated by chapter in node and scenario tables.");
  lines.push("- `cinderfen_overlook` is a playable event gate in live campaign flow; `cinderfen_waystation` now has one simulator profile for Shrine Attunement while other event/service launch modifiers stay covered by unit and e2e tests.");
  lines.push("- Chapter 2 balance pass trimmed Cinderfen player start resources, capture-site income, battle XP/resources, campaign-node rewards, and event-choice payouts while giving the Ashen staging camp slightly more starting bank and faster training.");
  lines.push("- The post-feature Chapter 2 balance pass trims the Cinder Shrine from +24 to +20 battle-local Aether after telemetry showed it was useful in staged routes but not the cause of fast rush wins.");
  lines.push("- Cinderfen Watchpost is the second compact Chapter 2 battle map: it uses existing Ashen units and systems, a raised-road watchtower, three capture sites, two neutral camps, and no Cinder Shrine.");
  lines.push("- The post-Waystation/Watchpost balance pass keeps Chapter 2 enemy pacing unchanged, lowers Shrine Attunement to 12 Aether, trims Cinderfen Watchpost first-clear rewards, and reduces Watchpost repeat-clear payout.");
  lines.push("- The Chapter 2 reward-economy audit keeps Cinderfen first-clear rewards unchanged, but makes Cinderfen battle item rolls and base battle XP/resources first-clear-only so repeat clears pay only the tiny repeat bonus.");
  lines.push("- Cinderfen-specific defeat tips now point players toward side income, the Cinder Shrine, Cinder Guardians, and Enemy Barracks sequencing before generic retry advice.");
  lines.push("");
  lines.push("## Chapter 2 Balance Pass Result");
  lines.push("");
  renderChapterTwoBalanceLines(report.telemetry).forEach((line) => lines.push(line));
  lines.push("");
  lines.push("## Current Enemy Hero Telemetry Read");
  lines.push("");
  lines.push("- Enemy Hero / Rival Commander V1 is represented in telemetry through `enemyHeroId`, defeated state, first attack-join timing, and losses involving the rival.");
  lines.push("- Rival / Nemesis Persistence V1 telemetry now records `rivalStateBefore`, `rivalOutcome`, `rivalStateAfter`, applied rival modifiers, losses against the rival, first-defeat reward earned, duplicate reward prevention, and trophy earned.");
  lines.push("- Old Stone Road intentionally has no enemy hero; all 36 Old Stone Road simulations currently win, so the early Easy lane should stay focused on campaign pacing and retinue readability.");
  lines.push("- Veyra of the Cinders, Gorak Emberhand, and Captain Malrec are relevant in their assigned nodes without creating structural `too_easy` or `too_hard` outcomes.");
  lines.push("- Retinue and Stronghold paths can make Ashen Outpost stronger, especially with mixed retinue, but the current data does not isolate enemy hero stats as the cause. Keep mixed-retinue Ashen sweeps under human review before changing rival numbers.");
  lines.push("");
  lines.push("## Rival Persistence Telemetry Read");
  lines.push("");
  lines.push("- Rival / Nemesis Persistence V1 is represented in telemetry without adding new maps, factions, workers, enemy construction, diplomacy, or procedural campaign.");
  lines.push("- Scripted simulations currently model each commander battle as a first campaign encounter, so `rivalStateBefore` starts at Unseen/Wary and `rivalModifiersApplied` is empty in the baseline suite.");
  lines.push("- Safe Beginner victories against Veyra, Gorak, and Malrec produce `rivalOutcome: defeated`; non-winning or timeout runs produce `rivalOutcome: triumphant`, which mirrors the live campaign rule that a player loss emboldens the rival.");
  lines.push("- The new persistence layer adds small future-encounter effects only after live campaign outcomes: escaped rivals can return with +5% HP, triumphant rivals can return with +5% damage, and first defeated rivals grant a small one-time campaign/item/trophy reward.");
  lines.push("- Rival Rewards and Trophies V1 telemetry records whether a first-defeat reward was earned, whether a duplicate first-defeat reward was prevented, and which trophy id was earned.");
  lines.push(`- Current ${report.telemetry.length}-run structural read reports no structural \`too_easy\`, no structural \`too_hard\`, no Stronghold warnings, and Ashen Outpost remains beatable.`);
  lines.push("");
  lines.push("## Rival Persistence Balance Pass Result");
  lines.push("");
  renderRivalPersistenceBalanceLines(report.telemetry).forEach((line) => lines.push(line));
  lines.push("");
  lines.push("## Enemy Hero Balance Pass Result");
  lines.push("");
  lines.push("- The 2026-05-02 telemetry-based enemy hero pass applied no numeric gameplay changes because rival commanders are relevant without creating structural `too_easy` or `too_hard` nodes.");
  lines.push("- Old Stone Road remains unassigned to an enemy hero: all 36 Old Stone Road simulations still win, and adding a rival there would risk making the early Easy lane noisy before the player has seen the mid-campaign commander pattern.");
  lines.push("- Veyra of the Cinders on Aether Well Ruins appears in 36 runs, is defeated in 24, joins attacks around 10:31-10:32 in 17 slow or retinue-assisted runs, and is involved in 12 player losses. Safe Beginner still wins, so her HP, damage, Hexfire Bolt range/cooldown, XP reward, and map assignment remain unchanged.");
  lines.push("- Gorak Emberhand on Bandit Hillfort appears in 36 runs, is defeated in 13, joins attacks around 11:40-11:41 in 12 Greedy Economy runs, and is involved in 12 player losses. His pressure is meaningful but not an early rush, so his HP, damage, Ember Strike/Rally Raiders tuning, XP reward, and Bandit Hillfort assignment remain unchanged.");
  lines.push("- Captain Malrec on Ashen Outpost appears in 36 runs, is defeated in all 36, joins attacks around 10:41-10:42 in 14 slow runs, and is involved in 14 player losses. Ashen remains a milestone because no-retinue and many Stronghold paths still produce timeouts, while mixed retinue sweeps remain human-review rather than structural `too_easy`.");
  lines.push("- Retinue and Stronghold paths make some Ashen outcomes stronger, but the commander data does not isolate a rival-specific overpowered or unfair pattern; keep deathless mixed-retinue Ashen sweeps under human review before buffing Malrec or nerfing retinue-adjacent interactions.");
  lines.push("");
  lines.push("## Retinue Balance Pass Result");
  lines.push("");
  lines.push("- The 2026-05-02 conservative retinue balance pass applied no numeric gameplay changes because telemetry shows no structural `too_easy` or `too_hard` nodes.");
  lines.push("- Retained capacity at 2 active units by default and +1 only from Training Yard II; mixed retinue profiles are strong enough for human review, but no-retinue Ashen Outpost remains beatable.");
  lines.push("- Retained Seasoned+ eligibility, 55 / 130 / 230 XP thresholds, +4% / +8% / +12% rank bonuses, Elite-only +1 armor, and permanent retinue removal on death.");
  lines.push("- Retained Quartermaster II interaction unchanged; the mixed-retinue Quartermaster profile is strong but still classified as human-review rather than structural `too_easy`.");
  lines.push("- Next balance action is human-paced Ashen Outpost review with no retinue, one Veteran, mixed retinue, Training Yard II, and Quartermaster II before changing numbers.");
  lines.push("");
  lines.push("## Stronghold Profile Verdicts");
  lines.push("");
  lines.push("| Profile | Target upgrades | Purchased upgrades | First purchase | Record | Improved runs | Warnings |");
  lines.push("| --- | --- | --- | --- | ---: | ---: | --- |");
  report.analysis.strongholdProfileSummaries.forEach((summary) => {
    lines.push(
      `| ${summary.profileName} | ${formatUpgradeList(summary.targetUpgradeIds)} | ${formatUpgradeList(
        summary.purchasedUpgradeIds
      )} | ${summary.firstPurchaseNodeId ?? "-"} | ${summary.victories}-${summary.defeats}-${summary.timeouts} | ${
        summary.improvedRuns
      } | ${summary.warnings.length > 0 ? summary.warnings.join("; ") : "-"} |`
    );
  });
  lines.push("");
  lines.push("## Node Verdicts");
  lines.push("");
  lines.push("| Profile | Chapter | Node | Difficulty | AI | Wins | Losses | Barracks before pressure | First wave survived | Verdict |");
  lines.push("| --- | --- | --- | --- | --- | ---: | ---: | ---: | ---: | --- |");
  report.analysis.nodeSummaries.forEach((summary) => {
    const runCount = report.telemetry.filter(
      (run) => run.strongholdProfileId === summary.strongholdProfileId && run.nodeId === summary.nodeId
    ).length;
    lines.push(
      `| ${summary.strongholdProfileName} | ${formatChapterLabel(summary.nodeId)} | ${summary.nodeName} | ${summary.difficulty} | ${summary.aiPersonality} | ${
        summary.victories
      } | ${summary.defeats + summary.timeouts} | ${summary.barracksBeforePressureRuns}/${runCount} | ${
        summary.firstWaveSurvivedRuns
      }/${runCount} | ${summary.verdict} |`
    );
  });
  lines.push("");
  lines.push("## Scenario Runs");
  lines.push("");
  lines.push(
    "| Profile | Chapter | Node | Script | Upgrades | Retinue | Enemy hero | Launch effects | Starting units | Starting resources | Result | Duration | First wave | Floated resources | Objectives | Rewards |"
  );
  lines.push("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ---: | --- | --- | --- | --- |");
  report.telemetry.forEach((run) => {
    lines.push(
      `| ${run.strongholdProfileName} | ${formatChapterLabel(run.nodeId)} | ${run.nodeName} | ${formatScriptName(run.playerScript)} | ${formatUpgradeList(
        run.strongholdUpgradeIds
      )} | ${run.retinueUnits.length > 0 ? run.retinueUnits.join(", ") : "-"} | ${formatEnemyHeroTelemetry(run)} | ${formatStrongholdEffectTelemetry(run.strongholdEffects)} | ${formatUnitCounts(run.startingUnits)} | ${formatResources(
        run.startingResources
      )} | ${run.battleResult} | ${formatTime(run.battleDurationSeconds)} | ${
        run.firstWaveSurvived ? "yes" : "no"
      } | ${formatResources(run.resourcesFloated)} | ${
        run.objectiveCompletion.length > 0 ? run.objectiveCompletion.join(", ") : "-"
      } | ${formatReward(run.rewardResult)} |`
    );
  });
  lines.push("");
  lines.push("## Balance Read");
  lines.push("");
  report.analysis.nodeSummaries.forEach((summary) => {
    lines.push(`### ${summary.strongholdProfileName} - ${summary.nodeName}`);
    lines.push("");
    summary.notes.forEach((note) => lines.push(`- ${note}`));
    lines.push("");
  });
  lines.push("## Suggested Tuning Changes");
  lines.push("");
  report.analysis.suggestedTuningChanges.forEach((suggestion) => lines.push(`- ${suggestion}`));
  lines.push("");
  lines.push("## Human Judgment Still Needed");
  lines.push("");
  lines.push("- The simulator is deterministic and structural; it cannot judge moment-to-moment feel, readability, audio, or player stress.");
  lines.push("- Manual or visual browser playtests are still needed before finalizing deeper map, objective, or fortress-structure changes.");
  lines.push("- Treat remaining suggestions as investigation leads, not proof that more aggressive tuning is automatically correct.");
  lines.push("");
  return `${lines.join("\n")}\n`;
}


function formatReward(reward: PlaytestRewardTelemetry | null): string {
  if (!reward) {
    return "-";
  }
  const itemText = [...reward.battleItemIds, ...reward.campaignItemIds].join(", ");
  const resourceTotal =
    Object.values(reward.battleResources).reduce((total, amount) => total + (amount ?? 0), 0) +
    Object.values(reward.campaignResources).reduce((total, amount) => total + (amount ?? 0), 0);
  return `${reward.battleXp + reward.campaignXp} XP, ${resourceTotal} resources${itemText ? `, ${itemText}` : ""}`;
}


function renderRivalPersistenceBalanceLines(runs: PlaytestTelemetry[]): string[] {
  const rivalRuns = runs.filter((run) => run.enemyHeroId);
  const modifierRuns = rivalRuns.filter((run) => run.rivalModifiersApplied.length > 0);
  const winningDefeats = rivalRuns.filter((run) => run.battleResult === "victory" && run.enemyHeroDefeated);
  const escaped = rivalRuns.filter((run) => run.battleResult === "victory" && !run.enemyHeroDefeated);
  const nonWinningRivalPressure = rivalRuns.filter((run) => run.battleResult !== "victory" && run.lossesInvolvingEnemyHero > 0);
  const firstRewards = rivalRuns.filter((run) => run.rivalFirstDefeatRewardEarned);
  const duplicatesPrevented = rivalRuns.filter((run) => run.rivalDuplicateRewardPrevented);
  const trophies = rivalRuns.filter((run) => run.rivalTrophyEarned);
  const lines: string[] = [];
  lines.push(
    `- Rival commander coverage: ${rivalRuns.length} commander-node runs. ${winningDefeats.length} winning commander defeats earned the one-time reward/trophy path; ${escaped.length} escaped-rival victories were observed; ${nonWinningRivalPressure.length} non-winning runs involved rival pressure.`
  );
  lines.push(
    `- Reward duplication read: ${firstRewards.length} first-defeat rewards and ${trophies.length} trophies were earned in first-encounter simulations; ${duplicatesPrevented.length} duplicate-prevention events were observed in the baseline suite because repeat defeats are covered by save/unit/e2e tests rather than the first-encounter simulator path.`
  );
  lines.push(
    `- Modifier read: ${modifierRuns.length} runs applied persisted rival modifiers. The current structural suite keeps commander battles as first encounters, so +5% HP and +5% damage remain the conservative ceiling until a future rematch-profile pass needs broader coverage.`
  );
  lines.push("- Tuning result: no rival HP, damage, modifier strength, escape rule, XP reward, resource reward, or trophy effect changed; only player-facing/reporting copy was tightened around one-time rewards and small rematch modifiers.");
  summarizeRivalRuns(rivalRuns).forEach((summary) => {
    lines.push(
      `- ${summary.enemyHeroId}: ${summary.runs} runs, ${formatCount(summary.wins, "win")} / ${formatCount(
        summary.defeats,
        "defeat"
      )} / ${formatCount(summary.timeouts, "timeout")}, commander defeated ${summary.commanderDefeated} times, joined attacks ${summary.joinedAttack} times, ${summary.lossRuns} non-winning pressure runs, ${summary.firstRewards} one-time rewards.`
    );
  });
  return lines;
}

function summarizeRivalRuns(runs: PlaytestTelemetry[]): Array<{
  enemyHeroId: string;
  runs: number;
  wins: number;
  defeats: number;
  timeouts: number;
  commanderDefeated: number;
  joinedAttack: number;
  lossRuns: number;
  firstRewards: number;
}> {
  return uniqueValues(runs.map((run) => run.enemyHeroId).filter((enemyHeroId): enemyHeroId is string => Boolean(enemyHeroId)))
    .sort((left, right) => left.localeCompare(right))
    .map((enemyHeroId) => {
      const heroRuns = runs.filter((run) => run.enemyHeroId === enemyHeroId);
      return {
        enemyHeroId,
        runs: heroRuns.length,
        wins: heroRuns.filter((run) => run.battleResult === "victory").length,
        defeats: heroRuns.filter((run) => run.battleResult === "defeat").length,
        timeouts: heroRuns.filter((run) => run.battleResult === "timeout").length,
        commanderDefeated: heroRuns.filter((run) => run.enemyHeroDefeated).length,
        joinedAttack: heroRuns.filter((run) => run.timeEnemyHeroJoinedAttack !== null).length,
        lossRuns: heroRuns.filter((run) => run.battleResult !== "victory" && run.lossesInvolvingEnemyHero > 0).length,
        firstRewards: heroRuns.filter((run) => run.rivalFirstDefeatRewardEarned).length
      };
    });
}


function formatStrongholdEffectTelemetry(effects: StrongholdBattleEffects): string {
  const parts: string[] = [];
  if (effects.extraPlayerUnitIds.length > 0) {
    parts.push(`units ${effects.extraPlayerUnitIds.join(", ")}`);
  }
  if (Object.values(effects.startingResources).some((amount) => (amount ?? 0) > 0)) {
    parts.push(`resources ${formatResources(effects.startingResources)}`);
  }
  if (effects.heroMaxHpMultiplier > 1 || effects.heroMaxManaMultiplier > 1) {
    parts.push(
      `hero ${Math.round((effects.heroMaxHpMultiplier - 1) * 100)}% HP/${Math.round(
        (effects.heroMaxManaMultiplier - 1) * 100
      )}% Mana`
    );
  }
  if (effects.buildingVisionBonus > 0) {
    parts.push(`vision +${effects.buildingVisionBonus}`);
  }
  if (effects.enemyWarningLeadSeconds > 0) {
    parts.push(`warning +${effects.enemyWarningLeadSeconds}s`);
  }
  if (effects.watchtowerRangeMultiplier > 1) {
    parts.push(`tower +${Math.round((effects.watchtowerRangeMultiplier - 1) * 100)}%`);
  }
  if (effects.firstBuildingConstructionTimeMultiplier < 1) {
    parts.push(`first build ${Math.round((1 - effects.firstBuildingConstructionTimeMultiplier) * 100)}% faster`);
  }
  Object.entries(effects.unitTrainingTimeMultipliers).forEach(([unitId, multiplier]) => {
    if (multiplier !== undefined && multiplier < 1) {
      parts.push(`${titleCase(unitId)} train ${Math.round((1 - multiplier) * 100)}% faster`);
    }
  });
  Object.entries(effects.firstCaptureBonusResourceAdditions).forEach(([siteId, resources]) => {
    if (Object.values(resources).some((amount) => (amount ?? 0) > 0)) {
      parts.push(`${titleCase(siteId)} first capture +${formatResources(resources)}`);
    }
  });
  return parts.length > 0 ? parts.join("; ") : "-";
}


function formatUnitCounts(units: Record<string, number>): string {
  const active = Object.entries(units).filter(([, count]) => count > 0);
  return active.length > 0
    ? active
        .map(([unitId, count]) => `${count} ${titleCase(unitId)}`)
        .join(", ")
    : "none";
}

function formatUpgradeList(upgradeIds: StrongholdUpgradeId[]): string {
  return upgradeIds.length > 0 ? upgradeIds.map((upgradeId) => STRONGHOLD_UPGRADE_BY_ID[upgradeId].name).join(", ") : "none";
}


function formatEnemyHeroTelemetry(run: PlaytestTelemetry): string {
  if (!run.enemyHeroId) {
    return "-";
  }
  const joined = run.timeEnemyHeroJoinedAttack === null ? "held" : `joined ${formatTime(run.timeEnemyHeroJoinedAttack)}`;
  const defeated = run.enemyHeroDefeated ? "defeated" : "alive";
  const losses = run.lossesInvolvingEnemyHero > 0 ? `, losses ${run.lossesInvolvingEnemyHero}` : "";
  const rival =
    run.rivalOutcome !== "none"
      ? `, rival ${run.rivalOutcome}${run.rivalModifiersApplied.length > 0 ? ` (${run.rivalModifiersApplied.join(", ")})` : ""}`
      : "";
  const reward = run.rivalFirstDefeatRewardEarned ? ", one-time reward" : run.rivalDuplicateRewardPrevented ? ", duplicate prevented" : "";
  const trophy = run.rivalTrophyEarned ? `, trophy ${run.rivalTrophyEarned}` : "";
  return `${run.enemyHeroId} ${defeated}, ${joined}${losses}${rival}${reward}${trophy}`;
}

function listLine(label: string, values: string[]): string {
  const unique = uniqueValues(values);
  return `- ${label}: ${unique.length > 0 ? unique.join(", ") : "none"}`;
}

function renderChapterTwoBalanceLines(telemetry: PlaytestTelemetry[]): string[] {
  const crossingRuns = telemetry.filter((run) => run.nodeId === "cinderfen_crossing");
  const watchRuns = telemetry.filter((run) => run.nodeId === "cinderfen_watch");
  const cinderfenRuns = [...crossingRuns, ...watchRuns];
  const crossingScriptLines = renderCinderfenScriptRead("Cinderfen Crossing", crossingRuns);
  const watchScriptLines = renderCinderfenScriptRead("Cinderfen Watchpost", watchRuns);
  const noStrongholdSafe = crossingRuns.find(
    (run) => run.strongholdProfileId === "no_stronghold" && run.playerScript === "safe_beginner"
  );
  const watchNoStrongholdSafe = watchRuns.find(
    (run) => run.strongholdProfileId === "no_stronghold" && run.playerScript === "safe_beginner"
  );
  const retinueTrainingYard = cinderfenRuns.filter((run) => run.strongholdProfileId === "retinue_training_yard_path");
  const rivalModifierRuns = cinderfenRuns.filter((run) => run.rivalModifiersApplied.length > 0).length;
  const shrineSurgeRuns = crossingRuns.filter((run) => run.commandLog.some((entry) => entry.includes("Cinder Shrine Surge"))).length;
  const attunedShrineRuns = crossingRuns.filter(
    (run) =>
      run.strongholdProfileId === "waystation_shrine_attunement" &&
      run.commandLog.some((entry) => entry.includes("Cinder Shrine Surge: 25 Aether"))
  ).length;
  const watchShrineRuns = watchRuns.filter((run) => run.commandLog.some((entry) => entry.includes("Cinder Shrine Surge"))).length;
  const reward = noStrongholdSafe?.rewardResult;
  const watchReward = watchNoStrongholdSafe?.rewardResult;
  return [
    "- Cinderfen Crossing and Cinderfen Watchpost are reported separately in the Chapter 2 slice so the second battle can be tuned without masking the first battle's stability.",
    ...crossingScriptLines,
    ...watchScriptLines,
    `- Retinue + Training Yard II remains the strongest Chapter 2 profile at ${formatRunRecord(retinueTrainingYard)} and stays a human-review watchpoint rather than an automated ` +
      "`too_easy` flag.",
    `- Rival state impact: ${rivalModifierRuns} Cinderfen runs applied rival modifiers; neither current Chapter 2 battle has a named enemy hero.`,
    `- Cinder Shrine impact: ${shrineSurgeRuns}/${crossingRuns.length} Crossing runs captured the shrine and received the one-time battle-local surge; ${attunedShrineRuns} attuned Waystation runs raised that capture to +25 Aether. Watchpost has no shrine and recorded ${watchShrineRuns}/${watchRuns.length} shrine surges.`,
    reward
      ? `- Cinderfen Crossing normal first-clear reward read: ${reward.battleXp + reward.campaignXp} XP, ${sumResources(
          reward.battleResources
        ) + sumResources(reward.campaignResources)} campaign/battle resources, ${[
          ...reward.battleItemIds,
          ...reward.campaignItemIds
        ].join(", ")}.`
      : "- Cinderfen Crossing normal first-clear reward read: no winning baseline run found.",
    watchReward
      ? `- Cinderfen Watchpost normal first-clear reward read: ${
          watchReward.battleXp + watchReward.campaignXp
        } XP, ${sumResources(watchReward.battleResources) + sumResources(watchReward.campaignResources)} campaign/battle resources, ${[
          ...watchReward.battleItemIds,
          ...watchReward.campaignItemIds
        ].join(", ")}.`
      : "- Cinderfen Watchpost normal first-clear reward read: no winning baseline run found.",
    `- Cinderfen repeat-clear value after the reward-economy audit: Crossing ${formatRepeatRewardRead(
      "cinderfen_causeway_rewards"
    )}; Watchpost ${formatRepeatRewardRead(
      "cinderfen_watchpost_rewards"
    )}. The Cinderfen weighted battle item pools are first-clear-only, reducing Fast Army farm value without changing first-clear usefulness.`,
    "- Chapter 1 telemetry remains unchanged by this pass because tuning touches only Cinderfen battle data, Cinderfen reward/service values, battle-local capture-site rules, simulator modeling, and Cinderfen-specific result copy."
  ];
}

function renderCinderfenScriptRead(label: string, runs: PlaytestTelemetry[]): string[] {
  const scriptLines = [`- ${label} script read:`];
  ["safe_beginner", "greedy_economy", "fast_army"].forEach((scriptId) => {
    const scriptRuns = runs.filter((run) => run.playerScript === scriptId);
    scriptLines.push(
      `  - ${formatScriptName(scriptId as PlaytestScriptId)}: ${formatRunRecord(scriptRuns)}, average contact ${formatAverageTime(
        scriptRuns.map((run) => run.timeFirstEnemyContact)
      )}, first wave survived ${scriptRuns.filter((run) => run.firstWaveSurvived).length}/${scriptRuns.length}.`
    );
  });
  return scriptLines;
}

function formatRunRecord(runs: PlaytestTelemetry[]): string {
  const victories = runs.filter((run) => run.battleResult === "victory").length;
  const defeats = runs.filter((run) => run.battleResult === "defeat").length;
  const timeouts = runs.filter((run) => run.battleResult === "timeout").length;
  return `${formatCount(victories, "win")} / ${formatCount(defeats, "defeat")} / ${formatCount(timeouts, "timeout")}`;
}

function formatCount(value: number, label: string): string {
  return `${value} ${label}${value === 1 ? "" : "s"}`;
}

function formatAverageTime(values: Array<number | null>): string {
  const numeric = values.filter((value): value is number => typeof value === "number");
  if (numeric.length === 0) {
    return "-";
  }
  return formatTime(numeric.reduce((total, value) => total + value, 0) / numeric.length);
}

function sumResources(resources: Partial<ResourceBag>): number {
  return Object.values(resources).reduce((total, amount) => total + (amount ?? 0), 0);
}

function formatRepeatRewardRead(tableId: string): string {
  const reward = REWARD_TABLE_BY_ID[tableId]?.repeatClearReward;
  return `${reward?.xp ?? 0} XP / ${sumResources(reward?.resources ?? {})} resources / no battle item roll`;
}

function formatChapterLabel(nodeId: string): string {
  const chapterId = CAMPAIGN_NODE_BY_ID[nodeId]?.chapterId;
  return chapterId ? CAMPAIGN_CHAPTER_BY_ID[chapterId]?.title ?? chapterId : "Unknown chapter";
}

function formatScriptName(scriptId: PlaytestScriptId): string {
  return scriptId
    .split("_")
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join(" ");
}

function titleCase(value: string): string {
  return value
    .split("_")
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join(" ");
}


function uniqueValues<T>(values: T[]): T[] {
  return [...new Set(values)];
}
