import { formatTime } from "../core/MathUtils";
import { SCENARIO_LAB_PROFILES } from "./ScenarioLabProfiles";
import type {
  ScenarioLabProfileSummary,
  ScenarioLabRecord,
  ScenarioLabReport,
  ScenarioLabWatchpointClassification
} from "./ScenarioLabTypes";

export function renderScenarioLabMarkdownReport(report: ScenarioLabReport): string {
  const lines: string[] = [];
  lines.push("# v0.13 Automated Playtest Scenario Lab");
  lines.push("");
  lines.push("Evidence type: automated deterministic simulator evidence only. No human tester feedback is included or implied.");
  lines.push("");
  lines.push(`Generated by: ${report.generatedBy}`);
  lines.push(`Source telemetry: schema v${report.sourceReportSchemaVersion}, ${report.sourceRunCount} source runs.`);
  lines.push("");
  lines.push("## Executive Summary");
  lines.push("");
  lines.push(`- Strongest profile: ${profileName(report, report.strongestProfileId)}.`);
  lines.push(`- Weakest profile: ${profileName(report, report.weakestProfileId)}.`);
  lines.push(`- Fastest profile: ${profileName(report, report.fastestProfileId)}.`);
  lines.push(`- Most failure-prone profile: ${profileName(report, report.mostFailureProneProfileId)}.`);
  lines.push("- Recommended action: no runtime tuning from v0.13 automated evidence alone; keep human testing as the next evidence gate.");
  lines.push("");
  lines.push("## Profile Comparison");
  lines.push("");
  lines.push("| Profile | Runs | Record | Win rate | Avg clear | Avg losses | Avg army | Avg resources | Pressure warnings | Verdict | Confidence |");
  lines.push("| --- | ---: | --- | ---: | ---: | ---: | ---: | ---: | ---: | --- | --- |");
  report.profiles.forEach((summary) => {
    lines.push(
      `| ${summary.profileName} | ${summary.runCount} | ${formatRecord(summary.record)} | ${formatPercent(
        summary.winRate
      )} | ${formatTime(summary.averageClearTimeSeconds)} | ${formatNumber(summary.averageUnitLosses)} | ${formatNumber(
        summary.averageFinalArmySize
      )} | ${Math.round(summary.averageResourceSurplus)} | ${summary.pressureWarningCount} | ${summary.routeVerdict} | ${
        summary.confidence
      } |`
    );
  });
  lines.push("");
  lines.push("## Node Risk Summary");
  lines.push("");
  lines.push("| Node | Record | Avg losses | Timeouts | Defeats | Pressure warnings | Verdict |");
  lines.push("| --- | --- | ---: | ---: | ---: | ---: | --- |");
  report.nodeRiskSummaries.forEach((summary) => {
    lines.push(
      `| ${summary.nodeName} | ${formatRecord(summary.record)} | ${formatNumber(summary.averageUnitLosses)} | ${
        summary.timeoutCount
      } | ${summary.defeatCount} | ${summary.pressureWarningCount} | ${summary.verdict} |`
    );
  });
  lines.push("");
  lines.push("## Watchpoint Classifier");
  lines.push("");
  lines.push("| Watchpoint | Action | Confidence | Human testing | Automated verdict |");
  lines.push("| --- | --- | --- | --- | --- |");
  report.watchpoints.forEach((watchpoint) => {
    lines.push(
      `| ${watchpoint.watchpointName} | ${watchpoint.action} | ${watchpoint.confidence} | ${
        watchpoint.humanTestingNeeded ? "yes" : "no"
      } | ${watchpoint.automatedVerdict} |`
    );
  });
  lines.push("");
  lines.push("## Watchpoint Evidence");
  lines.push("");
  report.watchpoints.forEach((watchpoint) => {
    lines.push(`### ${watchpoint.watchpointName}`);
    lines.push("");
    watchpoint.evidence.forEach((evidence) => lines.push(`- ${evidence}`));
    lines.push("");
  });
  lines.push("## Profile Definitions");
  lines.push("");
  SCENARIO_LAB_PROFILES.forEach((profile) => {
    const summary = report.profiles.find((entry) => entry.profileId === profile.id);
    lines.push(`### ${profile.name}`);
    lines.push("");
    lines.push(`- Behavior model: ${profile.playerBehaviorModel}`);
    lines.push(`- Scripts: ${profile.scriptIds.join(", ")}`);
    lines.push(`- Stronghold/profile rows: ${profile.preferredStrongholdProfileIds.join(", ")}`);
    lines.push(`- Nodes: ${profile.nodeIds.join(", ")}`);
    lines.push(`- Risk appetite: ${profile.riskAppetite}; objective priority: ${profile.objectivePriority}; retreat bias: ${profile.retreatSurvivalBias}.`);
    lines.push(`- Watchpoints: ${profile.watchpointRelevance.join(", ")}`);
    lines.push(`- Automated result: ${summary?.routeVerdict ?? "not run"}.`);
    profile.automationNotes.forEach((note) => lines.push(`- ${note}`));
    lines.push("");
  });
  lines.push("## Metrics Availability");
  lines.push("");
  lines.push("| Metric | Status | Note |");
  lines.push("| --- | --- | --- |");
  report.metricsAvailability.forEach((metric) => {
    lines.push(`| ${metric.metric} | ${metric.status} | ${metric.note} |`);
  });
  lines.push("");
  lines.push("## Limits");
  lines.push("");
  lines.push("- The lab cannot measure human attention, stress, fun, or visual readability.");
  lines.push("- Hero final HP/death state and base damage are unavailable in current telemetry.");
  lines.push("- Profile rows can overlap by design; the lab compares evidence views, not independent player populations.");
  lines.push("- Treat automated results as prioritization evidence for human testing, not as proof that tuning is required.");
  lines.push("");
  return formatMarkdownDocument(lines);
}

export function renderWatchpointSummaryMarkdown(report: ScenarioLabReport): string {
  const lines: string[] = [];
  lines.push("# v0.13 Playtest Watchpoint Summary");
  lines.push("");
  lines.push("Evidence type: automated deterministic simulator evidence only. No human tester feedback is included or implied.");
  lines.push("");
  lines.push("| Watchpoint | Action | Confidence | Evidence |");
  lines.push("| --- | --- | --- | --- |");
  report.watchpoints.forEach((watchpoint) => {
    lines.push(
      `| ${watchpoint.watchpointName} | ${watchpoint.action} | ${watchpoint.confidence} | ${formatEvidenceInline(
        watchpoint.evidence
      )} |`
    );
  });
  lines.push("");
  lines.push("## Next Human Testing Priorities");
  lines.push("");
  report.watchpoints
    .filter((watchpoint) => watchpoint.humanTestingNeeded)
    .forEach((watchpoint) => lines.push(`- ${watchpoint.watchpointName}: ${watchpoint.automatedVerdict}`));
  lines.push("");
  lines.push("## No-Tuning Guardrail");
  lines.push("");
  lines.push("- No runtime tuning should be made from this summary alone.");
  lines.push("- Tiny tuning requires repeated strong evidence and preferably real human playtest notes.");
  lines.push("- Copy/readability work should be considered before numbers when the issue may be understanding or noticeability.");
  lines.push("");
  return formatMarkdownDocument(lines);
}

export function renderScenarioProfileCatalogMarkdown(): string {
  const lines: string[] = [];
  lines.push("# v0.13 Automated Scenario Profile Catalog");
  lines.push("");
  lines.push("These are deterministic automated evidence profiles, not human tester reports.");
  lines.push("");
  SCENARIO_LAB_PROFILES.forEach((profile) => {
    lines.push(`## ${profile.name}`);
    lines.push("");
    lines.push(`- Behavior model: ${profile.playerBehaviorModel}`);
    lines.push(`- Route assumptions: ${formatSentenceList(profile.routeAssumptions)}.`);
    lines.push(`- Scripts: ${profile.scriptIds.join(", ")}`);
    lines.push(`- Stronghold/profile rows: ${profile.preferredStrongholdProfileIds.join(", ")}`);
    lines.push(`- Nodes: ${profile.nodeIds.join(", ")}`);
    lines.push(`- Expected strengths: ${formatSentenceList(profile.expectedStrengths)}.`);
    lines.push(`- Expected weaknesses: ${formatSentenceList(profile.expectedWeaknesses)}.`);
    lines.push(`- Watchpoint relevance: ${profile.watchpointRelevance.join(", ")}`);
    lines.push("");
  });
  return formatMarkdownDocument(lines);
}

function profileName(report: ScenarioLabReport, profileId: string | null): string {
  if (!profileId) {
    return "none";
  }
  return report.profiles.find((profile) => profile.profileId === profileId)?.profileName ?? profileId;
}

function formatRecord(record: ScenarioLabRecord): string {
  return `${record.wins}-${record.defeats}-${record.timeouts}`;
}

function formatPercent(value: number): string {
  return `${Math.round(value * 100)}%`;
}

function formatNumber(value: number): string {
  return value.toFixed(1);
}

function formatSentenceList(values: string[]): string {
  return values.map((value) => value.replace(/[.]+$/u, "")).join("; ");
}

function formatEvidenceInline(values: string[]): string {
  return `${values.map((value) => value.replace(/[.]+$/u, "")).join("; ")}.`;
}

function formatMarkdownDocument(lines: string[]): string {
  while (lines[lines.length - 1] === "") {
    lines.pop();
  }
  return `${lines.join("\n")}\n`;
}

export function watchpointSummaryRequiresHumanTesting(watchpoint: ScenarioLabWatchpointClassification): boolean {
  return watchpoint.humanTestingNeeded;
}
