export type AssetCategory =
  | "portrait"
  | "faction_emblem"
  | "ability_icon"
  | "resource_icon"
  | "ui"
  | "ui_kit"
  | "splash"
  | "unit_sprite"
  | "building_sprite"
  | "unit_concept"
  | "building_concept";

export type AssetStatus = "needed" | "manual-ready" | "final-ready" | "optional";

export interface ManualAssetEntry {
  id: string;
  category: AssetCategory;
  displayName: string;
  filename: string;
  targetFolder: "portraits" | "icons" | "units" | "buildings" | "terrain" | "ui" | "splash";
  preferredWidth: number;
  preferredHeight: number;
  usage: string;
  styleTags: string[];
  smallSizeReadable: boolean;
  transparencyPreferred: boolean;
  flatBackgroundAllowed: boolean;
  factionId?: string;
  unitId?: string;
  buildingId?: string;
  abilityId?: string;
  priority: number;
  status: AssetStatus;
  required: boolean;
  notes: string;
  subject: string;
  composition: string;
}

export const ASSET_REGISTRY: ManualAssetEntry[] = [
  {
    id: "warlord_hero_portrait",
    category: "portrait",
    displayName: "Warlord Hero Portrait",
    filename: "warlord_hero_portrait.png",
    targetFolder: "portraits",
    preferredWidth: 768,
    preferredHeight: 768,
    usage: "Hero creation card, HUD portrait, future character sheet.",
    styleTags: ["portrait", "hero", "free_marches", "martial", "leader"],
    smallSizeReadable: true,
    transparencyPreferred: false,
    flatBackgroundAllowed: true,
    factionId: "free_marches",
    priority: 1,
    status: "needed",
    required: true,
    notes: "The first hero class. Needs to read as a durable battlefield commander.",
    subject: "a Free Marches warlord hero in practical worn silver plate over a dark gambeson, muted gold command sash, deep blue weathered cloak, square jaw, tired eyes, and a veteran's calm battlefield authority",
    composition: "square chest-up bust portrait, three-quarter view facing slightly left, stern but noble expression, one gloved hand resting near a banner pole, shield-and-tower motifs worked into the cloak clasp, soft frontier keep silhouette behind the shoulders"
  },
  {
    id: "arcanist_hero_portrait",
    category: "portrait",
    displayName: "Arcanist Hero Portrait",
    filename: "arcanist_hero_portrait.png",
    targetFolder: "portraits",
    preferredWidth: 768,
    preferredHeight: 768,
    usage: "Hero creation card, HUD portrait, future character sheet.",
    styleTags: ["portrait", "hero", "arcane", "spellcaster"],
    smallSizeReadable: true,
    transparencyPreferred: false,
    flatBackgroundAllowed: true,
    priority: 2,
    status: "needed",
    required: true,
    notes: "A distinct magic specialist, not a generic wizard.",
    subject: "an original battlefield arcanist hero wearing layered charcoal travel robes, bronze clasps, ember-lit aether glass focus stones, ink-stained fingers, and a controlled dangerous gaze",
    composition: "square chest-up bust portrait, face turned slightly toward the viewer, one glowing hand near the sternum forming a compact spell, warm orange aether light balanced against deep blue shadow, simple arcane workbench shapes blurred in the background"
  },
  {
    id: "shepherd_hero_portrait",
    category: "portrait",
    displayName: "Shepherd Hero Portrait",
    filename: "shepherd_hero_portrait.png",
    targetFolder: "portraits",
    preferredWidth: 768,
    preferredHeight: 768,
    usage: "Hero creation card, HUD portrait, future character sheet.",
    styleTags: ["portrait", "hero", "support", "faith", "healer"],
    smallSizeReadable: true,
    transparencyPreferred: false,
    flatBackgroundAllowed: true,
    priority: 3,
    status: "needed",
    required: true,
    notes: "Should feel protective and commanding, not passive.",
    subject: "a Shepherd hero, a calm holy field commander in travel-worn cream and moss-green vestments over light armor, simple ashwood staff, chapel charms, healer satchel, and quiet protective resolve",
    composition: "square chest-up bust portrait, gentle but unshaken expression, staff angled behind the shoulder, soft green-white chapel light around the hands, practical healer-warrior details, clean misty field background"
  },
  {
    id: "main_menu_background",
    category: "ui",
    displayName: "Main Menu Background",
    filename: "main_menu_background.png",
    targetFolder: "ui",
    preferredWidth: 1920,
    preferredHeight: 1080,
    usage: "Main menu background behind title and menu buttons.",
    styleTags: ["ui", "background", "menu", "world_tone"],
    smallSizeReadable: false,
    transparencyPreferred: false,
    flatBackgroundAllowed: false,
    priority: 4,
    status: "needed",
    required: true,
    notes: "Must leave calm readable space for menu panel overlays.",
    subject: "a dark heroic fantasy borderland at twilight: distant stone keeps on a ridge, small frontier banners, ruined shrine stones, winding road, low mist, and faint blue aether glow breaking through storm clouds",
    composition: "1920x1080 wide environment background, darker uncluttered center-left safe area for title and menu buttons, stronger atmosphere and silhouettes at the edges, no close foreground characters, no text"
  },
  {
    id: "rally_banner_icon",
    category: "ability_icon",
    displayName: "Rally Banner Icon",
    filename: "rally_banner_icon.png",
    targetFolder: "icons",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "Warlord ability button.",
    styleTags: ["icon", "ability", "warlord", "banner", "leadership"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    abilityId: "rally_banner",
    factionId: "free_marches",
    priority: 5,
    status: "needed",
    required: true,
    notes: "Needs a strong banner silhouette.",
    subject: "a deep blue Free Marches war banner with muted gold trim, a worn silver spearhead, two short cloth tails, and a simple command aura",
    composition: "square centered icon, banner fills 70 percent of canvas, strong vertical silhouette, simple golden pulse ring behind it, 12 percent empty padding, readable as a banner at 64x64"
  },
  {
    id: "firebolt_icon",
    category: "ability_icon",
    displayName: "Firebolt Icon",
    filename: "firebolt_icon.png",
    targetFolder: "icons",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "Arcanist ability button.",
    styleTags: ["icon", "ability", "fire", "arcane", "projectile"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    abilityId: "firebolt",
    priority: 6,
    status: "needed",
    required: true,
    notes: "Should read instantly as a single target magic projectile.",
    subject: "a compact orange firebolt shaped like a sharp magical dart, white-hot core, ember edges, and three blue-violet aether sparks trailing behind",
    composition: "square centered icon, diagonal projectile from lower left to upper right, high contrast flame core against clean dark or transparent background, no extra flames, readable at 64x64"
  },
  {
    id: "heal_icon",
    category: "ability_icon",
    displayName: "Heal Icon",
    filename: "heal_icon.png",
    targetFolder: "icons",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "Shepherd ability button.",
    styleTags: ["icon", "ability", "heal", "faith", "support"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    abilityId: "heal",
    priority: 7,
    status: "needed",
    required: true,
    notes: "Must read as healing without using medical modern symbols.",
    subject: "a green-white holy hand of light mending a small cracked round shield, with a simple chapel glow and two soft healing motes",
    composition: "square centered icon, hand and shield form one clear silhouette, bright center, soft outer glow, no medical cross, no tiny runes, readable at 64x64"
  },
  {
    id: "free_marches_emblem",
    category: "faction_emblem",
    displayName: "Free Marches Emblem",
    filename: "free_marches_emblem.png",
    targetFolder: "icons",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "Faction emblem for menus, future diplomacy, campaign map, and UI panels.",
    styleTags: ["icon", "emblem", "free_marches", "shield", "tower"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    factionId: "free_marches",
    priority: 8,
    status: "needed",
    required: true,
    notes: "Simple symbolic mark, no words.",
    subject: "a simple Free Marches heraldic emblem combining a squat stone tower, kite shield, and small banner, using deep blue field, worn silver stone, and muted gold accent",
    composition: "flat centered emblem, no text, no outer frame required, three clear shapes only, thick readable silhouette, transparent or flat dark background, recognizable at 64x64"
  },
  {
    id: "ascendant_realms_key_art",
    category: "splash",
    displayName: "Ascendant Realms Key Art",
    filename: "ascendant_realms_key_art.png",
    targetFolder: "splash",
    preferredWidth: 1920,
    preferredHeight: 1080,
    usage: "Future store capsule exploration, splash screen, pitch material, and design reference.",
    styleTags: ["splash", "key_art", "hero", "army", "campaign"],
    smallSizeReadable: false,
    transparencyPreferred: false,
    flatBackgroundAllowed: false,
    priority: 9,
    status: "needed",
    required: true,
    notes: "Original key art only. No logo or text.",
    subject: "an original fantasy warlord hero overlooking a living campaign realm: small army banners below, captured resource shrines glowing in the valley, distant ruins, rival smoke columns, and aether-lit storm clouds over contested kingdoms",
    composition: "1920x1080 cinematic key art, hero foreground silhouette on a ridge at left, readable army groups in the middle ground, world-map scale in the distance, open sky area in upper right for future logo treatment, no text"
  },
  {
    id: "cleave_icon",
    category: "ability_icon",
    displayName: "Cleave Icon",
    filename: "cleave_icon.png",
    targetFolder: "icons",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "Warlord ability button.",
    styleTags: ["icon", "ability", "warlord", "melee", "arc"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    abilityId: "cleave",
    priority: 10,
    status: "needed",
    required: true,
    notes: "Needs to read as an area melee strike.",
    subject: "a heavy sword edge creating a bright crescent slash through sparks and dust, with a small worn silver blade silhouette at the base",
    composition: "square centered icon, one dominant sweeping arc, bold melee motion shape, high contrast, no enemy body parts, no clutter, readable at 64x64"
  },
  {
    id: "war_cry_icon",
    category: "ability_icon",
    displayName: "War Cry Icon",
    filename: "war_cry_icon.png",
    targetFolder: "icons",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "Warlord ability button.",
    styleTags: ["icon", "ability", "warlord", "shout", "morale"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    abilityId: "war_cry",
    priority: 11,
    status: "needed",
    required: true,
    notes: "Should not rely on a detailed face at small size.",
    subject: "a stylized Free Marches command horn in worn silver with deep blue wrap, emitting three muted gold shockwave arcs",
    composition: "square centered icon, horn silhouette angled slightly upward, exactly three clear sound-wave arcs, simple dark or transparent background, readable at 64x64"
  },
  {
    id: "arcane_burst_icon",
    category: "ability_icon",
    displayName: "Arcane Burst Icon",
    filename: "arcane_burst_icon.png",
    targetFolder: "icons",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "Arcanist ability button.",
    styleTags: ["icon", "ability", "arcane", "area_damage"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    abilityId: "arcane_burst",
    priority: 12,
    status: "needed",
    required: true,
    notes: "Needs a clear burst shape.",
    subject: "a violet-orange arcane explosion sigil bursting outward from a bright white central point, with four chunky aether shards and a simple ring fracture",
    composition: "square centered icon, circular radial burst fills 70 percent of canvas, strong value contrast, no tiny glyph text, simple dark or transparent background, readable at 64x64"
  },
  {
    id: "blink_icon",
    category: "ability_icon",
    displayName: "Blink Icon",
    filename: "blink_icon.png",
    targetFolder: "icons",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "Arcanist ability button.",
    styleTags: ["icon", "ability", "arcane", "movement", "teleport"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    abilityId: "blink",
    priority: 13,
    status: "needed",
    required: true,
    notes: "Needs to read as movement or teleport.",
    subject: "a small hooded arcanist silhouette dissolving into blue-white aether shards between two bright anchor marks",
    composition: "square centered icon, left-to-right teleport motion, silhouette remains readable, two anchor marks only, no detailed face, clean dark or transparent background, readable at 64x64"
  },
  {
    id: "blessing_icon",
    category: "ability_icon",
    displayName: "Blessing Icon",
    filename: "blessing_icon.png",
    targetFolder: "icons",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "Shepherd ability button.",
    styleTags: ["icon", "ability", "faith", "buff", "support"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    abilityId: "blessing",
    priority: 14,
    status: "needed",
    required: true,
    notes: "A supportive buff, not direct healing.",
    subject: "a small chapel charm glowing above a protected round shield, green-white blessing light wrapping around the shield edge",
    composition: "square centered icon, charm and shield form two large readable shapes, soft aura but crisp silhouette, no text, no tiny runes, readable at 64x64"
  },
  {
    id: "sanctify_ground_icon",
    category: "ability_icon",
    displayName: "Sanctify Ground Icon",
    filename: "sanctify_ground_icon.png",
    targetFolder: "icons",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "Shepherd ability button.",
    styleTags: ["icon", "ability", "faith", "area", "holy_ground"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    abilityId: "sanctify_ground",
    priority: 15,
    status: "needed",
    required: true,
    notes: "Needs to read as a holy area effect.",
    subject: "a glowing circle of sanctified ground made from green-white light, simple chapel-stone segments, and a few rising sparks",
    composition: "square top-down icon, dominant circular ring silhouette, four simple stone segments, minimal rune-like marks that do not become text, readable at 64x64"
  },
  {
    id: "enemy_commander_portrait",
    category: "portrait",
    displayName: "Enemy Commander Portrait",
    filename: "enemy_commander_portrait.png",
    targetFolder: "portraits",
    preferredWidth: 768,
    preferredHeight: 768,
    usage: "Future enemy hero panel, result screen, and campaign rival presentation.",
    styleTags: ["portrait", "enemy", "ashen_covenant", "commander"],
    smallSizeReadable: true,
    transparencyPreferred: false,
    flatBackgroundAllowed: true,
    factionId: "ashen_covenant",
    priority: 16,
    status: "needed",
    required: true,
    notes: "A rival commander for prototype enemy identity.",
    subject: "an Ashen Covenant commander with soot-black lamellar armor, ember red battle cloth, burnt bronze mask fragments hanging from the belt, ash-streaked face, and a ruthless controlled stare",
    composition: "square chest-up bust portrait, three-quarter view facing slightly right, ember rim light from below, heavy jagged shoulder silhouette, smoky volcanic background kept simple"
  },
  {
    id: "ashen_covenant_emblem",
    category: "faction_emblem",
    displayName: "Ashen Covenant Emblem",
    filename: "ashen_covenant_emblem.png",
    targetFolder: "icons",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "Faction emblem for future diplomacy, campaign map, and enemy UI.",
    styleTags: ["icon", "emblem", "ashen_covenant", "ember", "jagged"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    factionId: "ashen_covenant",
    priority: 17,
    status: "needed",
    required: true,
    notes: "Simple symbolic mark, no words.",
    subject: "a jagged Ashen Covenant emblem shaped like a black iron brazier fused with a broken volcanic crown, ember red core, burnt bronze edges",
    composition: "flat centered emblem, three main shapes, sharp readable silhouette, no text, no skull, transparent or flat dark background, recognizable at 64x64"
  },
  {
    id: "sylvan_concord_emblem",
    category: "faction_emblem",
    displayName: "Sylvan Concord Emblem",
    filename: "sylvan_concord_emblem.png",
    targetFolder: "icons",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "Faction emblem for future diplomacy, campaign map, and UI.",
    styleTags: ["icon", "emblem", "sylvan_concord", "moon", "roots"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    factionId: "sylvan_concord",
    priority: 18,
    status: "needed",
    required: true,
    notes: "Simple symbolic mark, no words.",
    subject: "a graceful Sylvan Concord emblem combining a crescent moon, interlocking roots, and living branch shapes in forest green, moon white, and bark brown",
    composition: "flat centered emblem, flowing organic silhouette, no text, no animal mascot, transparent or flat dark background, recognizable at 64x64"
  },
  {
    id: "crown_shrine_icon",
    category: "resource_icon",
    displayName: "Crown Shrine Icon",
    filename: "crown_shrine_icon.png",
    targetFolder: "icons",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "Resource site icon for Crowns.",
    styleTags: ["icon", "resource", "crowns", "shrine"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    priority: 19,
    status: "needed",
    required: true,
    notes: "Should read as wealth and control, not a literal modern coin pile.",
    subject: "a small ancient stone shrine topped with a simple crown-shaped relic, muted gold light pooling beneath it",
    composition: "square centered resource icon, crown relic and shrine read as one bold silhouette, no coin pile, simple dark or transparent background, readable at 64x64"
  },
  {
    id: "stone_quarry_icon",
    category: "resource_icon",
    displayName: "Stone Quarry Icon",
    filename: "stone_quarry_icon.png",
    targetFolder: "icons",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "Resource site icon for Stone.",
    styleTags: ["icon", "resource", "stone", "quarry"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    priority: 20,
    status: "needed",
    required: true,
    notes: "Should read as stone production at a glance.",
    subject: "three stacked cut stone blocks with a simple quarry chisel leaning against them, dusty pale highlights and dark cracks",
    composition: "square centered resource icon, angular block silhouette, chisel as secondary shape, minimal details, readable at 64x64"
  },
  {
    id: "iron_vein_icon",
    category: "resource_icon",
    displayName: "Iron Vein Icon",
    filename: "iron_vein_icon.png",
    targetFolder: "icons",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "Resource site icon for Iron.",
    styleTags: ["icon", "resource", "iron", "ore"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    priority: 21,
    status: "needed",
    required: true,
    notes: "Should read as military metal.",
    subject: "dark iron ore chunks with a simple forged spearhead emerging from the vein",
    composition: "centered ore and spearhead silhouette, high contrast metallic edges"
  },
  {
    id: "aether_well_icon",
    category: "resource_icon",
    displayName: "Aether Well Icon",
    filename: "aether_well_icon.png",
    targetFolder: "icons",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "Resource site icon for Aether.",
    styleTags: ["icon", "resource", "aether", "magic_well"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    priority: 22,
    status: "needed",
    required: true,
    notes: "Should read as magical energy source.",
    subject: "a small stone well filled with blue-violet aether light and rising magical motes",
    composition: "centered well silhouette, bright glowing core, simple dark outline"
  },
  {
    id: "battle_hud_panel",
    category: "ui",
    displayName: "Battle HUD Panel",
    filename: "battle_hud_panel.png",
    targetFolder: "ui",
    preferredWidth: 1024,
    preferredHeight: 256,
    usage: "Future HUD panel texture or UI reference.",
    styleTags: ["ui", "hud", "panel", "dark_fantasy"],
    smallSizeReadable: false,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    priority: 23,
    status: "needed",
    required: true,
    notes: "Low contrast background texture, not a final layout.",
    subject: "a dark fantasy strategy HUD panel texture made from worn metal, dark leather, and subtle gold trim",
    composition: "wide horizontal panel, quiet center for text, decorated edges, no text"
  },
  {
    id: "victory_screen_background",
    category: "ui",
    displayName: "Victory Screen Background",
    filename: "victory_screen_background.png",
    targetFolder: "ui",
    preferredWidth: 1920,
    preferredHeight: 1080,
    usage: "Victory and progression screen background.",
    styleTags: ["ui", "background", "victory", "results"],
    smallSizeReadable: false,
    transparencyPreferred: false,
    flatBackgroundAllowed: false,
    priority: 24,
    status: "needed",
    required: true,
    notes: "Should have a celebratory but restrained mood.",
    subject: "a captured shrine at dawn with Free Marches banners raised, calm soldiers in the distance, and soft aether light fading",
    composition: "wide background, uncluttered middle for result panels, no text"
  },
  {
    id: "defeat_screen_background",
    category: "ui",
    displayName: "Defeat Screen Background",
    filename: "defeat_screen_background.png",
    targetFolder: "ui",
    preferredWidth: 1920,
    preferredHeight: 1080,
    usage: "Defeat result screen background.",
    styleTags: ["ui", "background", "defeat", "results"],
    smallSizeReadable: false,
    transparencyPreferred: false,
    flatBackgroundAllowed: false,
    priority: 25,
    status: "needed",
    required: true,
    notes: "Somber, not graphic.",
    subject: "a fallen frontier banner near a ruined command hall at dusk, smoke in the distance, abandoned shields, subdued ember light",
    composition: "wide background, empty center for defeat panel, no text, no gore"
  },
  {
    id: "ui_panel_frame",
    category: "ui_kit",
    displayName: "Reusable Panel Frame",
    filename: "ui_panel_frame.png",
    targetFolder: "ui",
    preferredWidth: 1024,
    preferredHeight: 1024,
    usage: "Optional nine-slice frame for menu panels, hero panel, side panel, and major modal panels.",
    styleTags: ["ui_kit", "frame", "panel", "nine_slice", "dark_fantasy"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    priority: 26,
    status: "needed",
    required: false,
    notes: "Transparent center and reusable decorated edges. Do not make this a full painted panel background.",
    subject: "a reusable Ascendant Realms dark fantasy interface panel frame made from worn blackened iron, dark leather backing visible only near edges, muted gold corner brackets, and tiny blue aether glints",
    composition: "square transparent PNG frame for nine-slice use, ornate corners, repeatable top bottom left and right edges, fully transparent quiet center occupying at least 70 percent of the canvas, no text, no icons, no background scene"
  },
  {
    id: "ui_button_idle",
    category: "ui_kit",
    displayName: "Button Idle Frame",
    filename: "ui_button_idle.png",
    targetFolder: "ui",
    preferredWidth: 512,
    preferredHeight: 192,
    usage: "Optional nine-slice frame for normal menu and HUD buttons.",
    styleTags: ["ui_kit", "button", "idle", "nine_slice", "dark_fantasy"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    priority: 27,
    status: "needed",
    required: false,
    notes: "Button art must support text drawn by the browser over the top.",
    subject: "a normal idle fantasy strategy button frame in dark iron and worn leather with thin muted gold edge highlights and subtle deep blue side accents",
    composition: "wide transparent PNG button frame for nine-slice use, rounded rectangular silhouette, clean transparent center for text, readable corners, no words, no symbols, no baked label, no glow stronger than the border"
  },
  {
    id: "ui_button_hover",
    category: "ui_kit",
    displayName: "Button Hover Frame",
    filename: "ui_button_hover.png",
    targetFolder: "ui",
    preferredWidth: 512,
    preferredHeight: 192,
    usage: "Optional nine-slice frame for hovered or focused buttons.",
    styleTags: ["ui_kit", "button", "hover", "focus", "nine_slice", "dark_fantasy"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    priority: 28,
    status: "needed",
    required: false,
    notes: "Should match idle button, but read as interactable.",
    subject: "a hovered fantasy strategy button frame matching the idle state, with slightly brighter muted gold edge light, restrained blue aether line accents, and crisp readable border contrast",
    composition: "wide transparent PNG button frame for nine-slice use, same proportions as idle button, clean transparent center for text, no words, no symbols, no baked label, subtle focus glow limited to the edge"
  },
  {
    id: "ui_button_pressed",
    category: "ui_kit",
    displayName: "Button Pressed Frame",
    filename: "ui_button_pressed.png",
    targetFolder: "ui",
    preferredWidth: 512,
    preferredHeight: 192,
    usage: "Optional nine-slice frame for active or pressed buttons.",
    styleTags: ["ui_kit", "button", "pressed", "active", "nine_slice", "dark_fantasy"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    priority: 29,
    status: "needed",
    required: false,
    notes: "Should feel depressed inward without making the text area busy.",
    subject: "a pressed fantasy strategy button frame matching the idle and hover states, with darker inset iron, compressed gold edge highlights, and a subtle inward shadow",
    composition: "wide transparent PNG button frame for nine-slice use, same proportions as idle button, clean transparent center for text, no words, no icons, no baked label, edge-only pressed-state detail"
  },
  {
    id: "ui_resource_frame",
    category: "ui_kit",
    displayName: "Resource Counter Frame",
    filename: "ui_resource_frame.png",
    targetFolder: "ui",
    preferredWidth: 512,
    preferredHeight: 192,
    usage: "Optional frame for Crowns, Stone, Iron, and Aether resource chips in the battle HUD.",
    styleTags: ["ui_kit", "resource", "hud", "counter", "nine_slice"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    priority: 30,
    status: "needed",
    required: false,
    notes: "Must stay compact and readable in the top-left HUD.",
    subject: "a compact dark fantasy resource counter frame with a reinforced left color-band socket, blackened iron rim, worn leather center, and minimal muted gold ticks",
    composition: "wide transparent PNG frame for small HUD counters, clear empty center for resource name and number, left edge designed to accept a colored accent stripe, no text, no coins, no embedded icons, readable at small size"
  },
  {
    id: "ui_divider_ornament",
    category: "ui_kit",
    displayName: "Ornate Section Divider",
    filename: "ui_divider_ornament.png",
    targetFolder: "ui",
    preferredWidth: 1024,
    preferredHeight: 96,
    usage: "Optional decorative divider under panel titles and section headers.",
    styleTags: ["ui_kit", "divider", "ornament", "header"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    priority: 31,
    status: "needed",
    required: false,
    notes: "Thin and quiet. This should not overpower text.",
    subject: "a thin Ascendant Realms section divider made of worn silver linework, muted gold center notch, and two tiny blue aether sparks",
    composition: "wide transparent PNG ornament, very thin horizontal divider, symmetrical but not ornate to excess, quiet center flourish, no text, no icons, no heavy frame, works under headings"
  },
  {
    id: "ui_tooltip_frame",
    category: "ui_kit",
    displayName: "Tooltip And Info Frame",
    filename: "ui_tooltip_frame.png",
    targetFolder: "ui",
    preferredWidth: 768,
    preferredHeight: 512,
    usage: "Optional nine-slice frame for info boxes, status messages, and future tooltips.",
    styleTags: ["ui_kit", "tooltip", "info", "nine_slice", "dark_fantasy"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    priority: 32,
    status: "needed",
    required: false,
    notes: "Subtler than the main panel frame so tooltips do not dominate the screen.",
    subject: "a compact tooltip frame in dark translucent leather and fine worn silver trim, with tiny muted gold corner pins and a faint blue aether edge sheen",
    composition: "transparent PNG frame for nine-slice use, rectangular proportions, transparent quiet center for text, light edge decoration only, no text, no icons, no parchment scroll"
  },
  {
    id: "ui_minimap_frame",
    category: "ui_kit",
    displayName: "Minimap Frame",
    filename: "ui_minimap_frame.png",
    targetFolder: "ui",
    preferredWidth: 512,
    preferredHeight: 384,
    usage: "Optional frame for the battle minimap shell.",
    styleTags: ["ui_kit", "minimap", "hud", "frame"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    priority: 33,
    status: "needed",
    required: false,
    notes: "The center must stay empty so the live minimap can remain visible.",
    subject: "a compact fantasy strategy minimap frame with dark iron corners, worn silver edge rails, muted gold rivets, and subtle blue aether corner markers",
    composition: "rectangular transparent PNG frame, empty transparent center for map content, sturdy corners, thin readable edges, no map art, no icons, no compass labels, no text"
  },
  {
    id: "ui_ability_slot_frame",
    category: "ui_kit",
    displayName: "Ability Slot Frame",
    filename: "ui_ability_slot_frame.png",
    targetFolder: "ui",
    preferredWidth: 256,
    preferredHeight: 256,
    usage: "Optional frame around hero ability buttons and future ability slots.",
    styleTags: ["ui_kit", "ability", "slot", "frame", "hud"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    priority: 34,
    status: "needed",
    required: false,
    notes: "Must frame ability icons without hiding them.",
    subject: "a square ability slot frame combining blackened iron, fine silver bevels, muted gold corner caps, and a faint blue aether inner glow",
    composition: "square transparent PNG frame, fully transparent center for icon art, thick readable outer silhouette, no ability symbol, no numbers, no text, no background fill"
  },
  {
    id: "ui_inventory_slot_frame",
    category: "ui_kit",
    displayName: "Inventory Slot Frame",
    filename: "ui_inventory_slot_frame.png",
    targetFolder: "ui",
    preferredWidth: 256,
    preferredHeight: 256,
    usage: "Optional frame for inventory and equipment rows or future item slots.",
    styleTags: ["ui_kit", "inventory", "slot", "equipment", "frame"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    priority: 35,
    status: "needed",
    required: false,
    notes: "Neutral enough for weapons, armor, and trinkets.",
    subject: "a square inventory slot frame with dark leather inset, worn silver rim, small muted gold corner rivets, and subtle empty-item shadow",
    composition: "square transparent PNG frame, transparent or very quiet center for item art, no item icon, no numbers, no text, no decorative clutter"
  },
  {
    id: "ui_victory_panel_frame",
    category: "ui_kit",
    displayName: "Victory Panel Frame",
    filename: "ui_victory_panel_frame.png",
    targetFolder: "ui",
    preferredWidth: 1024,
    preferredHeight: 1024,
    usage: "Optional special nine-slice frame for victory results and progression panels.",
    styleTags: ["ui_kit", "victory", "panel", "frame", "nine_slice"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    priority: 36,
    status: "needed",
    required: false,
    notes: "A warmer variant of the generic panel frame.",
    subject: "a victory results panel frame for Ascendant Realms with worn silver metal, muted gold laurel-like corner marks, deep blue banner cloth accents, and faint dawn light along the top edge",
    composition: "square transparent PNG frame for nine-slice use, ornate corners and repeatable edges, fully transparent quiet center for battle result text, no words, no trophy icon, no character art, no background scene"
  },
  {
    id: "ui_defeat_panel_frame",
    category: "ui_kit",
    displayName: "Defeat Panel Frame",
    filename: "ui_defeat_panel_frame.png",
    targetFolder: "ui",
    preferredWidth: 1024,
    preferredHeight: 1024,
    usage: "Optional special nine-slice frame for defeat results panels.",
    styleTags: ["ui_kit", "defeat", "panel", "frame", "nine_slice"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    priority: 37,
    status: "needed",
    required: false,
    notes: "Somber variant of the generic panel frame, not graphic.",
    subject: "a defeat results panel frame for Ascendant Realms with blackened iron, dulled silver scratches, ember red hairline cracks, and sparse burnt bronze corner plates",
    composition: "square transparent PNG frame for nine-slice use, restrained somber corners and repeatable edges, fully transparent quiet center for battle result text, no words, no skulls, no gore, no background scene"
  },
  {
    id: "militia_unit_concept",
    category: "unit_concept",
    displayName: "Militia Unit Concept",
    filename: "militia_unit_concept.png",
    targetFolder: "units",
    preferredWidth: 1024,
    preferredHeight: 1024,
    usage: "Reference art for future Militia unit sprite or model.",
    styleTags: ["unit", "concept", "free_marches", "militia"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    factionId: "free_marches",
    unitId: "militia",
    priority: 40,
    status: "optional",
    required: false,
    notes: "Optional concept, not required by gameplay yet.",
    subject: "a Free Marches militia fighter with spear, round shield, padded jack, deep blue cloth strip, and worn silver helmet",
    composition: "full-body three-quarter unit concept, clear simple pose, transparent or plain background"
  },
  {
    id: "ranger_unit_concept",
    category: "unit_concept",
    displayName: "Ranger Unit Concept",
    filename: "ranger_unit_concept.png",
    targetFolder: "units",
    preferredWidth: 1024,
    preferredHeight: 1024,
    usage: "Reference art for future Ranger unit sprite or model.",
    styleTags: ["unit", "concept", "free_marches", "ranger"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    factionId: "free_marches",
    unitId: "ranger",
    priority: 41,
    status: "optional",
    required: false,
    notes: "Optional concept, not required by gameplay yet.",
    subject: "a frontier ranger with short bow, hooded blue-gray cloak, leather armor, travel packs, and practical boots",
    composition: "full-body three-quarter concept, bow silhouette clear, simple background"
  },
  {
    id: "acolyte_unit_concept",
    category: "unit_concept",
    displayName: "Acolyte Unit Concept",
    filename: "acolyte_unit_concept.png",
    targetFolder: "units",
    preferredWidth: 1024,
    preferredHeight: 1024,
    usage: "Reference art for future Acolyte unit sprite or model.",
    styleTags: ["unit", "concept", "free_marches", "support", "magic"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    factionId: "free_marches",
    unitId: "acolyte",
    priority: 42,
    status: "optional",
    required: false,
    notes: "Optional concept, not required by gameplay yet.",
    subject: "a young chapel acolyte with simple vestments, small lantern focus, travel satchel, and soft green-white magic",
    composition: "full-body three-quarter concept, support role readable, simple background"
  },
  {
    id: "command_hall_concept",
    category: "building_concept",
    displayName: "Command Hall Concept",
    filename: "command_hall_concept.png",
    targetFolder: "buildings",
    preferredWidth: 1024,
    preferredHeight: 1024,
    usage: "Reference art for future Command Hall building art.",
    styleTags: ["building", "concept", "free_marches", "base"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    factionId: "free_marches",
    buildingId: "command_hall",
    priority: 43,
    status: "optional",
    required: false,
    notes: "Optional concept, not required by gameplay yet.",
    subject: "a Free Marches stone command hall with timber supports, deep blue banners, a watch platform, and practical frontier defenses",
    composition: "three-quarter strategy building concept, strong readable footprint, simple ground plane"
  },
  {
    id: "barracks_concept",
    category: "building_concept",
    displayName: "Barracks Concept",
    filename: "barracks_concept.png",
    targetFolder: "buildings",
    preferredWidth: 1024,
    preferredHeight: 1024,
    usage: "Reference art for future Barracks building art.",
    styleTags: ["building", "concept", "free_marches", "military"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    factionId: "free_marches",
    buildingId: "barracks",
    priority: 44,
    status: "optional",
    required: false,
    notes: "Optional concept, not required by gameplay yet.",
    subject: "a compact Free Marches barracks with training yard, weapon racks, blue pennants, stone base, and timber roof",
    composition: "three-quarter strategy building concept, clear military purpose, simple ground plane"
  },
  {
    id: "mystic_lodge_concept",
    category: "building_concept",
    displayName: "Mystic Lodge Concept",
    filename: "mystic_lodge_concept.png",
    targetFolder: "buildings",
    preferredWidth: 1024,
    preferredHeight: 1024,
    usage: "Reference art for future Mystic Lodge building art.",
    styleTags: ["building", "concept", "free_marches", "magic"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    factionId: "free_marches",
    buildingId: "mystic_lodge",
    priority: 45,
    status: "optional",
    required: false,
    notes: "Optional concept, not required by gameplay yet.",
    subject: "a small frontier mystic lodge with chapel-stone foundation, hanging aether lanterns, blue cloth, and simple ritual circle",
    composition: "three-quarter strategy building concept, magical purpose readable, simple ground plane"
  },
  {
    id: "watchtower_concept",
    category: "building_concept",
    displayName: "Watchtower Concept",
    filename: "watchtower_concept.png",
    targetFolder: "buildings",
    preferredWidth: 1024,
    preferredHeight: 1024,
    usage: "Reference art for future Watchtower building art.",
    styleTags: ["building", "concept", "free_marches", "defense"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: true,
    factionId: "free_marches",
    buildingId: "watchtower",
    priority: 46,
    status: "optional",
    required: false,
    notes: "Optional concept, not required by gameplay yet.",
    subject: "a sturdy Free Marches watchtower with stone base, timber top, archer platform, and a small blue banner",
    composition: "three-quarter strategy building concept, tall readable silhouette, simple ground plane"
  },
  {
    id: "warlord_hero_battle_sprite",
    category: "unit_sprite",
    displayName: "Warlord Hero Battle Sprite",
    filename: "warlord_hero_battle_sprite.png",
    targetFolder: "units",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "In-battle hero sprite for the Warlord class.",
    styleTags: ["unit_sprite", "hero", "warlord", "free_marches", "battle"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: false,
    factionId: "free_marches",
    priority: 50,
    status: "optional",
    required: false,
    notes: "Preferred over the portrait when present.",
    subject: "a Free Marches warlord hero in practical worn silver plate, deep blue cloak, muted gold command sash, and a raised banner spear",
    composition: "single full-body three-quarter top-down RTS battle sprite, facing right, transparent background, centered, no scenery, no text, readable at 64x64"
  },
  {
    id: "arcanist_hero_battle_sprite",
    category: "unit_sprite",
    displayName: "Arcanist Hero Battle Sprite",
    filename: "arcanist_hero_battle_sprite.png",
    targetFolder: "units",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "In-battle hero sprite for the Arcanist class.",
    styleTags: ["unit_sprite", "hero", "arcanist", "battle"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: false,
    priority: 51,
    status: "optional",
    required: false,
    notes: "Preferred over the portrait when present.",
    subject: "an arcanist battlefield hero in layered charcoal robes with bronze clasps, ember aether focus stones, and one compact glowing hand",
    composition: "single full-body three-quarter top-down RTS battle sprite, facing right, transparent background, centered, no scenery, no text, readable at 64x64"
  },
  {
    id: "shepherd_hero_battle_sprite",
    category: "unit_sprite",
    displayName: "Shepherd Hero Battle Sprite",
    filename: "shepherd_hero_battle_sprite.png",
    targetFolder: "units",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "In-battle hero sprite for the Shepherd class.",
    styleTags: ["unit_sprite", "hero", "shepherd", "battle"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: false,
    factionId: "free_marches",
    priority: 52,
    status: "optional",
    required: false,
    notes: "Preferred over the portrait when present.",
    subject: "a Shepherd holy field commander in cream and moss-green vestments over light armor, ashwood staff, healer satchel, and chapel charms",
    composition: "single full-body three-quarter top-down RTS battle sprite, facing right, transparent background, centered, no scenery, no text, readable at 64x64"
  },
  {
    id: "militia_unit_sprite",
    category: "unit_sprite",
    displayName: "Militia Unit Battle Sprite",
    filename: "militia_unit_sprite.png",
    targetFolder: "units",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "In-battle sprite for Militia units.",
    styleTags: ["unit_sprite", "free_marches", "militia", "battle"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: false,
    factionId: "free_marches",
    unitId: "militia",
    priority: 53,
    status: "optional",
    required: false,
    notes: "Runtime prefers this over Militia Unit Concept.",
    subject: "a Free Marches militia fighter with spear, round shield, padded jack, blue cloth strip, and worn silver helmet",
    composition: "single full-body three-quarter top-down RTS battle sprite, facing right, transparent background, centered, no scenery, no text, readable at 48x48"
  },
  {
    id: "ranger_unit_sprite",
    category: "unit_sprite",
    displayName: "Ranger Unit Battle Sprite",
    filename: "ranger_unit_sprite.png",
    targetFolder: "units",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "In-battle sprite for Ranger units.",
    styleTags: ["unit_sprite", "free_marches", "ranger", "battle"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: false,
    factionId: "free_marches",
    unitId: "ranger",
    priority: 54,
    status: "optional",
    required: false,
    notes: "Runtime prefers this over Ranger Unit Concept.",
    subject: "a frontier ranger with short bow, hooded blue-gray cloak, leather armor, travel pack, and practical boots",
    composition: "single full-body three-quarter top-down RTS battle sprite, facing right, transparent background, centered, no scenery, no text, readable at 48x48"
  },
  {
    id: "acolyte_unit_sprite",
    category: "unit_sprite",
    displayName: "Acolyte Unit Battle Sprite",
    filename: "acolyte_unit_sprite.png",
    targetFolder: "units",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "In-battle sprite for Acolyte units.",
    styleTags: ["unit_sprite", "free_marches", "acolyte", "battle"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: false,
    factionId: "free_marches",
    unitId: "acolyte",
    priority: 55,
    status: "optional",
    required: false,
    notes: "Runtime prefers this over Acolyte Unit Concept.",
    subject: "a young chapel acolyte with simple vestments, small lantern focus, travel satchel, and green-white magic glow",
    composition: "single full-body three-quarter top-down RTS battle sprite, facing right, transparent background, centered, no scenery, no text, readable at 48x48"
  },
  {
    id: "raider_unit_sprite",
    category: "unit_sprite",
    displayName: "Raider Unit Battle Sprite",
    filename: "raider_unit_sprite.png",
    targetFolder: "units",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "In-battle sprite for enemy Raider units.",
    styleTags: ["unit_sprite", "ashen_covenant", "raider", "battle"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: false,
    factionId: "ashen_covenant",
    unitId: "raider",
    priority: 56,
    status: "optional",
    required: false,
    notes: "Missing until generated manually.",
    subject: "an Ashen Covenant raider with soot-black leather, ember red cloth, hooked blade, light shield, and aggressive forward posture",
    composition: "single full-body three-quarter top-down RTS battle sprite, facing left, transparent background, centered, no scenery, no text, readable at 48x48"
  },
  {
    id: "hexer_unit_sprite",
    category: "unit_sprite",
    displayName: "Hexer Unit Battle Sprite",
    filename: "hexer_unit_sprite.png",
    targetFolder: "units",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "In-battle sprite for enemy Hexer units.",
    styleTags: ["unit_sprite", "ashen_covenant", "hexer", "battle"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: false,
    factionId: "ashen_covenant",
    unitId: "hexer",
    priority: 57,
    status: "optional",
    required: false,
    notes: "Missing until generated manually.",
    subject: "an Ashen Covenant hexer caster in dark ragged robes with violet ember magic, burnt bronze mask fragments, and a crooked ritual staff",
    composition: "single full-body three-quarter top-down RTS battle sprite, facing left, transparent background, centered, no scenery, no text, readable at 48x48"
  },
  {
    id: "brute_unit_sprite",
    category: "unit_sprite",
    displayName: "Brute Unit Battle Sprite",
    filename: "brute_unit_sprite.png",
    targetFolder: "units",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "In-battle sprite for enemy Brute units.",
    styleTags: ["unit_sprite", "ashen_covenant", "brute", "battle"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: false,
    factionId: "ashen_covenant",
    unitId: "brute",
    priority: 58,
    status: "optional",
    required: false,
    notes: "Missing until generated manually.",
    subject: "a heavy Ashen Covenant brute with blackened iron plates, ember red wraps, oversized maul, hunched shoulders, and thick armored silhouette",
    composition: "single full-body three-quarter top-down RTS battle sprite, facing left, transparent background, centered, no scenery, no text, readable at 56x56"
  },
  {
    id: "enemy_commander_unit_sprite",
    category: "unit_sprite",
    displayName: "Enemy Commander Battle Sprite",
    filename: "enemy_commander_unit_sprite.png",
    targetFolder: "units",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "In-battle sprite for the enemy commander.",
    styleTags: ["unit_sprite", "ashen_covenant", "commander", "battle"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: false,
    factionId: "ashen_covenant",
    unitId: "enemy_commander",
    priority: 59,
    status: "optional",
    required: false,
    notes: "Preferred over the portrait when present.",
    subject: "an Ashen Covenant commander with soot-black lamellar armor, ember red battle cloth, jagged shoulder silhouette, and a cruel command blade",
    composition: "single full-body three-quarter top-down RTS battle sprite, facing left, transparent background, centered, no scenery, no text, readable at 64x64"
  },
  {
    id: "wild_hound_unit_sprite",
    category: "unit_sprite",
    displayName: "Wild Hound Battle Sprite",
    filename: "wild_hound_unit_sprite.png",
    targetFolder: "units",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "In-battle sprite for neutral Wild Hound units.",
    styleTags: ["unit_sprite", "neutral", "monster", "battle"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: false,
    factionId: "wilds",
    unitId: "wild_hound",
    priority: 60,
    status: "optional",
    required: false,
    notes: "Missing until generated manually.",
    subject: "a lean territorial fantasy wild hound with tawny fur, dark mane, sharp ears, and low lunging posture",
    composition: "single full-body three-quarter top-down RTS battle sprite, facing left, transparent background, centered, no scenery, no text, readable at 44x44"
  },
  {
    id: "stone_imp_unit_sprite",
    category: "unit_sprite",
    displayName: "Stone Imp Battle Sprite",
    filename: "stone_imp_unit_sprite.png",
    targetFolder: "units",
    preferredWidth: 512,
    preferredHeight: 512,
    usage: "In-battle sprite for neutral Stone Imp units.",
    styleTags: ["unit_sprite", "neutral", "monster", "battle"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: false,
    factionId: "wilds",
    unitId: "stone_imp",
    priority: 61,
    status: "optional",
    required: false,
    notes: "Missing until generated manually.",
    subject: "a squat stone imp with cracked gray rock body, pale quarry dust highlights, tiny ember eyes, and chunky clawed hands",
    composition: "single full-body three-quarter top-down RTS battle sprite, facing left, transparent background, centered, no scenery, no text, readable at 44x44"
  },
  {
    id: "command_hall_building_sprite",
    category: "building_sprite",
    displayName: "Command Hall Battle Sprite",
    filename: "command_hall_building_sprite.png",
    targetFolder: "buildings",
    preferredWidth: 768,
    preferredHeight: 768,
    usage: "In-battle sprite for the player Command Hall.",
    styleTags: ["building_sprite", "free_marches", "command_hall", "battle"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: false,
    factionId: "free_marches",
    buildingId: "command_hall",
    priority: 62,
    status: "optional",
    required: false,
    notes: "Runtime prefers this over Command Hall Concept.",
    subject: "a Free Marches stone command hall with timber supports, deep blue banners, watch platform, and practical frontier defenses",
    composition: "single three-quarter top-down RTS building sprite, transparent background, centered, clear rectangular footprint, no scenery, no text, readable at 96x82"
  },
  {
    id: "barracks_building_sprite",
    category: "building_sprite",
    displayName: "Barracks Battle Sprite",
    filename: "barracks_building_sprite.png",
    targetFolder: "buildings",
    preferredWidth: 768,
    preferredHeight: 768,
    usage: "In-battle sprite for the player Barracks.",
    styleTags: ["building_sprite", "free_marches", "barracks", "battle"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: false,
    factionId: "free_marches",
    buildingId: "barracks",
    priority: 63,
    status: "optional",
    required: false,
    notes: "Runtime prefers this over Barracks Concept.",
    subject: "a compact Free Marches barracks with training yard, weapon racks, blue pennants, stone base, and timber roof",
    composition: "single three-quarter top-down RTS building sprite, transparent background, centered, clear rectangular footprint, no scenery, no text, readable at 82x64"
  },
  {
    id: "mystic_lodge_building_sprite",
    category: "building_sprite",
    displayName: "Mystic Lodge Battle Sprite",
    filename: "mystic_lodge_building_sprite.png",
    targetFolder: "buildings",
    preferredWidth: 768,
    preferredHeight: 768,
    usage: "In-battle sprite for the player Mystic Lodge.",
    styleTags: ["building_sprite", "free_marches", "mystic_lodge", "battle"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: false,
    factionId: "free_marches",
    buildingId: "mystic_lodge",
    priority: 64,
    status: "optional",
    required: false,
    notes: "Runtime prefers this over Mystic Lodge Concept.",
    subject: "a small frontier mystic lodge with chapel-stone foundation, hanging aether lanterns, blue cloth, and a simple ritual circle",
    composition: "single three-quarter top-down RTS building sprite, transparent background, centered, clear rectangular footprint, no scenery, no text, readable at 72x62"
  },
  {
    id: "watchtower_building_sprite",
    category: "building_sprite",
    displayName: "Watchtower Battle Sprite",
    filename: "watchtower_building_sprite.png",
    targetFolder: "buildings",
    preferredWidth: 768,
    preferredHeight: 768,
    usage: "In-battle sprite for the player Watchtower.",
    styleTags: ["building_sprite", "free_marches", "watchtower", "battle"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: false,
    factionId: "free_marches",
    buildingId: "watchtower",
    priority: 65,
    status: "optional",
    required: false,
    notes: "Runtime prefers this over Watchtower Concept.",
    subject: "a sturdy Free Marches watchtower with stone base, timber archer platform, small blue banner, and defensive railings",
    composition: "single three-quarter top-down RTS building sprite, transparent background, centered, tall readable silhouette, no scenery, no text, readable at 48x72"
  },
  {
    id: "enemy_stronghold_building_sprite",
    category: "building_sprite",
    displayName: "Enemy Stronghold Battle Sprite",
    filename: "enemy_stronghold_building_sprite.png",
    targetFolder: "buildings",
    preferredWidth: 768,
    preferredHeight: 768,
    usage: "In-battle sprite for the enemy Stronghold objective.",
    styleTags: ["building_sprite", "ashen_covenant", "stronghold", "battle"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: false,
    factionId: "ashen_covenant",
    buildingId: "enemy_stronghold",
    priority: 66,
    status: "optional",
    required: false,
    notes: "Missing until generated manually.",
    subject: "an Ashen Covenant enemy stronghold with blackened stone, ember red banners, burnt bronze spikes, smoky ritual furnace, and jagged battlements",
    composition: "single three-quarter top-down RTS building sprite, transparent background, centered, clear rectangular footprint, no scenery, no text, readable at 104x88"
  },
  {
    id: "enemy_barracks_building_sprite",
    category: "building_sprite",
    displayName: "Enemy Barracks Battle Sprite",
    filename: "enemy_barracks_building_sprite.png",
    targetFolder: "buildings",
    preferredWidth: 768,
    preferredHeight: 768,
    usage: "In-battle sprite for the enemy Barracks.",
    styleTags: ["building_sprite", "ashen_covenant", "barracks", "battle"],
    smallSizeReadable: true,
    transparencyPreferred: true,
    flatBackgroundAllowed: false,
    factionId: "ashen_covenant",
    buildingId: "enemy_barracks",
    priority: 67,
    status: "optional",
    required: false,
    notes: "Missing until generated manually.",
    subject: "an Ashen Covenant barracks with black timber, rough volcanic stone, ember red cloth strips, crude weapon racks, and burnt bronze braces",
    composition: "single three-quarter top-down RTS building sprite, transparent background, centered, clear rectangular footprint, no scenery, no text, readable at 82x64"
  }
];

export function requiredAssetIds(): string[] {
  return ASSET_REGISTRY.filter((asset) => asset.required).map((asset) => asset.id);
}
