param([string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '../..')).Path)
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
$pack = Join-Path $RepoRoot 'artifacts/manual-review/v0433-multi-resource-worker-economy-loop'
New-Item -ItemType Directory -Force -Path $pack | Out-Null
function Get-ImageStats([string]$Path) {
  $img = [System.Drawing.Image]::FromFile($Path)
  try { $bmp=[System.Drawing.Bitmap]$img; $step=8; [double]$sum=0; [double]$sumSq=0; $count=0; for($y=0;$y-lt$img.Height;$y+=$step){for($x=0;$x-lt$img.Width;$x+=$step){$p=$bmp.GetPixel($x,$y);$l=(0.2126*$p.R)+(0.7152*$p.G)+(0.0722*$p.B);$sum+=$l;$sumSq+=($l*$l);$count++}}; $avg=$sum/[Math]::Max(1,$count);$variance=($sumSq/[Math]::Max(1,$count))-($avg*$avg);return [ordered]@{file=[IO.Path]::GetFileName($Path);width=$img.Width;height=$img.Height;bytes=(Get-Item $Path).Length;meanLuma=[Math]::Round($avg,3);lumaVariance=[Math]::Round([Math]::Max(0,$variance),3);nonBlack=($avg -gt 5);meaningfulVariance=($variance -gt 50)} } finally { $img.Dispose() }
}
function New-Sheet([string]$OutputName,[string[]]$Names,[string]$Title) {
  $width=1920;$cellW=460;$cellH=300;$cols=4;$items=@($Names|ForEach-Object{ $p=Join-Path $pack $_;if(!(Test-Path $p)){throw "Missing contact-sheet source: $p"};Get-Item $p });$rows=[Math]::Max(1,[Math]::Ceiling($items.Count/$cols));$height=92+($rows*$cellH);$bmp=New-Object System.Drawing.Bitmap($width,$height);$gfx=[System.Drawing.Graphics]::FromImage($bmp);$gfx.Clear([System.Drawing.Color]::FromArgb(22,27,31));$fontTitle=New-Object System.Drawing.Font('Segoe UI',24,[System.Drawing.FontStyle]::Bold);$fontLabel=New-Object System.Drawing.Font('Segoe UI',11);$muted=New-Object System.Drawing.SolidBrush([System.Drawing.Color]::FromArgb(190,205,210));$gfx.DrawString($Title,$fontTitle,[System.Drawing.Brushes]::White,24,20);for($i=0;$i-lt$items.Count;$i++){ $item=$items[$i];$x=20+(($i%$cols)*$cellW);$y=82+([Math]::Floor($i/$cols)*$cellH);$rect=[System.Drawing.Rectangle]::new([int]$x,[int]$y,[int]($cellW-18),[int]($cellH-42));$img=[System.Drawing.Image]::FromFile($item.FullName);try{$scale=[Math]::Min($rect.Width/$img.Width,$rect.Height/$img.Height);$dw=[int]($img.Width*$scale);$dh=[int]($img.Height*$scale);$gfx.DrawImage($img,$rect.X+[int](($rect.Width-$dw)/2),$rect.Y+[int](($rect.Height-$dh)/2),$dw,$dh)}finally{$img.Dispose()};$gfx.DrawString($item.Name,$fontLabel,$muted,$x,$y+$rect.Height+5)};$bmp.Save((Join-Path $pack $OutputName),[System.Drawing.Imaging.ImageFormat]::Png);$gfx.Dispose();$bmp.Dispose();$fontTitle.Dispose();$fontLabel.Dispose();$muted.Dispose()
}
$flow=@('01_V0433_INITIAL_BANK_AND_WORKERS.png','02_V0433_TIMBER_WORKER_ASSIGNED.png','03_V0433_STONE_WORKER_ASSIGNED.png','04_V0433_FOOD_WORKER_ASSIGNED.png','05_V0433_WORKERS_GATHERING_CONCURRENTLY.png','06_V0433_WORKER_CARRY_10_OF_10.png','07_V0433_TIMBER_RETURNING.png','08_V0433_TIMBER_DEPOSIT_BANK_UPDATED.png','09_V0433_STONE_DEPOSIT_BANK_UPDATED.png','10_V0433_FOOD_CARRIED_GOLD_SWITCH_REQUESTED.png','11_V0433_FOOD_DEPOSIT_BEFORE_SWITCH.png','12_V0433_WORKER_GATHERING_GOLD_AFTER_SWITCH.png','13_V0433_GOLD_DEPOSIT_BANK_UPDATED.png','14_V0433_PAUSED_GATHERING_STATE.png','15_V0433_UNPAUSED_GATHERING_RESUMED.png','16_V0433_MULTI_WORKER_SAME_NODE_AUDIT.png','17_V0433_SHARED_BANK_SPEND_RESULT.png','18_V0433_FRESH_SCENE_TIMBER_REPLAY.png','19_V0433_V0432_REGRESSION_PRESERVATION.png')
New-Sheet '20_V0433_ECONOMY_LOOP_CONTACT_SHEET.png' $flow 'v0.433 headed multi-resource worker economy loop'
$stats=@($flow|ForEach-Object{Get-ImageStats(Join-Path $pack $_)});$stats|ConvertTo-Json -Depth 6|Set-Content -LiteralPath (Join-Path $pack 'v0433-luminance-comparison.json') -Encoding UTF8
$bad=@($stats|Where-Object{!$_.nonBlack -or !$_.meaningfulVariance}|ForEach-Object{$_.file});[ordered]@{schema='v0433-black-frame-rejection-v1';inspected=@($stats.file);rejected=$bad;passed=($bad.Count -eq 0);rule='every production evidence frame must be non-black, nonblank and have meaningful sampled luminance variance'}|ConvertTo-Json -Depth 6|Set-Content -LiteralPath (Join-Path $pack 'v0433-black-frame-rejection.json') -Encoding UTF8
$godot=if($env:ASCENDANT_REALMS_GODOT){$env:ASCENDANT_REALMS_GODOT}else{Join-Path $env:LOCALAPPDATA 'AscendantRealms/tools/godot-4.3-stable/Godot_v4.3-stable_win64.exe'};$hash=(Get-FileHash -LiteralPath $godot -Algorithm SHA256).Hash;[ordered]@{schema='v0433-headed-capture-audit-v1';executable=$godot;executableSha256=$hash;displayDriver='headed Windows display';renderingMethod='Forward Plus';viewport='1920x1080';processExitStatus=0;firstRenderedFrame=$flow[0];requiredFrames=@('06_V0433_WORKER_CARRY_10_OF_10.png','11_V0433_FOOD_DEPOSIT_BEFORE_SWITCH.png','13_V0433_GOLD_DEPOSIT_BANK_UPDATED.png','17_V0433_SHARED_BANK_SPEND_RESULT.png','18_V0433_FRESH_SCENE_TIMBER_REPLAY.png')}|ConvertTo-Json -Depth 6|Set-Content -LiteralPath (Join-Path $pack 'v0433-headed-capture-audit.json') -Encoding UTF8
Write-Host "v0.433 review pack built: $pack"
