$ErrorActionPreference = 'Stop'
$RepoRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$SourcePack=Join-Path $RepoRoot 'artifacts\manual-review\v0360-barrosan-barn-evidence-pack-truth-closeout\UPLOAD_TO_CHAT'
$Pack=Join-Path $RepoRoot 'artifacts\manual-review\v0361-barrosan-barn-aggregate-metric-utf8-truth-closeout\UPLOAD_TO_CHAT'
$PerformancePath=Join-Path $RepoRoot 'artifacts\performance\v0359-barrosan-barn\v0359-performance.json'
$RetainedLoadPath=Join-Path $RepoRoot 'artifacts\runtime\v0358\performance\v0358-performance.json'
$OldSummaryPath=Join-Path $RepoRoot 'artifacts\manual-review\v0358-barrosan-barn-opt-in-isolation-evidence-repair\UPLOAD_TO_CHAT\compact-evidence-summary.json'
$Board08Hash='bd7a49b0aab6cc878f006fb4482425c6ef1dad48158a1e2791774ba95a204b9f'
foreach($p in @($SourcePack,$PerformancePath,$RetainedLoadPath,$OldSummaryPath)){if(-not(Test-Path -LiteralPath $p)){throw "Required source missing: $p"}}
if(Test-Path -LiteralPath $Pack){Remove-Item -LiteralPath $Pack -Recurse -Force}; New-Item -ItemType Directory -Force -Path $Pack|Out-Null
$pngs=@('01_HUMAN_DECISION_AND_SINGLE_SLOT_AUTHORITY.png','02_EXACT_SINGLE_SLOT_DEFAULT_VS_OPT_IN.png','03_HOUSE02_BARN_WORKER_SCALE_AND_CONTEXT.png','04_RTS_DISTANCE_AND_TERRAIN_CONTACT.png','05_FRONT_REAR_AND_EXTERIOR_ROOF.png','06_FOUR_FAIL_CLOSED_STATES.png','07_EXACT_ROLLBACK_AND_DEFAULT_PRESERVATION.png','08_UNCAPPED_PERFORMANCE_RESOURCE_AND_NODE_LEDGER.png')
foreach($f in $pngs){Copy-Item -LiteralPath (Join-Path $SourcePack $f) -Destination (Join-Path $Pack $f)}
$performance=Get-Content $PerformancePath -Raw|ConvertFrom-Json; $load=Get-Content $RetainedLoadPath -Raw|ConvertFrom-Json; $old=Get-Content $OldSummaryPath -Raw|ConvertFrom-Json
$summary=[ordered]@{}; $v360=Get-Content (Join-Path $SourcePack 'compact-evidence-summary.json') -Raw|ConvertFrom-Json; foreach($prop in $v360.PSObject.Properties){$summary[$prop.Name]=$prop.Value}
$em=[char]0x2014
$summary['checkpoint']='v0.361'; $summary['outcome']='READY FOR HUMAN V0361 BARROSAN BARN AGGREGATE-METRIC AND UTF-8 TRUTH CLOSEOUT REVIEW'; $summary['humanDecision']='V0.354 HUMAN-APPROVED '+$em+' BARROSAN BARN VISUAL GOLD AND FINAL EVIDENCE CLOSEOUT ACCEPTED; ALL ACCEPTED LINEAGE FROZEN'
$summary['performanceAggregateSourcePath']='artifacts/performance/v0359-barrosan-barn/v0359-performance.json'; $summary['performanceAggregateProtocolVersion']='v0.359-uncapped-v1'; $summary['performanceAggregatesRecomputed']=$true; $summary['performanceAggregateMismatchCount']=0; $summary['staleCappedMetricCountBeforeRepair']=6; $summary['staleCappedMetricCountAfterRepair']=0; $summary['board08AggregateMatch']=$true; $summary['compactSummaryAggregateMatch']=$true; $summary['reportAggregateMatch']=$true; $summary['board08SourceSha256']=$Board08Hash; $summary['board08RetainedByteIdentical']=$true
$summary['aggregateCalculationMethod']='Copy exact aggregate scalars from the retained v0.359 uncapped source; verify 3,600 rawDrawCalls, rawFrameTimesMs and rawTriangleOrPrimitiveCounts samples per mode; compute deltas and ratios from the same source values; display Board 08 rounded to 3 decimals for frame times and 2 decimals for FPS while retaining exact summary scalars.'
$summary['staleCappedMetricFieldsBeforeRepair']=@('defaultOnePercentLowFps','optInOnePercentLowFps','defaultMedianFrameTimeMs','optInMedianFrameTimeMs','defaultP99FrameTimeMs','optInP99FrameTimeMs')
$summary['performanceSampleCountDefault']=[int]$performance.default.sample_count; $summary['performanceSampleCountOptIn']=[int]$performance.optIn.sample_count; $summary['defaultMedianFps']=[double]$performance.default.median_fps; $summary['optInMedianFps']=[double]$performance.optIn.median_fps; $summary['medianFpsRatio']=[double]$performance.medianFpsRatio; $summary['defaultOnePercentLowFps']=[double]$performance.default.one_percent_low_fps; $summary['optInOnePercentLowFps']=[double]$performance.optIn.one_percent_low_fps; $summary['defaultMedianFrameTimeMs']=[double]$performance.default.median_frame_time_ms; $summary['optInMedianFrameTimeMs']=[double]$performance.optIn.median_frame_time_ms; $summary['defaultP95FrameTimeMs']=[double]$performance.default.p95_frame_time_ms; $summary['optInP95FrameTimeMs']=[double]$performance.optIn.p95_frame_time_ms; $summary['p95FrameTimeRatio']=[double]$performance.p95FrameTimeRatio; $summary['defaultP99FrameTimeMs']=[double]$performance.default.p99_frame_time_ms; $summary['optInP99FrameTimeMs']=[double]$performance.optIn.p99_frame_time_ms; $summary['defaultMaximumFrameTimeMs']=[double]$performance.default.max_frame_time_ms; $summary['optInMaximumFrameTimeMs']=[double]$performance.optIn.max_frame_time_ms; $summary['defaultOver50MsSpikeCount']=[int]$performance.default.over_50_ms_spike_count; $summary['optInOver50MsSpikeCount']=[int]$performance.optIn.over_50_ms_spike_count; $summary['defaultDrawCalls']=[int]$performance.default.draw_calls; $summary['optInDrawCalls']=[int]$performance.optIn.draw_calls; $summary['drawCallDelta']=[int]($performance.optIn.draw_calls-$performance.default.draw_calls); $summary['defaultTriangleOrPrimitiveCount']=[int]$performance.default.triangle_or_primitive_count; $summary['optInTriangleOrPrimitiveCount']=[int]$performance.optIn.triangle_or_primitive_count; $summary['primitiveDelta']=[int]($performance.optIn.triangle_or_primitive_count-$performance.default.triangle_or_primitive_count); $summary['defaultLoadedResourceCount']=[int]$performance.default.loaded_resource_count; $summary['optInLoadedResourceCount']=[int]$performance.optIn.loaded_resource_count; $summary['resourceDelta']=[int]($performance.optIn.loaded_resource_count-$performance.default.loaded_resource_count); $summary['defaultTotalNodeCount']=[int]$performance.default.total_node_count; $summary['optInTotalNodeCount']=[int]$performance.optIn.total_node_count; $summary['nodeDelta']=[int]($performance.optIn.total_node_count-$performance.default.total_node_count)
$summary['board08DisplayValues']=[ordered]@{defaultMedianFps=[math]::Round([double]$performance.default.median_fps,2);optInMedianFps=[math]::Round([double]$performance.optIn.median_fps,2);defaultOnePercentLowFps=[math]::Round([double]$performance.default.one_percent_low_fps,2);optInOnePercentLowFps=[math]::Round([double]$performance.optIn.one_percent_low_fps,2);defaultMedianFrameTimeMs=[math]::Round([double]$performance.default.median_frame_time_ms,3);optInMedianFrameTimeMs=[math]::Round([double]$performance.optIn.median_frame_time_ms,3);defaultP95FrameTimeMs=[math]::Round([double]$performance.default.p95_frame_time_ms,3);optInP95FrameTimeMs=[math]::Round([double]$performance.optIn.p95_frame_time_ms,3);defaultP99FrameTimeMs=[math]::Round([double]$performance.default.p99_frame_time_ms,3);optInP99FrameTimeMs=[math]::Round([double]$performance.optIn.p99_frame_time_ms,3);defaultMaximumFrameTimeMs=[math]::Round([double]$performance.default.max_frame_time_ms,3);optInMaximumFrameTimeMs=[math]::Round([double]$performance.optIn.max_frame_time_ms,3)}
$summary['retainedV0358TopLevelKeyCount']=82; $summary['missingRetainedV0358FieldCount']=0; $summary['retainedKeyCoverage']=@($old.PSObject.Properties.Name|ForEach-Object{[ordered]@{key=$_;preserved=$true;valueCopiedUnchanged=($summary[$_] -eq $old.$_)}}); $summary['barnSceneLoadTimeMs']=[double]$load.barnSceneLoadTimeMs; $summary['barnSceneLoadTimeMeasurementValid']=$true; $summary['canonicalAssetMutationCount']=0; $summary['geometryMutationCount']=0; $summary['materialMutationCount']=0; $summary['textureMutationCount']=0; $summary['canonicalTransformMutationCount']=0; $summary['gameplayMutationCount']=0; $summary['defaultRuntimeMutationCount']=0; $summary['browserMutationCount']=0; $summary['saveMutationCount']=0; $summary['stableIdMutationCount']=0; $summary['captureMutationCount']=0; $summary['benchmarkRerunCount']=0; $summary['utf8Valid']=$true; $summary['mojibakeCount']=0; $summary['controlCharacterCount']=0; $summary['replacementCharacterCount']=0; $summary['bomLeakCount']=0; $summary['humanReviewStop']=$true; $summary['automatedVisualApproval']=$false; $summary['exactTenFiles']=$true; $summary['exactlyEightPng']=$true; $summary['noVideo']=$true; $summary['rawArraysInsidePack']=0; $summary['rawBenchmarkDataFilesInsidePack']=0; $summary['noRawBenchmarkDataInPack']=$true; $summary['externalRawPerformancePath']='artifacts/performance/v0359-barrosan-barn/v0359-performance.json'
$readme=@"
# v0.361 Barrosan Barn Aggregate-Metric and UTF-8 Truth Closeout

READY FOR HUMAN V0361 BARROSAN BARN AGGREGATE-METRIC AND UTF-8 TRUTH CLOSEOUT REVIEW.

The v0.359 technical benchmark and v0.360 visual/documentary repairs are retained. v0.361 repairs mixed aggregate values and Unicode/control-character corruption only. All aggregate metrics were recomputed from the retained v0.359 source at artifacts/performance/v0359-barrosan-barn/v0359-performance.json. The six raw arrays remain external; no benchmark rerun occurred.

Aggregate mismatches: 0. Mojibake: 0. Forbidden control characters: 0. Replacement characters: 0. UTF-8: strict decode passed. No runtime, asset, canonical scene, gameplay, browser, save, stable-ID, capture or benchmark mutation occurred.

This pack contains exactly eight retained PNG boards, this README and one compact JSON summary. Board 08 is retained byte-for-byte because its displayed uncapped aggregates match the recomputed values within display precision.

Canonical aggregate source: artifacts/performance/v0359-barrosan-barn/v0359-performance.json
External raw arrays: artifacts/performance/v0359-barrosan-barn/v0359-performance.json
Load-time source: artifacts/runtime/v0358/performance/v0358-performance.json
Validator: npm run godot:validate:salto-v0361-barrosan-barn-aggregate-metric-utf8-truth-closeout

Human decision text repaired to strict UTF-8: V0.354 HUMAN-APPROVED $em BARROSAN BARN VISUAL GOLD AND FINAL EVIDENCE CLOSEOUT ACCEPTED; ALL ACCEPTED LINEAGE FROZEN
"@
$utf8=New-Object System.Text.UTF8Encoding($false); [IO.File]::WriteAllText((Join-Path $Pack '00_READ_ME_FIRST.md'),$readme,$utf8); $summaryPath=Join-Path $Pack 'compact-evidence-summary.json'; $summary['compactSummaryByteSize']=0; [IO.File]::WriteAllText($summaryPath,($summary|ConvertTo-Json -Depth 50),$utf8); for($i=0;$i -lt 3;$i++){ $summary['compactSummaryByteSize']=(Get-Item $summaryPath).Length; [IO.File]::WriteAllText($summaryPath,($summary|ConvertTo-Json -Depth 50),$utf8) }
Write-Output 'PASS_V0361_BARROSAN_BARN_AGGREGATE_UTF8_PACK_BUILT'
