import { createHash } from "node:crypto";
import { execFileSync, spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const repo = path.resolve(import.meta.dirname, "../..");
const project = path.join(repo, "production", "ascendant-realms-godot");
const godot = process.env.ASCENDANT_REALMS_GODOT || "D:\\CodexData\\tools\\godot-4.6.3-stable\\Godot_v4.6.3-stable_win64.exe";
const evidenceRoot = process.env.P1R14_EVIDENCE_ROOT || "D:\\CodexData\\evidence\\ascendant-realms-p1-remediation-c\\p1r14";
const logsRoot = process.env.P1R14_LOG_ROOT || "D:\\CodexData\\logs\\ascendant-realms-p1-remediation-c";
mkdirSync(evidenceRoot, { recursive: true }); mkdirSync(logsRoot, { recursive: true });
const sourceSha = () => execFileSync("git", ["rev-parse", "HEAD"], { cwd: repo, encoding: "utf8" }).trim();
const sha256 = (file) => createHash("sha256").update(readFileSync(file)).digest("hex");
function withAutoload(fn) { const f = path.join(project, "project.godot"); const original = readFileSync(f, "utf8"); const marker = 'P1R14Capture="*res://tests/p1r14_tactical_hierarchy.gd"'; const patched = original.includes(marker) ? original : original.replace('P1S1Capture="*res://tests/p1s1_viewport_safe_area.gd"', 'P1S1Capture="*res://tests/p1s1_viewport_safe_area.gd"\n' + marker); writeFileSync(f, patched); try { return fn(); } finally { writeFileSync(f, original); } }
function run(map, out) { mkdirSync(out, { recursive: true }); const log = path.join(logsRoot, `p1r14-${map}.log`); const result = spawnSync(godot, ["--path", project, "--resolution", "1920x1080", "--windowed", "--position", "20,20", "--log-file", log], { cwd: repo, env: { ...process.env, TEMP:"D:\\CodexData\\temp", TMP:"D:\\CodexData\\temp", ASCENDANT_P1R14_SOURCE_SHA:sourceSha(), ASCENDANT_P1R14_MAP:map, ASCENDANT_P1R14_WIDTH:"1920", ASCENDANT_P1R14_HEIGHT:"1080", ASCENDANT_P1R14_OUTPUT:out }, encoding:"utf8", timeout:300000, windowsHide:false }); const manifest = path.join(out, "tactical-hierarchy-manifest.json"); if (!existsSync(manifest)) throw new Error(`R14 ${map} produced no manifest; exit=${result.status}`); return JSON.parse(readFileSync(manifest, "utf8")); }
function capture() { const runId = `run-${new Date().toISOString().replace(/[-:TZ.]/g, "").slice(0,14)}-${sourceSha().slice(0,8)}`; const dir = path.join(evidenceRoot, runId); const maps = [{ id:"hollowspan", label:"HOLLOWSPAN" }, { id:"emberfall_rift", label:"EMBERFALL_RIFT" }, { id:"ashen_vale", label:"ASHEN_VALE" }]; const manifests = withAutoload(() => maps.map(({ id, label }) => run(id, path.join(dir, label)))); const failures = []; for (const m of manifests) { if (m.source_sha !== sourceSha()) failures.push(`${m.map}:source_sha`); if (!m.pass) failures.push(...(m.failures || [`${m.map}:capture_failed`])); for (const f of m.frames || []) if (!existsSync(f.png) || readFileSync(f.png).length < 20000) failures.push(`${m.map}:image`); } const captures = manifests.flatMap((m) => (m.frames || []).map((f) => ({ ...f, sha256: sha256(f.png) }))); const summary = { schema:"ascendant-realms-p1r14-capture-v1", source_sha:sourceSha(), run_dir:runId, godot, manifests, captures, pass:failures.length === 0, failures }; writeFileSync(path.join(evidenceRoot, "p1r14-capture-manifest.json"), JSON.stringify(summary, null, 2) + "\n"); console.log(JSON.stringify(summary, null, 2)); if (failures.length) process.exitCode = 1; }
function validate() { const failures = []; const gameWorld = readFileSync(path.join(project, "scripts", "world", "game_world.gd"), "utf8"); const resource = readFileSync(path.join(project, "scripts", "world", "resource_node.gd"), "utf8"); for (const s of ["_apply_p1r14_decor_material_tone", "albedo_color.lerp(Color(0.60, 0.64, 0.56), 0.16)"]) if (!gameWorld.includes(s)) failures.push(`missing decor hierarchy contract: ${s}`); for (const s of ["_apply_p1r14_resource_readability", "_add_p1r14_resource_accent", "ResourceReadabilityAccent"]) if (!resource.includes(s)) failures.push(`missing resource hierarchy contract: ${s}`); const manifestFile = path.join(evidenceRoot, "p1r14-capture-manifest.json"); if (!existsSync(manifestFile)) failures.push("missing capture manifest"); else { const m = JSON.parse(readFileSync(manifestFile, "utf8")); if (m.source_sha !== sourceSha()) failures.push("source_sha"); if (!m.pass) failures.push(...(m.failures || ["capture_failed"])); if (new Set((m.captures || []).map((f) => f.map)).size < 3) failures.push("missing matched Hollowspan/Emberfall/Ashen captures"); } const cfg = readFileSync(path.join(project, "project.godot"), "utf8"); if (cfg.includes("P1R14Capture")) failures.push("capture autoload persisted"); const report = { schema:"ascendant-realms-p1r14-validator-v1", source_sha:sourceSha(), evidence_root:evidenceRoot, maps:["hollowspan","emberfall_rift","ashen_vale"], pass:failures.length === 0, failures }; writeFileSync(path.join(evidenceRoot, "p1r14-validator-report.json"), JSON.stringify(report, null, 2) + "\n"); console.log(JSON.stringify(report, null, 2)); if (failures.length) process.exitCode = 1; }
if ((process.argv[2] || "validate") === "capture") capture(); else validate();
