import { createHash } from "node:crypto";
import { execFileSync, spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const repo = path.resolve(import.meta.dirname, "../.."); const project = path.join(repo, "production", "ascendant-realms-godot");
const godot = process.env.ASCENDANT_REALMS_GODOT || "D:\\CodexData\\tools\\godot-4.6.3-stable\\Godot_v4.6.3-stable_win64.exe";
const evidenceRoot = process.env.P1R17_EVIDENCE_ROOT || "D:\\CodexData\\evidence\\ascendant-realms-p1-remediation-c\\p1r17"; const logsRoot = process.env.P1R17_LOG_ROOT || "D:\\CodexData\\logs\\ascendant-realms-p1-remediation-c";
mkdirSync(evidenceRoot, { recursive:true }); mkdirSync(logsRoot, { recursive:true });
const sourceSha = () => execFileSync("git", ["rev-parse", "HEAD"], { cwd:repo, encoding:"utf8" }).trim(); const sha256 = f => createHash("sha256").update(readFileSync(f)).digest("hex");
function withAutoload(fn) { const file = path.join(project,"project.godot"); const original = readFileSync(file,"utf8"); const marker='P1R17Capture="*res://tests/p1r17_ui_capture.gd"'; const patched=original.includes(marker)?original:original.replace('P1S1Capture="*res://tests/p1s1_viewport_safe_area.gd"','P1S1Capture="*res://tests/p1s1_viewport_safe_area.gd"\n'+marker); writeFileSync(file,patched); try{return fn();}finally{writeFileSync(file,original);} }
function run(width,height,out){mkdirSync(out,{recursive:true});const log=path.join(logsRoot,`p1r17-${width}x${height}.log`);const r=spawnSync(godot,["--path",project,"--resolution",`${width}x${height}`,"--windowed","--position","20,20","--log-file",log],{cwd:repo,env:{...process.env,TEMP:"D:\\CodexData\\temp",TMP:"D:\\CodexData\\temp",ASCENDANT_P1R17_SOURCE_SHA:sourceSha(),ASCENDANT_P1R17_WIDTH:String(width),ASCENDANT_P1R17_HEIGHT:String(height),ASCENDANT_P1R17_OUTPUT:out},encoding:"utf8",timeout:300000,windowsHide:false});const f=path.join(out,"ui-manifest.json");if(!existsSync(f))throw new Error(`R17 no manifest exit=${r.status}`);return JSON.parse(readFileSync(f,"utf8"));}
function capture(){const id=`run-${new Date().toISOString().replace(/[-:TZ.]/g,"").slice(0,14)}-${sourceSha().slice(0,8)}`;const dir=path.join(evidenceRoot,id);const manifests=withAutoload(()=>[run(1920,1080,path.join(dir,"1920x1080")),run(1366,768,path.join(dir,"1366x768"))]);const failures=[];for(const m of manifests){if(m.source_sha!==sourceSha())failures.push("source_sha");if(!m.pass)failures.push(...(m.failures||[]));for(const f of m.frames||[])if(!existsSync(f.png)||readFileSync(f.png).length<20000)failures.push(`${f.name}:image`);}const captures=manifests.flatMap(m=>(m.frames||[]).map(f=>({...f,sha256:sha256(f.png)})));const summary={schema:"ascendant-realms-p1r17-capture-v1",source_sha:sourceSha(),run_dir:id,godot,manifests,captures,pass:failures.length===0,failures};writeFileSync(path.join(evidenceRoot,"p1r17-capture-manifest.json"),JSON.stringify(summary,null,2)+"\n");console.log(JSON.stringify(summary,null,2));if(failures.length)process.exitCode=1;}
function validate(){const failures=[];for(const file of ["skirmish_setup.gd","hero_sheet.gd","settings.gd"]){const text=readFileSync(path.join(project,"scripts","ui",file),"utf8");if(!text.includes("PRESENTATION_THEME")||!text.includes("theme = load(PRESENTATION_THEME)"))failures.push(`${file}:shared theme missing`);}const theme=path.join(project,"assets","ui","theme.tres");if(!existsSync(theme))failures.push("theme missing");const f=path.join(evidenceRoot,"p1r17-capture-manifest.json");if(!existsSync(f))failures.push("missing capture manifest");else{const m=JSON.parse(readFileSync(f,"utf8"));if(m.source_sha!==sourceSha())failures.push("source_sha mismatch");if(!m.pass)failures.push(...(m.failures||[]));if((m.captures||[]).length<6)failures.push("insufficient menu captures");}const cfg=readFileSync(path.join(project,"project.godot"),"utf8");if(cfg.includes("P1R17Capture"))failures.push("capture autoload persisted");const report={schema:"ascendant-realms-p1r17-validator-v1",source_sha:sourceSha(),evidence_root:evidenceRoot,information_architecture_unchanged:true,pass:failures.length===0,failures};writeFileSync(path.join(evidenceRoot,"p1r17-validator-report.json"),JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify(report,null,2));if(failures.length)process.exitCode=1;}
if((process.argv[2]||"validate")==="capture")capture();else validate();
