import { createHash } from "node:crypto";
import { execFileSync, spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const repo = path.resolve(import.meta.dirname, "../..");
const project = path.join(repo, "production", "ascendant-realms-godot");
const godot = process.env.ASCENDANT_REALMS_GODOT || "D:\\CodexData\\tools\\godot-4.6.3-stable\\Godot_v4.6.3-stable_win64.exe";
const evidenceRoot = process.env.P1R13_EVIDENCE_ROOT || "D:\\CodexData\\evidence\\ascendant-realms-p1-remediation-c\\p1r13";
const logsRoot = process.env.P1R13_LOG_ROOT || "D:\\CodexData\\logs\\ascendant-realms-p1-remediation-c";
mkdirSync(evidenceRoot, { recursive: true }); mkdirSync(logsRoot, { recursive: true });
const sourceSha = () => execFileSync("git", ["rev-parse", "HEAD"], { cwd: repo, encoding: "utf8" }).trim();
const sha256 = (f) => createHash("sha256").update(readFileSync(f)).digest("hex");
function withAutoload(fn) { const f = path.join(project, "project.godot"); const original = readFileSync(f, "utf8"); const marker = 'P1R13Capture="*res://tests/p1r13_unit_readability.gd"'; const patched = original.includes(marker) ? original : original.replace('P1S1Capture="*res://tests/p1s1_viewport_safe_area.gd"', 'P1S1Capture="*res://tests/p1s1_viewport_safe_area.gd"\n' + marker); writeFileSync(f, patched); try { return fn(); } finally { writeFileSync(f, original); } }
function run(label, race, width, height, out) { mkdirSync(out, { recursive: true }); const log = path.join(logsRoot, `p1r13-${label}-${width}x${height}.log`); const result = spawnSync(godot, ["--path", project, "--resolution", `${width}x${height}`, "--windowed", "--position", "20,20", "--log-file", log], { cwd: repo, env: { ...process.env, TEMP:"D:\\CodexData\\temp", TMP:"D:\\CodexData\\temp", ASCENDANT_P1R13_SOURCE_SHA:sourceSha(), ASCENDANT_P1R13_RACE:race, ASCENDANT_P1R13_LABEL:label, ASCENDANT_P1R13_WIDTH:String(width), ASCENDANT_P1R13_HEIGHT:String(height), ASCENDANT_P1R13_OUTPUT:out }, encoding:"utf8", timeout:300000, windowsHide:false }); const mf = path.join(out, "unit-readability-manifest.json"); if (!existsSync(mf)) throw new Error(`R13 ${label} produced no manifest; exit=${result.status}`); return JSON.parse(readFileSync(mf, "utf8")); }
function capture() { const runId = `run-${new Date().toISOString().replace(/[-:TZ.]/g, "").slice(0,14)}-${sourceSha().slice(0,8)}`; const dir = path.join(evidenceRoot, runId); const jobs = [["LIORAEN_DEFAULT","lioraen",1920,1080],["BARROSAN_DEFAULT","barrosan",1920,1080],["VORTHAK_DEFAULT","vorthak",1920,1080],["LIORAEN_1366_DEFAULT","lioraen",1366,768]]; const manifests = withAutoload(() => jobs.map(([label,race,w,h]) => run(label,race,w,h,path.join(dir,label)))); const failures = []; for (const m of manifests) { if (m.source_sha !== sourceSha()) failures.push(`${m.race}:source_sha`); if (!m.pass) failures.push(...(m.failures||[])); for (const f of m.frames||[]) { if (!existsSync(f.png) || readFileSync(f.png).length < 20000) failures.push(`${f.name}:image`); } } const captures = manifests.flatMap(m => (m.frames||[]).map(f=>({name:f.name,png:f.png,sha256:sha256(f.png),width:f.width,height:f.height,measurements:f.measurements}))); const summary={schema:"ascendant-realms-p1r13-capture-v1",source_sha:sourceSha(),run_dir:runId,godot,manifests,captures,pass:failures.length===0,failures}; writeFileSync(path.join(evidenceRoot,"p1r13-capture-manifest.json"),JSON.stringify(summary,null,2)+"\n"); console.log(JSON.stringify(summary,null,2)); if (failures.length) process.exitCode=1; }
function validate() { const failures=[]; const f=path.join(evidenceRoot,"p1r13-capture-manifest.json"); const unit=readFileSync(path.join(project,"scripts","units","unit.gd"),"utf8"); for (const s of ["P1R13_WORKER_VISUAL_EMPHASIS","P1R13_MILITARY_VISUAL_EMPHASIS","P1R13_HERO_VISUAL_EMPHASIS","_team_marker.position.y = _visual_height + 0.19"]) if (!unit.includes(s)) failures.push(`missing ${s}`); if (!existsSync(f)) failures.push("missing capture manifest"); else { const m=JSON.parse(readFileSync(f,"utf8")); if(m.source_sha!==sourceSha()) failures.push("source_sha"); if(!m.pass) failures.push(...(m.failures||[])); if((m.captures||[]).length<5) failures.push("insufficient captures"); } const cfg=readFileSync(path.join(project,"project.godot"),"utf8"); if(cfg.includes("P1R13Capture")) failures.push("capture autoload persisted"); const report={schema:"ascendant-realms-p1r13-validator-v1",source_sha:sourceSha(),evidence_root:evidenceRoot,pass:failures.length===0,failures}; writeFileSync(path.join(evidenceRoot,"p1r13-validator-report.json"),JSON.stringify(report,null,2)+"\n"); console.log(JSON.stringify(report,null,2)); if(failures.length) process.exitCode=1; }
if ((process.argv[2]||"validate") === "capture") capture(); else validate();
