import { createHash } from "node:crypto";
import { execFileSync, spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
const repo=path.resolve(import.meta.dirname,"../.."),project=path.join(repo,"production","ascendant-realms-godot");const godot=process.env.ASCENDANT_REALMS_GODOT||"D:\\CodexData\\tools\\godot-4.6.3-stable\\Godot_v4.6.3-stable_win64.exe";const evidenceRoot=process.env.P1R23_EVIDENCE_ROOT||"D:\\CodexData\\evidence\\ascendant-realms-p1-remediation-d\\p1r23";const logsRoot=process.env.P1R23_LOG_ROOT||"D:\\CodexData\\logs\\ascendant-realms-p1-remediation-d";mkdirSync(evidenceRoot,{recursive:true});mkdirSync(logsRoot,{recursive:true});const sourceSha=()=>execFileSync("git",["rev-parse","HEAD"],{cwd:repo,encoding:"utf8"}).trim();const sha256=f=>createHash("sha256").update(readFileSync(f)).digest("hex");
function withAutoload(fn){const f=path.join(project,"project.godot"),o=readFileSync(f,"utf8"),m='P1R23Capture="*res://tests/p1r23_selected_group.gd"',p=o.includes(m)?o:o.replace('P1S1Capture="*res://tests/p1s1_viewport_safe_area.gd"','P1S1Capture="*res://tests/p1s1_viewport_safe_area.gd"\n'+m);writeFileSync(f,p);try{return fn()}finally{writeFileSync(f,o)}}
function run(name,view,w,h,out){mkdirSync(out,{recursive:true});const log=path.join(logsRoot,`p1r23-${name}.log`),r=spawnSync(godot,["--path",project,"--resolution",`${w}x${h}`,"--windowed","--position","20,20","--log-file",log],{cwd:repo,env:{...process.env,TEMP:"D:\\CodexData\\temp",TMP:"D:\\CodexData\\temp",ASCENDANT_P1R23_SOURCE_SHA:sourceSha(),ASCENDANT_P1R23_NAME:name,ASCENDANT_P1R23_VIEW:view,ASCENDANT_P1R23_WIDTH:String(w),ASCENDANT_P1R23_HEIGHT:String(h),ASCENDANT_P1R23_OUTPUT:out},encoding:"utf8",timeout:300000,windowsHide:false});const f=path.join(out,"selected-group-manifest.json");if(!existsSync(f))throw new Error(`R23 ${name} produced no manifest; exit=${r.status}`);return JSON.parse(readFileSync(f,"utf8"))}
function capture(){const id=`run-${new Date().toISOString().replace(/[-:TZ.]/g,"").slice(0,14)}-${sourceSha().slice(0,8)}`,dir=path.join(evidenceRoot,id),jobs=[["01_R23_MULTI_LIORAEN","mixed",1920,1080],["02_R23_MIXED_GROUP","mixed",1920,1080],["03_R23_HERO_IN_GROUP","mixed",1920,1080],["04_R23_LARGE_GROUP","large",1920,1080],["05_R23_1366_GROUP","large",1366,768]],ms=withAutoload(()=>jobs.map(([n,v,w,h])=>run(n,v,w,h,path.join(dir,n))),),fail=[];for(const m of ms){if(m.source_sha!==sourceSha())fail.push(`${m.view}:source_sha`);if(!m.pass)fail.push(...(m.failures||["capture_failed"]));for(const f of m.frames||[])if(!existsSync(f.png)||readFileSync(f.png).length<20000)fail.push(`${m.view}:image`)}const captures=ms.flatMap(m=>(m.frames||[]).map(f=>({...f,sha256:sha256(f.png)}))),s={schema:"ascendant-realms-p1r23-capture-v1",source_sha:sourceSha(),run_dir:id,godot,jobs,manifests:ms,captures,pass:!fail.length,failures:fail};writeFileSync(path.join(evidenceRoot,"p1r23-capture-manifest.json"),JSON.stringify(s,null,2)+"\n");console.log(JSON.stringify(s,null,2));if(fail.length)process.exitCode=1}
function validate(){const fail=[],hud=readFileSync(path.join(project,"scripts","ui","hud.gd"),"utf8");for(const x of ["Selected group","_mk_icon","configure_entity","is_hero","grid.columns = 6"])if(!hud.includes(x))fail.push(`missing R23 contract: ${x}`);const f=path.join(evidenceRoot,"p1r23-capture-manifest.json");if(!existsSync(f))fail.push("missing capture manifest");else{const m=JSON.parse(readFileSync(f,"utf8"));if(m.source_sha!==sourceSha())fail.push("source_sha");if(!m.pass)fail.push(...(m.failures||["capture_failed"]));for(const n of ["01_R23_MULTI_LIORAEN","02_R23_MIXED_GROUP","03_R23_HERO_IN_GROUP","04_R23_LARGE_GROUP","05_R23_1366_GROUP"])if(!(m.captures||[]).some(x=>x.name===n))fail.push(`missing ${n}`);for(const f of(m.captures||[]))if(f.selected_count<2||f.selected_ids.length!==f.selected_count)fail.push(`${f.name}:selection_truth`)}const cfg=readFileSync(path.join(project,"project.godot"),"utf8");if(cfg.includes("P1R23Capture"))fail.push("capture autoload persisted");const out={schema:"ascendant-realms-p1r23-validator-v1",source_sha:sourceSha(),evidence_root:evidenceRoot,pass:!fail.length,failures:fail};writeFileSync(path.join(evidenceRoot,"p1r23-validator-report.json"),JSON.stringify(out,null,2)+"\n");console.log(JSON.stringify(out,null,2));if(fail.length)process.exitCode=1}
if((process.argv[2]||"validate")==="capture")capture();else validate();
