import { createHash } from "node:crypto";
import { execFileSync, spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
const repo=path.resolve(import.meta.dirname,"../.."), project=path.join(repo,"production","ascendant-realms-godot");
const godot=process.env.ASCENDANT_REALMS_GODOT||"D:\\CodexData\\tools\\godot-4.6.3-stable\\Godot_v4.6.3-stable_win64.exe", evidenceRoot=process.env.P1R22_EVIDENCE_ROOT||"D:\\CodexData\\evidence\\ascendant-realms-p1-remediation-d\\p1r22", logsRoot=process.env.P1R22_LOG_ROOT||"D:\\CodexData\\logs\\ascendant-realms-p1-remediation-d";
mkdirSync(evidenceRoot,{recursive:true}); mkdirSync(logsRoot,{recursive:true}); const sourceSha=()=>execFileSync("git",["rev-parse","HEAD"],{cwd:repo,encoding:"utf8"}).trim(); const sha256=f=>createHash("sha256").update(readFileSync(f)).digest("hex");
function withAutoload(fn){const f=path.join(project,"project.godot"),o=readFileSync(f,"utf8"),m='P1R22Capture="*res://tests/p1r22_command_card.gd"',p=o.includes(m)?o:o.replace('P1S1Capture="*res://tests/p1s1_viewport_safe_area.gd"','P1S1Capture="*res://tests/p1s1_viewport_safe_area.gd"\n'+m);writeFileSync(f,p);try{return fn()}finally{writeFileSync(f,o)}}
function run(name,view,width,height,out){mkdirSync(out,{recursive:true});const log=path.join(logsRoot,`p1r22-${name}.log`),r=spawnSync(godot,["--path",project,"--resolution",`${width}x${height}`,"--windowed","--position","20,20","--log-file",log],{cwd:repo,env:{...process.env,TEMP:"D:\\CodexData\\temp",TMP:"D:\\CodexData\\temp",ASCENDANT_P1R22_SOURCE_SHA:sourceSha(),ASCENDANT_P1R22_NAME:name,ASCENDANT_P1R22_VIEW:view,ASCENDANT_P1R22_WIDTH:String(width),ASCENDANT_P1R22_HEIGHT:String(height),ASCENDANT_P1R22_OUTPUT:out},encoding:"utf8",timeout:300000,windowsHide:false});const f=path.join(out,"command-card-manifest.json");if(!existsSync(f))throw new Error(`R22 ${name} produced no manifest; exit=${r.status}`);return JSON.parse(readFileSync(f,"utf8"))}
function capture(){const id=`run-${new Date().toISOString().replace(/[-:TZ.]/g,"").slice(0,14)}-${sourceSha().slice(0,8)}`,dir=path.join(evidenceRoot,id),jobs=[["01_R22_WORKER_BUILD_CARD","worker",1920,1080],["02_R22_HQ_CARD","hq",1920,1080],["03_R22_PRODUCTION_BUILDING","production",1920,1080],["04_R22_RESEARCH","research",1920,1080],["05_R22_DISABLED_STATES","disabled",1920,1080],["06_R22_1366_BUILD_CARD","worker",1366,768],["07_R22_1366_TRAIN_CARD","production",1366,768],["08_R22_BUILD_PLACEMENT","placement",1920,1080]],ms=withAutoload(()=>jobs.map(([n,v,w,h])=>run(n,v,w,h,path.join(dir,n))),),fail=[];for(const m of ms){if(m.source_sha!==sourceSha())fail.push(`${m.view}:source_sha`);if(!m.pass)fail.push(...(m.failures||["capture_failed"]));for(const f of m.frames||[])if(!existsSync(f.png)||readFileSync(f.png).length<20000)fail.push(`${m.view}:image`)}const captures=ms.flatMap(m=>(m.frames||[]).map(f=>({...f,sha256:sha256(f.png)}))),s={schema:"ascendant-realms-p1r22-capture-v1",source_sha:sourceSha(),run_dir:id,godot,jobs,manifests:ms,captures,pass:!fail.length,failures:fail};writeFileSync(path.join(evidenceRoot,"p1r22-capture-manifest.json"),JSON.stringify(s,null,2)+"\n");console.log(JSON.stringify(s,null,2));if(fail.length)process.exitCode=1}
function validate(){const fail=[],hud=readFileSync(path.join(project,"scripts","ui","hud.gd"),"utf8");for(const x of ["_mk_command_button","_mk_command_grid","Unavailable:","Tier %d | Cost:","Research"] )if(!hud.includes(x))fail.push(`missing R22 contract: ${x}`);const f=path.join(evidenceRoot,"p1r22-capture-manifest.json");if(!existsSync(f))fail.push("missing capture manifest");else{const m=JSON.parse(readFileSync(f,"utf8"));if(m.source_sha!==sourceSha())fail.push("source_sha");if(!m.pass)fail.push(...(m.failures||["capture_failed"]));for(const n of ["01_R22_WORKER_BUILD_CARD","02_R22_HQ_CARD","03_R22_PRODUCTION_BUILDING","04_R22_RESEARCH","05_R22_DISABLED_STATES","06_R22_1366_BUILD_CARD","07_R22_1366_TRAIN_CARD","08_R22_BUILD_PLACEMENT"])if(!(m.captures||[]).some(x=>x.name===n))fail.push(`missing ${n}`)}const cfg=readFileSync(path.join(project,"project.godot"),"utf8");if(cfg.includes("P1R22Capture"))fail.push("capture autoload persisted");const out={schema:"ascendant-realms-p1r22-validator-v1",source_sha:sourceSha(),evidence_root:evidenceRoot,pass:!fail.length,failures:fail};writeFileSync(path.join(evidenceRoot,"p1r22-validator-report.json"),JSON.stringify(out,null,2)+"\n");console.log(JSON.stringify(out,null,2));if(fail.length)process.exitCode=1}
if((process.argv[2]||"validate")==="capture")capture();else validate();
