import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const root=process.cwd(); const failures=[]; const abs=p=>path.join(root,p); const exists=p=>fs.existsSync(abs(p)); const check=(v,m)=>{if(!v) failures.push(m)}; const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(abs(p))).digest('hex');
const readStrict=p=>{const bytes=fs.readFileSync(abs(p)); let text; try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes)}catch{failures.push(`strict UTF-8 decode failed: ${p}`); return ''} return text};
const parseJson=p=>JSON.parse(readStrict(p).replace(/^\uFEFF/u,''));
const scene='desktop-spikes/godot-salto/scenes/gold/barrosan/BarrosanBarnGold.tscn'; const source='artifacts/runtime/v0355/screenshots/04_canonical_barn_square_256.png'; const sceneHash='ffaf4c4eeb7c0dabc3a483b0137ad2d92d2b2f6dd496b84b86584ae4a7e86a4a'; const sourceHash='13a761a2b60658a0d261c89d9046b752f052a5e32924381075a4b24ca7c3d6a3'; const roofHash='0077e19143517e2850aee3bdb6ce9408d55bc7e2bfdc958d61ac1b141ab684f9';
const pack='artifacts/manual-review/v0361-barrosan-barn-aggregate-metric-utf8-truth-closeout/UPLOAD_TO_CHAT'; const sourcePack='artifacts/manual-review/v0360-barrosan-barn-evidence-pack-truth-closeout/UPLOAD_TO_CHAT'; const summaryPath=`${pack}/compact-evidence-summary.json`; const oldPath='artifacts/manual-review/v0358-barrosan-barn-opt-in-isolation-evidence-repair/UPLOAD_TO_CHAT/compact-evidence-summary.json'; const perfPath='artifacts/performance/v0359-barrosan-barn/v0359-performance.json'; const loadPath='artifacts/runtime/v0358/performance/v0358-performance.json'; const reportPath='docs/V0361_BARROSAN_BARN_AGGREGATE_METRIC_UTF8_TRUTH_CLOSEOUT_REPORT.md';
const expected=['00_READ_ME_FIRST.md','01_HUMAN_DECISION_AND_SINGLE_SLOT_AUTHORITY.png','02_EXACT_SINGLE_SLOT_DEFAULT_VS_OPT_IN.png','03_HOUSE02_BARN_WORKER_SCALE_AND_CONTEXT.png','04_RTS_DISTANCE_AND_TERRAIN_CONTACT.png','05_FRONT_REAR_AND_EXTERIOR_ROOF.png','06_FOUR_FAIL_CLOSED_STATES.png','07_EXACT_ROLLBACK_AND_DEFAULT_PRESERVATION.png','08_UNCAPPED_PERFORMANCE_RESOURCE_AND_NODE_LEDGER.png','compact-evidence-summary.json'];
check(process.argv[2]==='validate','usage: node tools/godot/saltoV0361BarrosanBarnAggregateMetricUtf8TruthCloseoutTool.mjs validate'); for(const p of [scene,source,oldPath,perfPath,loadPath,pack,sourcePack,reportPath,'tools/godot/buildV0361BarrosanBarnAggregateMetricUtf8TruthCloseoutPack.ps1']) check(exists(p),`missing ${p}`);
const badKey=/^(?:raw(?:DrawCalls|FrameTimesMs|TriangleOrPrimitiveCounts?)|perFrame(?:DrawCalls|FrameTimesMs|TriangleOrPrimitiveCounts?)|frameSamples|samples)$/i;
const scanValue=(value,where,out)=>{if(Array.isArray(value)){for(const v of value)scanValue(v,where,out);return} if(value&&typeof value==='object'){for(const [k,v] of Object.entries(value)){if(badKey.test(k))out.rawKeys.push(`${where}.${k}`);scanValue(v,`${where}.${k}`,out)}}};
const scanText=text=>{let moj=0,control=0,replacement=0,bom=0; for(const ch of text){const n=ch.codePointAt(0); if(n===0xc3||n===0xc2||n===0xe2)moj++; if((n<32&&!['\t','\n','\r'].includes(ch))||n===0x7f)control++; if(n===0xfffd)replacement++; if(n===0xfeff)bom++} return {moj,control,replacement,bom}};
const nearly=(a,b,t=1e-9)=>Number.isFinite(Number(a))&&Math.abs(Number(a)-Number(b))<=t;
if(!failures.length){
 const s=parseJson(summaryPath), old=parseJson(oldPath), p=parseJson(perfPath), load=parseJson(loadPath); const names=fs.readdirSync(abs(pack)); const sourceNames=fs.readdirSync(abs(sourcePack));
 check(names.length===10&&expected.every(f=>names.includes(f)),'exact ten-file pack contract'); check(names.filter(f=>f.toLowerCase().endsWith('.png')).length===8,'exactly eight PNGs'); check(!names.some(f=>/\.(mp4|webm|mov|csv)$/i.test(f)),'video/CSV present'); check(!names.some(f=>f.endsWith('.json')&&f!=='compact-evidence-summary.json'),'raw JSON present');
 for(const f of expected.filter(x=>x.endsWith('.png'))){check(sha(`${pack}/${f}`)===sha(`${sourcePack}/${f}`),`accepted v0.360 board changed: ${f}`); const b=fs.readFileSync(abs(`${pack}/${f}`)); check(b.readUInt32BE(0)===0x89504e47&&b.readUInt32BE(16)===1600&&b.readUInt32BE(20)===900,`invalid 1600x900 board: ${f}`)}
 check(sha(scene)===sceneHash,'canonical scene hash changed'); check(sha(source)===sourceHash,'canonical source hash changed'); check(s.requiredRoofHash===roofHash&&s.observedRoofHash===roofHash&&s.roofHashMatch===true,'roof authority changed');
 check(Array.isArray(p.default.rawFrameTimesMs)&&p.default.rawFrameTimesMs.length===3600,'default raw sample count'); check(Array.isArray(p.optIn.rawFrameTimesMs)&&p.optIn.rawFrameTimesMs.length===3600,'opt-in raw sample count'); check(s.rawArraysInsidePack===0&&s.rawBenchmarkDataFilesInsidePack===0&&s.noRawBenchmarkDataInPack===true,'raw arrays inside pack');
 const d=p.default,o=p.optIn; const derived={performanceSampleCountDefault:d.sample_count,performanceSampleCountOptIn:o.sample_count,defaultMedianFps:d.median_fps,optInMedianFps:o.median_fps,medianFpsRatio:p.medianFpsRatio,defaultOnePercentLowFps:d.one_percent_low_fps,optInOnePercentLowFps:o.one_percent_low_fps,defaultMedianFrameTimeMs:d.median_frame_time_ms,optInMedianFrameTimeMs:o.median_frame_time_ms,defaultP95FrameTimeMs:d.p95_frame_time_ms,optInP95FrameTimeMs:o.p95_frame_time_ms,p95FrameTimeRatio:p.p95FrameTimeRatio,defaultP99FrameTimeMs:d.p99_frame_time_ms,optInP99FrameTimeMs:o.p99_frame_time_ms,defaultMaximumFrameTimeMs:d.max_frame_time_ms,optInMaximumFrameTimeMs:o.max_frame_time_ms,defaultOver50MsSpikeCount:d.over_50_ms_spike_count,optInOver50MsSpikeCount:o.over_50_ms_spike_count,defaultDrawCalls:d.draw_calls,optInDrawCalls:o.draw_calls,drawCallDelta:o.draw_calls-d.draw_calls,defaultTriangleOrPrimitiveCount:d.triangle_or_primitive_count,optInTriangleOrPrimitiveCount:o.triangle_or_primitive_count,primitiveDelta:o.triangle_or_primitive_count-d.triangle_or_primitive_count,defaultLoadedResourceCount:d.loaded_resource_count,optInLoadedResourceCount:o.loaded_resource_count,resourceDelta:o.loaded_resource_count-d.loaded_resource_count,defaultTotalNodeCount:d.total_node_count,optInTotalNodeCount:o.total_node_count,nodeDelta:o.total_node_count-d.total_node_count};
 for(const [k,v] of Object.entries(derived))check(nearly(s[k],v),'aggregate mismatch: '+k); check(s.performanceAggregateSourcePath==='artifacts/performance/v0359-barrosan-barn/v0359-performance.json','aggregate source path'); check(s.performanceAggregatesRecomputed===true&&s.performanceAggregateMismatchCount===0&&s.staleCappedMetricCountAfterRepair===0,'aggregate provenance'); check(s.board08AggregateMatch===true&&s.compactSummaryAggregateMatch===true&&s.reportAggregateMatch===true,'cross-file aggregate flags');
 const stale={defaultOnePercentLowFps:72.8228845017675,optInOnePercentLowFps:72.7285704510637,defaultMedianFrameTimeMs:13.333,optInMedianFrameTimeMs:13.332,defaultP99FrameTimeMs:13.489,optInP99FrameTimeMs:13.541}; for(const [k,v] of Object.entries(stale))check(!nearly(s[k],v),'stale capped value remains in '+k); check(s.defaultMedianFrameTimeMs!==13.333&&s.optInMedianFrameTimeMs!==13.332,'capped median frame values remain');
 check(s.retainedV0358TopLevelKeyCount===82&&s.missingRetainedV0358FieldCount===0,'retained key count'); for(const k of Object.keys(old))check(Object.prototype.hasOwnProperty.call(s,k),`missing retained key ${k}`); check(Array.isArray(s.retainedKeyCoverage)&&s.retainedKeyCoverage.length===82,'key/value distinction missing'); check(s.retainedKeyCoverage.some(x=>x.key==='defaultOnePercentLowFps'&&x.preserved===true&&x.valueCopiedUnchanged===false),'stale value was copied unchanged');
 const summaryScan={rawKeys:[]}; scanValue(s,'summary',summaryScan); check(summaryScan.rawKeys.length===0,'raw array key in compact summary');
 const textFiles=[`${pack}/00_READ_ME_FIRST.md`,summaryPath,reportPath]; let totals={moj:0,control:0,replacement:0,bom:0}; for(const f of textFiles){const scan=scanText(readStrict(f)); totals.moj+=scan.moj; totals.control+=scan.control; totals.replacement+=scan.replacement; totals.bom+=scan.bom} for(const f of names) {const scan=scanText(f);totals.moj+=scan.moj;totals.control+=scan.control;totals.replacement+=scan.replacement;totals.bom+=scan.bom} check(totals.moj===0&&totals.control===0&&totals.replacement===0&&totals.bom===0,`UTF-8 truth counts mojibake=${totals.moj} control=${totals.control} replacement=${totals.replacement} bom=${totals.bom}`); check(s.utf8Valid===true&&s.mojibakeCount===0&&s.controlCharacterCount===0&&s.replacementCharacterCount===0&&s.bomLeakCount===0,'UTF-8 summary flags');
 const report=readStrict(reportPath); const begin='<!-- V0361_AGGREGATES_BEGIN -->',end='<!-- V0361_AGGREGATES_END -->'; check(report.includes(begin)&&report.includes(end),'report aggregate block missing'); let reportAgg={}; try{reportAgg=JSON.parse(report.split(begin)[1].split(end)[0])}catch{failures.push('report aggregate block is not JSON')}; for(const [k,v] of Object.entries(derived))check(nearly(reportAgg[k],v),'report aggregate mismatch: '+k); check(s.reportAggregateMatch===true,'report aggregate flag'); check(nearly(s.barnSceneLoadTimeMs,load.barnSceneLoadTimeMs)&&s.retainedBarnNodeCount===0,'load/rollback evidence');
 for(const k of ['canonicalAssetMutationCount','geometryMutationCount','materialMutationCount','textureMutationCount','canonicalTransformMutationCount','gameplayMutationCount','defaultRuntimeMutationCount','browserMutationCount','saveMutationCount','stableIdMutationCount','captureMutationCount','benchmarkRerunCount'])check(s[k]===0,'mutation count '+k); check(s.optInOnly===true&&s.defaultRuntimeIntegrated===false&&s.productionIntegrated===false&&s.gameplayIntegrated===false&&s.browserIntegrated===false,'runtime isolation');
 check(s.compactSummaryByteSize===fs.statSync(abs(summaryPath)).size,'summary byte metadata'); check(Buffer.byteLength(fs.readFileSync(abs(summaryPath)))<100000,'summary under 100KB');
 const negative=[]; const mustFail=(label,condition)=>{if(condition)negative.push(label)}; const badStale={...s,defaultOnePercentLowFps:stale.defaultOnePercentLowFps}; mustFail('stale aggregate negative test',nearly(badStale.defaultOnePercentLowFps,derived.defaultOnePercentLowFps)); mustFail('mojibake negative test',scanText('x\u00e2\u20ac\u009d').moj===0); mustFail('control negative test',scanText('x\u0007').control===0); mustFail('replacement negative test',scanText('x\ufffd').replacement===0); mustFail('Board 08 mismatch negative test',s.board08SourceSha256==='not-the-accepted-board'); const missing={...s}; delete missing.requiredSourceHash; mustFail('retained-key negative test',Object.prototype.hasOwnProperty.call(missing,'requiredSourceHash')); const raw={...s,rawFrameTimesMs:[1]}; const rawTest={rawKeys:[]}; scanValue(raw,'negative',rawTest); mustFail('raw-array negative test',rawTest.rawKeys.length===0); check(negative.length===0,'negative tests not enforced: '+negative.join(', '));
}
if(failures.length){console.error('FAIL_V0361_BARROSAN_BARN_AGGREGATE_UTF8_TRUTH_CLOSEOUT\n- '+failures.join('\n- '));process.exit(1)} console.log('PASS_V0361_BARROSAN_BARN_AGGREGATE_UTF8_TRUTH_CLOSEOUT');
