import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const root=process.cwd(); const failures=[]; const abs=p=>path.join(root,p); const exists=p=>fs.existsSync(abs(p)); const read=p=>fs.readFileSync(abs(p),'utf8').replace(/^\uFEFF/u,''); const json=p=>JSON.parse(read(p)); const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(abs(p))).digest('hex'); const check=(v,m)=>{if(!v) failures.push(m)};
const scene='desktop-spikes/godot-salto/scenes/gold/barrosan/BarrosanBarnGold.tscn'; const source='artifacts/runtime/v0355/screenshots/04_canonical_barn_square_256.png'; const sceneHash='ffaf4c4eeb7c0dabc3a483b0137ad2d92d2b2f6dd496b84b86584ae4a7e86a4a'; const sourceHash='13a761a2b60658a0d261c89d9046b752f052a5e32924381075a4b24ca7c3d6a3'; const roofHash='0077e19143517e2850aee3bdb6ce9408d55bc7e2bfdc958d61ac1b141ab684f9';
const pack='artifacts/manual-review/v0360-barrosan-barn-evidence-pack-truth-closeout/UPLOAD_TO_CHAT'; const summaryPath=`${pack}/compact-evidence-summary.json`; const oldPath='artifacts/manual-review/v0358-barrosan-barn-opt-in-isolation-evidence-repair/UPLOAD_TO_CHAT/compact-evidence-summary.json'; const perfPath='artifacts/performance/v0359-barrosan-barn/v0359-performance.json'; const loadPath='artifacts/runtime/v0358/performance/v0358-performance.json'; const manifestPath='artifacts/runtime/v0359/capture-manifest.json';
const files=['00_READ_ME_FIRST.md','01_HUMAN_DECISION_AND_SINGLE_SLOT_AUTHORITY.png','02_EXACT_SINGLE_SLOT_DEFAULT_VS_OPT_IN.png','03_HOUSE02_BARN_WORKER_SCALE_AND_CONTEXT.png','04_RTS_DISTANCE_AND_TERRAIN_CONTACT.png','05_FRONT_REAR_AND_EXTERIOR_ROOF.png','06_FOUR_FAIL_CLOSED_STATES.png','07_EXACT_ROLLBACK_AND_DEFAULT_PRESERVATION.png','08_UNCAPPED_PERFORMANCE_RESOURCE_AND_NODE_LEDGER.png','compact-evidence-summary.json'];
check(process.argv[2]==='validate','usage: node tools/godot/saltoV0360BarrosanBarnEvidencePackTruthCloseoutTool.mjs validate'); for(const p of [scene,source,oldPath,perfPath,loadPath,manifestPath,pack,'docs/V0360_BARROSAN_BARN_EVIDENCE_PACK_TRUTH_CLOSEOUT_REPORT.md','tools/godot/buildV0360BarrosanBarnEvidencePackTruthCloseoutPack.ps1']) check(exists(p),`missing ${p}`);
if(!failures.length){
 const s=json(summaryPath), old=json(oldPath), p=json(perfPath), lp=json(loadPath), m=json(manifestPath), names=fs.readdirSync(abs(pack));
 check(names.length===10,`pack must contain exactly 10 files, found ${names.length}`); check(files.every(f=>names.includes(f)),'pack inventory mismatch'); check(names.filter(f=>f.toLowerCase().endsWith('.png')).length===8,'pack must contain exactly 8 PNG files'); check(!names.some(f=>/\.(json|csv|mp4|webm|mov)$/i.test(f)&&f!=='compact-evidence-summary.json'),'raw data/video file found in pack');
 check(s.checkpoint==='v0.360','summary checkpoint'); check(s.retainedV0358TopLevelKeyCount===82,'retained v0.358 key count'); check(s.missingRetainedV0358FieldCount===0,'retained v0.358 fields missing'); for(const key of Object.keys(old)) check(Object.prototype.hasOwnProperty.call(s,key),`missing retained field ${key}`);
 const rawKey=/^(?:raw(?:DrawCalls|FrameTimesMs|TriangleOrPrimitiveCounts?)|perFrame(?:DrawCalls|FrameTimesMs|TriangleOrPrimitiveCounts?)|frameSamples|samples)$/i; const scan=(v,where)=>{if(Array.isArray(v)){for(const x of v)scan(x,where);return} if(v&&typeof v==='object'){for(const [k,x] of Object.entries(v)){check(!rawKey.test(k),`raw benchmark key in compact summary: ${where}.${k}`);scan(x,`${where}.${k}`)}}}; scan(s,'summary'); check(s.rawArraysInsidePack===0&&s.rawBenchmarkDataFilesInsidePack===0,'raw benchmark data inside pack'); check(s.noRawBenchmarkDataInPack===true,'noRawBenchmarkDataInPack false'); check(Buffer.byteLength(fs.readFileSync(abs(summaryPath)),'utf8')<100000,'compact summary is not under 100KB'); check(s.rawBenchmarkArrayKeyCount===6&&s.rawBenchmarkEntryCount===21600,'raw-array reconciliation missing');
 for(const f of files.filter(x=>x.endsWith('.png'))){const b=fs.readFileSync(abs(`${pack}/${f}`)); check(b.length>10000,`blank or tiny PNG ${f}`); check(b.readUInt32BE(0)===0x89504e47,'invalid PNG signature'); check(b.readUInt32BE(16)===1600&&b.readUInt32BE(20)===900,`PNG ${f} must be 1600x900`)}
 const readme=read(`${pack}/00_READ_ME_FIRST.md`); check(readme.includes('BLACK-FRAME REJECTION REPORT'),'black-frame rejection report missing'); check(s.board06Layout==='2x2'&&s.board06ScenarioHeadingFontPx>=27&&s.board06BodyFontPx>=18&&s.board06DiagnosticsReadable,'Board 06 readability contract'); check(s.board08BarnLoadTimeSeparate===true&&s.board08RequiredRows.includes('Barn scene load time')&&s.board08RequiredRows.includes('Barn load-time validity'),'Board 08 load-time separation'); check(Math.abs(Number(s.barnSceneLoadTimeMs)-376.718)<0.001&&s.barnSceneLoadTimeMeasurementValid===true,'Barn load time evidence'); check(String(s.barnSceneLoadTimeProtocol).includes('Time.get_ticks_usec'),'load-time protocol');
 const failCodes=['MISSING_SCENE_FAIL_CLOSED','HASH_MISMATCH_FAIL_CLOSED','INVALID_AUTHORITY_FAIL_CLOSED','UNKNOWN_SLOT_REJECTED']; check(Array.isArray(s.failClosedScenarios)&&s.failClosedScenarios.length===4,'four fail-closed cards missing'); for(const [i,c] of (s.failClosedScenarios||[]).entries()){check(c.loadAttempted===true,`fail card ${i+1} loadAttempted`); check(c.loadSucceeded===false&&c.barnInstanceCount===0&&c.fallbackAssetUsed===false&&c.runtimeContinued===true,`fail card ${i+1} contract`); check(c.failureCode===failCodes[i],`fail card ${i+1} code`)}
 check(sha(scene)===sceneHash,'canonical scene hash changed'); check(sha(source)===sourceHash,'accepted source hash changed'); check(s.requiredRoofHash===roofHash&&s.observedRoofHash===roofHash&&s.roofHashMatch===true,'roof authority evidence'); check(s.optInOnly===true&&s.defaultRuntimeIntegrated===false&&s.productionIntegrated===false&&s.gameplayIntegrated===false&&s.browserIntegrated===false,'opt-in/default contract'); for(const k of ['canonicalAssetMutationCount','geometryMutationCount','materialMutationCount','textureMutationCount','canonicalTransformMutationCount','gameplayMutationCount','defaultRuntimeMutationCount','stableIdMutationCount','saveMutationCount']) check(s[k]===0,`mutation count ${k}`); check(s.utf8Valid===true&&s.mojibakeCount===0,'UTF-8 evidence'); check(s.automatedVisualApproval===false&&s.humanReviewStop===true,'human review stop');
 check(Math.abs(Number(s.medianFpsRatio)-0.992743105950653)<1e-9,'median ratio'); check(Math.abs(Number(s.p95FrameTimeRatio)-1.06136900078678)<1e-9,'p95 ratio'); check(s.retainedBarnNodeCount===0,'retained Barn node count'); check(s.board03PanelsDistinct&&s.board04PanelsDistinct&&s.board05AllViewsDistinct&&s.board07R0R2PixelMatch&&s.board06PanelHashesDistinct,'accepted distinct/hash evidence');
 const panelById=new Map(m.panels.map(x=>[x.boardPanelId,x])); for(const id of ['wide_wide','close-scale_close_scale','rts-distance_rts_distance','terrain-contact_terrain_contact','front_front','rear_rear','roof_roof','rollback_r0','rollback_r1','rollback_r2']) check(panelById.has(id),`manifest panel ${id}`); check(s.compactSummaryByteSize===fs.statSync(abs(summaryPath)).size||Math.abs(Number(s.compactSummaryByteSize)-fs.statSync(abs(summaryPath)).size)<20,'summary byte size metadata');
 const test={...s,rawFrameTimesMs:[1]}; let injected=false; const reject=(v)=>{if(v&&typeof v==='object'){for(const [k,x] of Object.entries(v)){if(rawKey.test(k))return true;if(reject(x))return true}}return false}; injected=reject(test); check(injected,'validator self-test failed to detect injected raw array');
}
if(failures.length){console.error(`FAIL_V0360_BARROSAN_BARN_EVIDENCE_PACK_TRUTH_CLOSEOUT\n- ${failures.join('\n- ')}`);process.exit(1)} console.log('PASS_V0360_BARROSAN_BARN_EVIDENCE_PACK_TRUTH_CLOSEOUT');
