import{existsSync,readFileSync,readdirSync,writeFileSync}from'node:fs';
import{join,resolve}from'node:path';
const repo=resolve('.'),root=join(repo,'artifacts/desktop-spikes/godot-salto/v0300/world-marker-declutter-readability-repair-runtime'),manual=join(repo,'artifacts/manual-review/v0300-barrosan-world-marker-declutter-readability-repair'),errors=[],manifestPath=join(root,'screenshot-runtime-manifest.json');
const actions=['v0300_bridge_cluster_decluttered','v0300_route_preview_readable','v0300_deploy_authorized_readable','v0300_support_deployed_readable','v0300_line_reinforced_readable','v0300_pressure_stabilized_readable','v0300_barracks_reserve_cluster_decluttered','v0300_route_five_segments','v0300_integration_visual_static','v0300_support_presence_once','v0300_pressure_display','v0300_defender_card','v0300_support_card','v0300_barracks_card'];
if(!existsSync(manifestPath))errors.push('missing v0.300 manifest');
else{const m=JSON.parse(readFileSync(manifestPath));if(m.captureCount!==16)errors.push('capture incomplete');const runtimeErrors=m.errors??[];if(runtimeErrors.some(e=>!String(e).startsWith('Viewport texture was unavailable')))errors.push('runtime capture errors: '+runtimeErrors.join('; '));for(const a of actions)if(!m.captures?.some(c=>c.action===a))errors.push('missing '+a);const p=m.barrosanPlayableRuntimeSkin?.barrosanWorldMarkerDeclutterReadabilityRepair?.proofSnapshots?.v0300_bridge_cluster_decluttered||{};for(const[k,v]of Object.entries({bridgeMarkerLabelsReadable:true,barracksReserveMarkerLabelsReadable:true,bridgeLabelLanesDistinct:true,barracksReserveSupersededLabelsHidden:true,acceptedMarkerNodesRetained:true,noNewMarkers:true,noMarkerSemanticsChanged:true,routePreviewStaticSegmentCount:5,routePreviewControlledNotMoving:true,staticDeployedSupportPresenceCount:1,staticIntegrationVisualCount:1,pressureAfterStabilizeLine:'Pressure 70/100',pressureDoesNotStack:true,noExistingUnitPositionChanges:true,noAnimatedMovement:true,noPathfindingRouteFollowing:true,noCombatDamageHpProjectilesDeath:true,noAiWavesFog:true,noEconomyResourceMutation:true,noTrueDefaultRuntimeMutation:true,selectedCardTextOverlap:false,buttonRowBelowText:true,rawValidatorParagraphAbsent:true}))if(p[k]!==v)errors.push('proof '+k)}
const source=readFileSync(join(repo,'desktop-spikes/godot-salto/scripts/salto_barrosan_playable_runtime_skin.gd'),'utf8');for(const t of['v0300_review_modes','ROUTE PREVIEW','DEPLOY AUTHORIZED','SUPPORT DEPLOYED','LINE REINFORCED','PRESSURE STABILIZED','bridgeLabelLanesDistinct','barracksReserveSupersededLabelsHidden','Pressure 70/100'])if(!source.includes(t))errors.push('missing '+t);const block=source.slice(source.indexOf('func _v0300_review_modes()'),source.indexOf('func _v0264_reset_intel_relay()'));for(const f of['NavigationAgent','AStar','move_toward','spawn_deployed','damage_taken','_set_or_create_disc_marker("v0300'])if(block.includes(f))errors.push('forbidden '+f);if(/(?:spawn|fire|launch|attack|hit|kill|despawn|projectile)_[a-z_]+\s*\(/i.test(block))errors.push('forbidden gameplay call');
const numbered=existsSync(manual)?readdirSync(manual).filter(n=>/^\d\d_v0300_.*\.png$/.test(n)):[];if(numbered.length!==41)errors.push(`review pack must contain exactly 41 numbered PNGs; found ${numbered.length}`);for(const n of['40_v0300_contact_sheet.png','41_v0300_black_frame_rejection_report.png'])if(!numbered.includes(n))errors.push('missing '+n);
const report={status:errors.length?'FAIL_v0300_VALIDATION':'PASS_v0300_BARROSAN_WORLD_MARKER_DECLUTTER_READABILITY_REPAIR_VALIDATION',errors,captureCount:16,runtimeCaptureStatus:existsSync(manifestPath)?JSON.parse(readFileSync(manifestPath)).status:'MISSING',requiredActions:actions,reviewPackNumberedPngCount:numbered.length,blackFrameRejectionReport:'v0300-black-frame-stats.json'};if(existsSync(manual))writeFileSync(join(manual,'v0300-validation-report.json'),JSON.stringify(report,null,2)+'\n');console.log(report.status);if(errors.length){console.error(errors.join('\n'));process.exit(1)}
