import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const root = process.cwd(); const errors = [];
const abs = (relative) => path.join(root, relative); const exists = (relative) => fs.existsSync(abs(relative));
const read = (relative) => fs.readFileSync(abs(relative), 'utf8');
const readJson = (relative) => JSON.parse(read(relative).replace(/^\uFEFF/, ''));
const sha256 = (relative) => crypto.createHash('sha256').update(fs.readFileSync(abs(relative))).digest('hex');
const assert = (condition, message) => { if (!condition) errors.push(message); };
const FROZEN_HOUSE02_BLEND = '3da7c2cf71509e07c900001fd0b277e9af4584a074552ac1d929a4f37e0d78b6';
const FROZEN_HOUSE02_GLB = 'ceab23ff3cfb580cc63ce917ec1ff675a1cd318f8fe3390fc836166015ebba89';
const V0343_BLEND = 'ecb268c7a4f69c914951a0dbd9494fb332003566073b2311b47a348ba9f831e9';
const V0343_GLB = 'd4d780510b1812e7e4f082f24dfee049ab21f905acbaaeaa4f54d6f67b4118b9';
const V0344_BLEND = 'd63a8364f3edb10d20926a45dd52a41c8d0b8042fe707cf2aae267fbc63ac198';
const V0344_GLB = '76cd62330d4cb4073469fe51e510557d93dcc0d9a07e9f234a539561abda7015';
const V0345_BLEND = 'f620e472cfbac2f0800f07e8e1bc4e840eccada971fedd5776268986c74c34ba';
const V0345_GLB = '14df5b448db8257b695b00716ec6d3999f75a26ebe6cc03bd4e313399a53058c';
const packRoot = 'artifacts/manual-review/v0346-barn-house02-silhouette-roof-pitch/UPLOAD_TO_CHAT';
const runtime = 'artifacts/runtime/v0346';
const packNames = ['00_READ_ME_FIRST.md','01_HOUSE02_FAMILY_PROPORTION_RESET.png','02_UNLABELLED_FRONT_REAR_GABLE.png','03_LOWER_ROOF_PITCH_AND_DARK_SLATE.png','04_TRUE_MATCHED_512X256_COMPARISON.png','compact-evidence-summary.json'];
const sources = ['01_front_three_quarter.png','02_rear_three_quarter.png','03_direct_side_gable.png','04_close_roof_front_material.png','05_true_matched_512x256_house02_barn.png'];
function pngInfo(relative) { if (!exists(relative)) return null; const b = fs.readFileSync(abs(relative)); if (b.length < 24 || b.readUInt32BE(0) !== 0x89504e47) return null; let s=0,s2=0,n=0; for(let i=100;i<b.length;i+=Math.max(1,Math.floor(b.length/5000))){s+=b[i];s2+=b[i]*b[i];n++;} return {width:b.readUInt32BE(16),height:b.readUInt32BE(20),bytes:b.length,variance:s2/Math.max(1,n)-(s/Math.max(1,n))**2}; }
for (const file of ['art-source/blender/v0338/barrosan_house_02_material_gold_candidate.blend','desktop-spikes/godot-salto/assets/v0338/barrosan_house_02_material_gold_candidate.glb','art-source/blender/v0343/house02_derived_barrosan_barn_visual_preflight.blend','desktop-spikes/godot-salto/assets/v0343/house02_derived_barrosan_barn_visual_preflight.glb','art-source/blender/v0344/barn_front_granite_roof_edge_visual_preflight.blend','desktop-spikes/godot-salto/assets/v0344/barn_front_granite_roof_edge_visual_preflight.glb','art-source/blender/v0345/barn_proportion_simple_slate_roof_reset.blend','desktop-spikes/godot-salto/assets/v0345/barn_proportion_simple_slate_roof_reset.glb','art-source/blender/v0346/v0345_source_duplicate_for_v0346.blend','art-source/blender/v0346/barn_house02_silhouette_roof_pitch.blend','desktop-spikes/godot-salto/assets/v0346/barn_house02_silhouette_roof_pitch.glb','art-source/blender/v0346/v0346-barn-metrics.json','art-source/blender/v0346/v0346-source-lineage.json','art-source/blender/v0346/v0346-roof-object-diagnosis.json','desktop-spikes/godot-salto/scenes/review/V0346BarnHouse02SilhouetteRoofPitch.tscn','desktop-spikes/godot-salto/scripts/v0346_barn_house02_silhouette_roof_pitch.gd','tools/blender/generateV0346BarnHouse02SilhouetteRoofPitch.py','tools/blender/generateV0346BarnHouse02SilhouetteRoofPitchWindows.ps1','tools/godot/captureGodotV0346BarnHouse02SilhouetteRoofPitchWindows.ps1','tools/godot/buildV0346BarnHouse02SilhouetteRoofPitchPack.ps1']) assert(exists(file), `required v0.346 file missing: ${file}`);
assert(sha256('art-source/blender/v0338/barrosan_house_02_material_gold_candidate.blend')===FROZEN_HOUSE02_BLEND,'frozen House02 Blend changed'); assert(sha256('desktop-spikes/godot-salto/assets/v0338/barrosan_house_02_material_gold_candidate.glb')===FROZEN_HOUSE02_GLB,'frozen House02 GLB changed'); assert(sha256('art-source/blender/v0343/house02_derived_barrosan_barn_visual_preflight.blend')===V0343_BLEND,'v0.343 Blend changed'); assert(sha256('desktop-spikes/godot-salto/assets/v0343/house02_derived_barrosan_barn_visual_preflight.glb')===V0343_GLB,'v0.343 GLB changed'); assert(sha256('art-source/blender/v0344/barn_front_granite_roof_edge_visual_preflight.blend')===V0344_BLEND,'v0.344 Blend changed'); assert(sha256('desktop-spikes/godot-salto/assets/v0344/barn_front_granite_roof_edge_visual_preflight.glb')===V0344_GLB,'v0.344 GLB changed'); assert(sha256('art-source/blender/v0345/barn_proportion_simple_slate_roof_reset.blend')===V0345_BLEND,'v0.345 Blend changed'); assert(sha256('desktop-spikes/godot-salto/assets/v0345/barn_proportion_simple_slate_roof_reset.glb')===V0345_GLB,'v0.345 GLB changed'); assert(sha256('art-source/blender/v0346/v0345_source_duplicate_for_v0346.blend')===V0345_BLEND,'v0.346 source duplicate is not byte-identical to v0.345');
const lineage=readJson('art-source/blender/v0346/v0346-source-lineage.json'); assert(lineage.checkpoint==='v0.346'&&lineage.derivedFrom.includes('v0345')&&lineage.copiedV0345SourceSha256===V0345_BLEND,'v0.346 lineage does not derive from final v0.345'); assert(lineage.v0345Untouched===true&&lineage.v0344Untouched===true&&lineage.v0343Untouched===true&&lineage.house02Untouched===true,'frozen lineage preservation failed');
const metrics=readJson('art-source/blender/v0346/v0346-barn-metrics.json'); const ratios=metrics.ratiosAfter||{}; for(const [key,min,max] of [['ridgeHeight',1.0,1.12],['eaveHeight',0.95,1.08],['frontWidth',1.30,1.50],['depth',1.10,1.25]]) assert(ratios[key]>=min&&ratios[key]<=max,`House02-relative ${key} ratio outside v0.346 target`); assert(metrics.derivedFromV0345===true&&metrics.prototypeOnly===true&&metrics.defaultRuntimeIntegrated===false,'prototype/default-runtime isolation failed');
assert(metrics.roof?.principalSlopes===2&&metrics.roof?.frontSlope===true&&metrics.roof?.rearSlope===true&&metrics.roof?.straightRidge===true,'two-slope/straight-ridge contract failed'); for(const key of ['secondaryRoofNodes','pedimentNodes','blackGableVoids','orangeEdgeFaces','graniteRoofFaces','floatingRoofPieces','intersectingSecondaryRoofPieces']) assert(metrics.roof?.[key]===0,`roof defect count nonzero: ${key}`); assert(metrics.roof?.closedGraniteGables===2&&metrics.roof?.fasciaThicknessM<=0.09,'closed gables or thin edge contract failed'); assert(metrics.openings?.lowerDoubleLivestockDoor===true&&metrics.openings?.upperHayLoadingOpening===true&&metrics.openings?.rearServiceOpening===true,'agricultural openings missing'); for(const material of ['V0344_House02Derived_Granite_Continuous','V0346_House02_Family_Dark_Weathered_Slate','V0346_Subordinate_Charcoal_Brown_Roof_Edge']) assert(metrics.usedMaterials?.includes(material),`required material missing: ${material}`); assert(metrics.availableMaterials?.includes('V0346_House02_Family_Slate_Underside'),'slate underside material lineage missing'); assert(fs.statSync(abs('desktop-spikes/godot-salto/assets/v0346/barn_house02_silhouette_roof_pitch.glb')).size<20_000_000,'unapproved large v0.346 asset import');
const generator=read('tools/blender/generateV0346BarnHouse02SilhouetteRoofPitch.py').toLowerCase(); const script=read('desktop-spikes/godot-salto/scripts/v0346_barn_house02_silhouette_roof_pitch.gd'); const scene=read('desktop-spikes/godot-salto/scenes/review/V0346BarnHouse02SilhouetteRoofPitch.tscn'); for(const token of ['warcraft','blizzard','age of empires','copyrighted third-party']) assert(!generator.includes(token),`forbidden provenance token: ${token}`); for(const token of ['move_and_slide','navigationagent','projectile','save_game','instantiate_enemy','resource_mutation']) assert(!script.toLowerCase().includes(token),`forbidden gameplay coupling: ${token}`); for(const token of ['V0346_Stable_Oblique_Barn_Camera','PROJECTION_ORTHOGONAL','V0346_Frozen_House02_Unmodified_Anchor','V0346_Barn_House02_Family_Candidate','05_true_matched_512x256_house02_barn.png','prototypeOnly','defaultRuntimeIntegrated']) assert(script.includes(token)||script.toLowerCase().includes(token.toLowerCase()),`capture/isolation token missing: ${token}`); assert(scene.includes('[node name="V0346BarnHouse02SilhouetteRoofPitch" type="Node3D"]'),'scene is not isolated Node3D');
const packageText=read('package.json'); for(const command of ['blender:generate:salto-v0346-barn-house02-silhouette-roof-pitch','godot:capture:salto-v0346-barn-house02-silhouette-roof-pitch','godot:pack:salto-v0346-barn-house02-silhouette-roof-pitch','godot:validate:salto-v0346-barn-house02-silhouette-roof-pitch']) assert(packageText.includes(command),`package command missing: ${command}`);
assert(exists(packRoot),'v0.346 upload pack missing'); const packFiles=exists(packRoot)?fs.readdirSync(abs(packRoot)).filter(n=>fs.statSync(abs(`${packRoot}/${n}`)).isFile()).sort():[]; assert(JSON.stringify(packFiles)===JSON.stringify([...packNames].sort()),'v0.346 upload pack must contain exactly six files'); const summary=exists(`${packRoot}/compact-evidence-summary.json`)?readJson(`${packRoot}/compact-evidence-summary.json`):{}; assert(summary.exactlySixReviewFiles===true&&summary.exactlyFourPng===true&&summary.noVideo===true,'compact evidence summary count/video contract failed'); for(const name of packNames.filter(n=>n.endsWith('.png'))){const info=pngInfo(`${packRoot}/${name}`); assert(info&&info.bytes>10000&&info.variance>2,`invalid v0.346 board: ${name}`);}
const reportPath='docs/V0346_BARN_HOUSE02_SILHOUETTE_AND_ROOF_PITCH_REPORT.md'; assert(exists(reportPath),'v0.346 report missing'); if(exists(reportPath)){const report=read(reportPath); const outcome='READY FOR HUMAN V0346 BARN HOUSE02-FAMILY SILHOUETTE REVIEW'; assert((report.match(new RegExp(outcome,'g'))||[]).length===1,'v0.346 READY outcome must appear exactly once'); for(const token of ['v0.345 was rejected by human review','automated visual approval remains false',packRoot,'05_true_matched_512x256_house02_barn.png','no default runtime integration']) assert(report.toLowerCase().includes(token.toLowerCase()),`report evidence missing: ${token}`); assert(!report.toLowerCase().includes('v0.346 is gold')&&!report.toLowerCase().includes('v0.346 approved'),'report must not claim human approval/gold');}
if(exists(`${runtime}/v0346-barn-house02-silhouette-roof-pitch-runtime.json`)){const manifest=readJson(`${runtime}/v0346-barn-house02-silhouette-roof-pitch-runtime.json`); assert(manifest.captureCount===5&&manifest.status==='PASS_V0346_BARN_HOUSE02_SILHOUETTE_ROOF_PITCH'&&manifest.errors?.length===0&&manifest.house02RenderedDirectlyInCapture5===true,'runtime manifest incomplete'); assert(manifest.frontCaptureShowsAgriculturalOpenings===true&&manifest.rearCaptureShowsServiceSide===true,'front/rear orientation contract failed'); for(const name of sources){const info=pngInfo(`${runtime}/screenshots/${name}`); assert(info&&info.bytes>10000&&info.variance>2,`invalid v0.346 source capture: ${name}`);} const matched=pngInfo(`${runtime}/screenshots/05_true_matched_512x256_house02_barn.png`); assert(matched?.width===512&&matched?.height===256,'true matched source capture is not 512x256');} else assert(exists(`${packRoot}/04_TRUE_MATCHED_512X256_COMPARISON.png`),'runtime absent and matched board missing');
if(errors.length){console.error(JSON.stringify({status:'FAIL_V0346_BARN_HOUSE02_SILHOUETTE_ROOF_PITCH',errors},null,2));process.exit(1);} console.log(JSON.stringify({status:'PASS_V0346_BARN_HOUSE02_SILHOUETTE_ROOF_PITCH',outcome:'READY FOR HUMAN V0346 BARN HOUSE02-FAMILY SILHOUETTE REVIEW',automatedVisualApproval:false,humanReviewRequired:true,sourceCaptures:5,uploadPackFiles:6,prototypeOnly:true,defaultRuntimeUnchanged:true,gameplayUnchanged:true},null,2));
