import {existsSync,readFileSync,readdirSync,writeFileSync} from 'node:fs';
import {join,resolve} from 'node:path';
const repo=resolve('.'),base=join(repo,'artifacts/desktop-spikes/godot-salto/v0301/player-facing-presentation-debug-overlay-separation'),manual=join(repo,'artifacts/manual-review/v0301-player-facing-presentation-debug-overlay-separation'),errors=[];
const readManifest=(name)=>{const p=join(base,name,'screenshot-runtime-manifest.json');if(!existsSync(p)){errors.push(`missing ${name} manifest`);return null}return JSON.parse(readFileSync(p,'utf8'))};
const player=readManifest('player-facing'),debug=readManifest('debug-review');
for(const [name,m] of [['PLAYER',player],['DEBUG_REVIEW',debug]]){if(!m)continue;if(m.captureCount!==24)errors.push(`${name} capture count`);if((m.errors??[]).some(e=>!String(e).startsWith('Viewport texture was unavailable')))errors.push(`${name} runtime errors`);const s=m.barrosanPlayableRuntimeSkin?.barrosanPlayerFacingPresentationDebugOverlaySeparation??{};const snaps=s.proofSnapshots??{};const first=Object.values(snaps)[0]??{};if(first.presentationMode!==name)errors.push(`${name} mode evidence`);for(const [k,v] of Object.entries({playerModeExists:true,debugReviewModeExists:true,routePreviewStaticSegmentCount:5,staticDeployedSupportPresenceCount:1,staticIntegrationVisualCount:1,pressureAfterStabilizeLine:'Pressure 70/100',pressureDoesNotStack:true,selectedCardTextOverlap:false,buttonRowBelowText:true,topStripStateUnchanged:true,selectedCardStateUnchanged:true,resourcesUnchanged:true,unitPositionsUnchanged:true,minimapReadable:true,noGameplayMutation:true,noMovementPathfindingRouteFollowing:true,noCombatDamageHpProjectilesDeath:true,noAiWavesFog:true,noEconomyResourceMutation:true,noTrueDefaultRuntimeMutation:true,noDuplicateMarkers:true,noDuplicateRouteSegments:true,noDuplicateSupportPresence:true,noDuplicateIntegrationVisual:true})){if(first[k]!==v)errors.push(`${name} proof ${k}`)}}
if(player){const p=Object.values(player.barrosanPlayableRuntimeSkin?.barrosanPlayerFacingPresentationDebugOverlaySeparation?.proofSnapshots??{}).find(x=>x.presentationMode==='PLAYER')??{};for(const [k,v] of Object.entries({playerHistoricalProofLabelsHidden:true,playerValidatorOnlyTextHidden:true,playerCurrentStateUnderstandable:true})){if(p[k]!==v)errors.push(`PLAYER proof ${k}`)}}
if(debug){const d=Object.values(debug.barrosanPlayableRuntimeSkin?.barrosanPlayerFacingPresentationDebugOverlaySeparation?.proofSnapshots??{}).find(x=>x.presentationMode==='DEBUG_REVIEW')??{};if(d.debugAcceptedProofLabelsVisible!==true||d.debugEvidenceRail!==true)errors.push('DEBUG_REVIEW evidence preservation')}
const allProofs=[...Object.values(player?.barrosanPlayableRuntimeSkin?.barrosanPlayerFacingPresentationDebugOverlaySeparation?.proofSnapshots??{}),...Object.values(debug?.barrosanPlayableRuntimeSkin?.barrosanPlayerFacingPresentationDebugOverlaySeparation?.proofSnapshots??{})];if(!allProofs.some(x=>x.playerDebugPlayerRoundTripRestored===true))errors.push('round-trip restoration proof');
const source=readFileSync(join(repo,'desktop-spikes/godot-salto/scripts/salto_barrosan_playable_runtime_skin.gd'),'utf8');for(const t of['barrosan_presentation_mode','PLAYER','DEBUG_REVIEW','set_barrosan_presentation_mode','_v0301_apply_player_presentation','_v0301_apply_debug_review_presentation','v0299_pressure_stabilized_label','routePreviewStaticSegmentCount'])if(!source.includes(t))errors.push(`missing source ${t}`);const root=readFileSync(join(repo,'desktop-spikes/godot-salto/scripts/salto_spike_root.gd'),'utf8');for(const t of['--salto-barrosan-player-presentation','--salto-barrosan-debug-review-overlay','v0.301','_v0301_player_capture_steps','_v0301_debug_capture_steps'])if(!root.includes(t))errors.push(`missing root ${t}`);
const numbered=existsSync(manual)?readdirSync(manual).filter(n=>/^\d\d_v0301_.*\.png$/.test(n)):[];if(numbered.length!==48)errors.push(`review pack must contain exactly 48 numbered PNGs; found ${numbered.length}`);for(const n of['45_v0301_player_mode_contact_sheet.png','46_v0301_debug_review_mode_contact_sheet.png','47_v0301_combined_mode_comparison_contact_sheet.png','48_v0301_black_frame_rejection_report.png'])if(!numbered.includes(n))errors.push(`missing ${n}`);
const report={status:errors.length?'FAIL_v0301_VALIDATION':'PASS_v0301_BARROSAN_PLAYER_FACING_PRESENTATION_DEBUG_OVERLAY_SEPARATION_VALIDATION',errors,playerCaptureCount:player?.captureCount??0,debugCaptureCount:debug?.captureCount??0,reviewPackNumberedPngCount:numbered.length,blackFrameRejectionReport:'v0301-black-frame-stats.json'};if(existsSync(manual))writeFileSync(join(manual,'v0301-validation-report.json'),JSON.stringify(report,null,2)+'\n');console.log(report.status);if(errors.length){console.error(errors.join('\n'));process.exit(1)}
