import {copyFileSync,existsSync,mkdirSync,readFileSync,writeFileSync} from "node:fs";
import {dirname,join,relative,resolve} from "node:path";
import {fileURLToPath} from "node:url";
const repo=resolve(dirname(fileURLToPath(import.meta.url)),"..","..");
const rootDefault=join(repo,"artifacts","desktop-spikes","godot-salto","v0228");
const manual=join(repo,"artifacts","manual-review","v0228-production-battlefield-backplate");
const ids=["initial_overview","terrain_focus","road_focus","river_bridge_focus","structure_context","hostile_pressure","train_drawer","resolution_1366x768","resolution_1600x900","resolution_1920x1080"];
const root=resolve((process.argv.find(v=>v.startsWith("--artifact-root="))??`--artifact-root=${rootDefault}`).split("=")[1]);
const read=p=>JSON.parse(readFileSync(p,"utf8").replace(/^\uFEFF/u,""));
const write=(p,v)=>{mkdirSync(dirname(p),{recursive:true});writeFileSync(p,`${JSON.stringify(v,null,2)}\n`)};
const status=r=>r?.saltoProductionBattlefieldBackplateEnabled===true?r:r?.captures?.[0]?.status??r?.steps?.[0]?.status??r;
function check(r,e){const s=status(r),v=s?.saltoProductionBattlefieldBackplate??{};if(s?.saltoProductionBattlefieldBackplateEnabled!==true)e.push("v0.228 flag missing");if(v.enabled!==true||v.visualOnly!==true||v.gameplayChanged!==false)e.push("v0.228 visual-only status failed");if(Number(v.generatedProjectSourceImageCount??-1)!==0||Number(v.newRuntimeArtSlotsAdded??-1)!==0)e.push("unexpected source/runtime slot count")}
function capture(){const e=[],p=join(root,"capture","selected-production-battlefield-backplate","screenshot-runtime-manifest.json");if(!existsSync(p))e.push("missing capture manifest");const m=e.length?{}:read(p);check(m,e);const by=new Map((m.captures??[]).map(x=>[x.id,x]));mkdirSync(manual,{recursive:true});ids.forEach((id,i)=>{const x=by.get(id);if(!x?.absolutePath||!existsSync(x.absolutePath))e.push(`missing ${id}`);else copyFileSync(x.absolutePath,join(manual,`${String(i+1).padStart(2,"0")}_${id}.png`))});writeFileSync(join(manual,"12_notes.md"),"# v0.228 Production Battlefield Backplate Notes\n\n- One built-in image-generation preview was attempted but no filesystem artifact was exposed, so no generated project source was retained or integrated.\n- The shipped review path uses irregular authored Godot terrain polygons, tapered road segments, shaped river and bank layers, integrated bridge landings and restrained local accents.\n- Default launcher, browser runtime and gameplay remain unchanged.\n\nCandid visual acceptance must come from the contact sheet, not this technical report.\n");write(join(root,"v0228-capture-report.json"),{status:e.length?"FAIL_V0228_CAPTURE":"PASS_V0228_CAPTURE",generatedProjectSourceImageCount:0,errors:e});if(e.length)throw Error(e.join("\n"))}
function validation(){const e=[];for(const id of["selected-production-battlefield-backplate","selected-v0227-comparator","ground-missing-fallback","default-procedural"]){const p=join(root,"validation",id,"player-slice-validation-runtime.json");if(!existsSync(p)){e.push(`missing ${id}`);continue}const r=read(p);if(r.status!=="PASS_PLAYER_SLICE_VALIDATION")e.push(`${id} failed`);if(id==="selected-production-battlefield-backplate"||id==="ground-missing-fallback")check(r,e);if(id==="default-procedural"&&r.saltoPresentationRebootEnabled===true)e.push("default changed")}write(join(root,"v0228-validation-report.json"),{status:e.length?"FAIL_V0228_VALIDATION":"PASS_V0228_VALIDATION",errors:e});if(e.length)throw Error(e.join("\n"))}
function benchmark(){const e=[],load=id=>{const p=join(root,"benchmark",id,"worker-art-opt-in-benchmark-runtime.json");if(!existsSync(p)){e.push(`missing ${id}`);return{}}return read(p)},c=load("selected-v0227-comparator"),s=load("selected-production-battlefield-backplate"),d=load("default-procedural");check(s,e);const ratio=Number(s.fpsAverage??0)/Math.max(1,Number(c.fpsAverage??0));if(ratio<0.8)e.push("fps regression >20%");write(join(root,"v0228-benchmark-report.json"),{status:e.length?"FAIL_V0228_BENCHMARK":"PASS_V0228_BENCHMARK",procedural:d,v0227Comparator:c,selected:s,fpsRatioVsComparator:Number(ratio.toFixed(4)),errors:e});if(e.length)throw Error(e.join("\n"))}
const cmd=process.argv[2]??"capture";if(cmd==="capture")capture();else if(cmd==="validation")validation();else if(cmd==="benchmark")benchmark();else throw Error("unknown command");
