import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';

const root = process.cwd();
const base = 'a880884b8dae83ee5d843019fb3c309dfab4ea3c';
const abs = (value) => path.join(root, value);
const exists = (value) => fs.existsSync(abs(value));
const read = (value) => fs.readFileSync(abs(value), 'utf8');
const json = (value) => JSON.parse(read(value));
const sha = (value) => crypto.createHash('sha256').update(fs.readFileSync(abs(value))).digest('hex');
const errors = [];
const assert = (condition, message) => { if (!condition) errors.push(message); };
const runtime = 'artifacts/runtime/v0339';
const pack = 'artifacts/manual-review/v0339-barrosan-hamlet-vertical-slice/UPLOAD_TO_CHAT';
const full = 'artifacts/manual-review/v0339-barrosan-hamlet-vertical-slice/full-evidence';
const expectedPack = ['00_README.md','01_HUMAN_DECISION_AND_FROZEN_GOLD_ANCHOR.png','02_PRIMARY_PLAYER_RTS_AND_LIGHTING.png','03_SETTLEMENT_COMPOSITION_AND_ARCHITECTURE.png','04_TERRAIN_ROADS_PATHS_AND_GROUNDING.png','05_WATER_CROSSING_WALLS_AND_FUNCTIONAL_PROPS.png','06_VEGETATION_SCALE_AND_MATERIAL_HARMONY.png','07_PLAYER_DEBUG_AND_GAMEPLAY_COMPATIBILITY.png','08_CONTINUOUS_V0339_BARROSAN_HAMLET_VERTICAL_SLICE.mp4','09_TARGET_COMPARISON_PERFORMANCE_AND_TECHNICAL_EVIDENCE.png','compact-evidence-summary.json'];
const captures = ['01_primary_player_neutral_overcast_rts.png','02_cool_daylight_rts.png','03_warm_directional_rts.png','04_far_rts.png','05_near_rts.png','06_256_readability_source.png','07_grayscale_rts.png','08_direct_top_down.png','09_oblique_northwest.png','10_oblique_northeast.png','11_oblique_southeast.png','12_oblique_southwest.png','13_house02_grounding.png','14_barn_close.png','15_shed_close.png','16_wall_kit.png','17_road_path_hierarchy.png','18_water_crossing.png','19_trough_props.png','20_vegetation.png','21_worker_scale_and_entrances.png','22_footprint_compatibility.png','23_collision_debug.png','24_prospective_navigation_clearance.png','25_material_harmony.png','26_neutral_overcast_closeup.png','27_cool_daylight_closeup.png','28_warm_directional_closeup.png','29_house02_empty_vs_contextual.png','30_v0141_target_vs_v0339_mood.png','31_performance_draw_call_evidence.png'];
const requiredFiles = ['art-source/blender/v0339/barrosan_hamlet_vertical_slice_assets.blend','desktop-spikes/godot-salto/assets/v0339/barrosan_hamlet_vertical_slice_assets.glb','desktop-spikes/godot-salto/scenes/review/V0339BarrosanHamletVerticalSliceReview.tscn','desktop-spikes/godot-salto/scripts/v0339_barrosan_hamlet_vertical_slice_review.gd','tools/blender/generateV0339BarrosanHamletVerticalSlice.py','tools/godot/captureGodotV0339BarrosanHamletVerticalSliceWindows.ps1','tools/godot/buildV0339BarrosanHamletVerticalSlicePack.py'];
const unchangedFromBase = (relative) => { try { execFileSync('git', ['diff','--quiet',base,'--',relative], {cwd: root, stdio:'ignore'}); return true; } catch { return false; } };
const pngInfo = (relative) => { if (!exists(relative)) return null; const b=fs.readFileSync(abs(relative)); if(b.length<24||b.readUInt32BE(0)!==0x89504e47)return null; const w=b.readUInt32BE(16),h=b.readUInt32BE(20); let sum=0,sum2=0,n=0; for(let i=100;i<b.length;i+=Math.max(1,Math.floor(b.length/4000))){const v=b[i];sum+=v;sum2+=v*v;n++;} return {width:w,height:h,bytes:b.length,variance:sum2/n-(sum/n)**2}; };
const ffprobe = (relative) => JSON.parse(execFileSync('C:/Users/barro/.cache/codex-runtimes/ffmpeg-v0322/bin/ffprobe.exe',['-v','error','-count_frames','-show_entries','stream=codec_name,width,height,r_frame_rate,duration,nb_read_frames','-of','json',abs(relative)],{encoding:'utf8'})).streams?.[0]||{};

assert(unchangedFromBase('art-source/blender/v0338/barrosan_house_02_material_gold_candidate.blend'),'frozen v0.338 Blend changed');
assert(unchangedFromBase('desktop-spikes/godot-salto/assets/v0338/barrosan_house_02_material_gold_candidate.glb'),'frozen v0.338 GLB changed');
assert(sha('art-source/blender/v0338/barrosan_house_02_material_gold_candidate.blend')==='3da7c2cf71509e07c900001fd0b277e9af4584a074552ac1d929a4f37e0d78b6','v0.338 Blend frozen hash mismatch');
assert(sha('desktop-spikes/godot-salto/assets/v0338/barrosan_house_02_material_gold_candidate.glb')==='ceab23ff3cfb580cc63ce917ec1ff675a1cd318f8fe3390fc836166015ebba89','v0.338 GLB frozen hash mismatch');
for(const file of requiredFiles) assert(exists(file),`required v0.339 file missing: ${file}`);
const scene = exists('desktop-spikes/godot-salto/scenes/review/V0339BarrosanHamletVerticalSliceReview.tscn') ? read('desktop-spikes/godot-salto/scenes/review/V0339BarrosanHamletVerticalSliceReview.tscn') : '';
const script = exists('desktop-spikes/godot-salto/scripts/v0339_barrosan_hamlet_vertical_slice_review.gd') ? read('desktop-spikes/godot-salto/scripts/v0339_barrosan_hamlet_vertical_slice_review.gd') : '';
const generator = exists('tools/blender/generateV0339BarrosanHamletVerticalSlice.py') ? read('tools/blender/generateV0339BarrosanHamletVerticalSlice.py') : '';
for(const token of ['V0339BarrosanHamletVerticalSliceReview','prototypeOptIn','V0339_HOUSE_GLB','V0339_SECONDARY_GLB','orthographic','V0339_CONTINUOUS_FRAMES := 504','DEBUG_REVIEW','V0339DebugReviewEvidenceOnly']) assert(scene.includes(token)||script.includes(token),`v0.339 contract token missing: ${token}`);
for(const token of ['V0339_Barrosan_Agricultural_Barn','V0339_Barrosan_Timber_Stone_Shed','V0339_Dry_Stone_Wall_Kit','Stone_Trough_Basin','v0339_authored_asset']) assert(generator.includes(token),`authored asset family token missing: ${token}`);
for(const forbidden of ['move_and_slide','NavigationAgent3D','damage','projectile','change_pressure','save_game','queue_free']) assert(!script.toLowerCase().includes(forbidden.toLowerCase()),`forbidden gameplay coupling in v0.339 script: ${forbidden}`);
const manifestPath = `${runtime}/v0339-barrosan-hamlet-vertical-slice-runtime.json`;
assert(exists(manifestPath),'v0.339 runtime manifest missing');
if(exists(manifestPath)) { const m=json(manifestPath); assert(m.checkpoint==='v0.339'&&m.prototypeOptIn===true&&m.prototypeOnly===true&&m.defaultRuntimeIntegrated===false,'v0.339 opt-in/default-runtime contract failed'); assert(m.v0338House02InstancedUnmodified===true&&m.v0338House02BlendSha256==='3da7c2cf71509e07c900001fd0b277e9af4584a074552ac1d929a4f37e0d78b6'&&m.v0338House02GLBSha256==='ceab23ff3cfb580cc63ce917ec1ff675a1cd318f8fe3390fc836166015ebba89','frozen House 02 integration ledger failed'); assert(m.captureCount===31&&m.continuousFrames===504&&m.videoSeconds===21,'capture/video count contract failed'); assert(m.errors?.length===0,'v0.339 runtime manifest has errors'); assert(m.terrain?.true3D===true&&m.terrain?.riverBelowLand===true&&m.terrain?.roadsConnected===true&&m.terrain?.noTranslucentDebugPads===true,'terrain contract failed'); assert(m.architecture?.house02Anchor&&m.architecture?.agriculturalBarn&&m.architecture?.timberStoneShed&&m.architecture?.dryStoneWallKit&&m.architecture?.trough,'hamlet architecture contract failed'); assert(m.units?.positionsMutated===false,'unit positions mutated'); assert(m.noGameplay&&m.noMovement&&m.noPathfinding&&m.noCombat&&m.noAI&&m.noEconomy&&m.noResources&&m.noPressureMutation&&m.noSaves&&m.noStableIDChanges,'preservation ledger incomplete'); }
for(const file of captures){const info=pngInfo(`${runtime}/screenshots/${file}`); assert(info&&info.width>=1280&&info.height>=720&&info.bytes>10000&&info.variance>2,`invalid v0.339 capture: ${file}`); assert(exists(`${full}/${file}`),`full evidence missing: ${file}`);}
assert(pngInfo(`${runtime}/screenshots/06_256_readability.png`)?.width===256,'256px readability derivative missing');
const video = `${pack}/08_CONTINUOUS_V0339_BARROSAN_HAMLET_VERTICAL_SLICE.mp4`;
if(exists(video)){try{const s=ffprobe(video);assert(s.codec_name==='h264'&&s.width===1280&&s.height===720&&s.r_frame_rate==='24/1'&&Number(s.nb_read_frames)===504,'v0.339 video codec/dimensions/fps/frame count mismatch');assert(Number(s.duration)>=20.8&&Number(s.duration)<=21.2,'v0.339 video duration mismatch');}catch(e){errors.push(`v0.339 ffprobe failed: ${e.message}`)}}else errors.push('v0.339 exact upload video missing');
const names=exists(pack)?fs.readdirSync(abs(pack)).filter(n=>fs.statSync(abs(`${pack}/${n}`)).isFile()).sort():[];assert(JSON.stringify(names)===JSON.stringify([...expectedPack].sort()),`v0.339 exact upload pack mismatch: ${names.join(',')}`);
if(exists(`${pack}/compact-evidence-summary.json`)){const s=json(`${pack}/compact-evidence-summary.json`);assert(s.checkpoint==='v0.339'&&s.house02IntegratedUnmodified===true&&s.defaultRuntimeIntegrated===false,'v0.339 compact summary gate failed');assert(s.cameras?.orthographic&&s.cameras?.directTopDown&&s.cameras?.fourObliques,'camera evidence summary incomplete');assert(s.captures?.count===31&&s.video?.decodedFrames===504&&s.video?.allNonBlank===true,'compact capture/video evidence incomplete');assert(Array.isArray(s.exactUploadFiles)&&s.exactUploadFiles.length===10,'compact upload manifest must cover ten non-summary files');for(const record of s.exactUploadFiles)assert(exists(`${pack}/${record.path}`)&&fs.statSync(abs(`${pack}/${record.path}`)).size===record.bytes&&sha(`${pack}/${record.path}`)===record.sha256,`pack manifest mismatch: ${record.path}`);assert(fs.statSync(abs(`${pack}/compact-evidence-summary.json`)).size<250000,'compact summary exceeds 250KB');for(const file of expectedPack.filter(n=>n.endsWith('.png'))){const info=pngInfo(`${pack}/${file}`);assert(info&&info.width>=900&&info.height>=500&&info.bytes>10000&&info.variance>2,`upload board invalid/low variance: ${file}`);}}
const packageText=read('package.json');for(const token of ['blender:generate:salto-v0339-barrosan-hamlet-vertical-slice','godot:capture:salto-v0339-barrosan-hamlet-vertical-slice','godot:pack:salto-v0339-barrosan-hamlet-vertical-slice','godot:validate:salto-v0339-barrosan-hamlet-vertical-slice'])assert(packageText.includes(token),`package command missing: ${token}`);
if(errors.length){console.error(JSON.stringify({status:'FAIL_V0339_BARROSAN_HAMLET_VERTICAL_SLICE',base,errors},null,2));process.exit(1)}
console.log(JSON.stringify({status:'PASS_V0339_BARROSAN_HAMLET_VERTICAL_SLICE',base,checks:90,outcome:'READY FOR HUMAN BARROSAN HAMLET VERTICAL-SLICE REVIEW',humanReviewRequired:true,automatedVisualApproval:false},null,2));
