import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const root = process.cwd();
const source = path.join(root, 'artifacts/desktop-spikes/godot-salto/v0325/human-river-naturalization');
const upload = path.join(root, 'artifacts/manual-review/v0325-human-river-naturalization/UPLOAD_TO_CHAT');
const script = path.join(root, 'desktop-spikes/godot-salto/scripts/v0325_human_river_naturalization.gd');
const manifest = () => readJson(path.join(source, 'v0325-human-river-naturalization-runtime.json'));
const audit = () => readJson(path.join(source, 'v0325-human-river-naturalization-audit.json'));
const readJson = file => { if (!fs.existsSync(file)) fail(`missing JSON ${file}`); return JSON.parse(fs.readFileSync(file, 'utf8')); };
const readText = file => fs.readFileSync(file, 'utf8');
const exists = file => fs.existsSync(file);
function fail(message) { console.error(`FAIL_V0325: ${message}`); process.exitCode = 1; throw new Error(message); }
function requiredFiles() { const files = ['00_READ_ME_FIRST.md','01_V0324_TO_V0325_COMPARISON.png','02_CLEAN_PLAYER_OVERVIEW.png','03_UPSTREAM_AND_DOWNSTREAM.png','04_VISIBLE_BANK_CROSS_SECTION.png','05_YARDS_AND_FILLED_PATHS.png','06_BRIDGE_ABUTMENTS.png','07_ORDINARY_GAMEPLAY.png','08_CONTINUOUS_RIVER_NATURALIZATION.mp4','compact-evidence-summary.json']; for (const file of files) if (!exists(path.join(upload, file))) fail(`missing upload ${file}`); return files; }
function validateFiles() { requiredFiles(); if (fs.readdirSync(upload).length !== 10) fail(`upload pack must contain exactly 10 files, got ${fs.readdirSync(upload).length}`); if (!exists(script)) fail('v0.325 script missing'); const text = readText(script); for (const anchor of ['V0325SingleContinuousRecessedRiverWater','V0325LeftContinuousExposedSlope','V0325RightContinuousExposedSlope','V0325PrincipalWornEarthYard','V0325WorkshopWornEarthYard','V0325WestAbutmentBase','V0325EastAbutmentBase','V0325_RIVER_SAMPLES := 128']) if (!text.includes(anchor)) fail(`missing authored geometry anchor ${anchor}`); for (const forbidden of ['V0324RestrainedRiverFlowHighlight','V0324ShoreStone_','V0324PrincipalIrregularYard','V0324WorkshopIrregularYard','_add_disc(','BRIDGE LINE  |  SALTO EAST']) if (text.includes(forbidden)) fail(`rejected v0.324 visual construction remains: ${forbidden}`); }
function validateRiver() { const r = audit().river; if (r.directionChangeCount < 3 || r.longestStraightRunPercent >= 40) fail('river curvature contract failed'); if (r.widthVariationPercent < 15 || r.widthVariationPercent > 28) fail('river visible width variation outside 15-28%'); if (r.minimumVisibleBankSlopeWidth < 0.8 || r.minimumLandToWaterDrop < 0.35) fail('visible bank/depth contract failed'); if (r.whiteWaterMarkObjectCount !== 0 || r.blackBorderObjectCount !== 0) fail('forbidden water marks/border remain'); if (r.leftBankComponents !== 1 || r.rightBankComponents !== 1 || r.waterComponents !== 1) fail('river components disconnected'); return r; }
function validateYards() { const yards = audit().yards; for (const [name, yard] of Object.entries(yards)) { if (!yard.filledSurface || !yard.connectedToBridgeRoute || yard.sharpCornerCount !== 0 || yard.orangePerimeterCount !== 0 || yard.helperLineCount !== 0) fail(`${name} yard/path human contract failed`); } return yards; }
function validateBridge() { const b = audit().bridge; if (!b.northAbutmentContact || !b.southAbutmentContact || b.deckContactCount !== 2 || b.floatingEntranceCount !== 0 || b.abutmentMasses !== 2 || b.retainingFaces !== 4) fail('embedded bridge abutment contract failed'); return b; }
function validatePlayer() { const m = manifest(); if (!m.prototypeOptIn || !m.prototypeOnly || m.defaultRuntimeChanged || m.gameplayChanged || m.playerDebugStringsFound.length !== 0) fail('opt-in/default/gameplay/player hygiene flags failed'); const s = JSON.parse(fs.readFileSync(path.join(upload, 'compact-evidence-summary.json'), 'utf8')); if (s.forbiddenCues.whiteWaterMarkObjectCount !== 0 || s.forbiddenCues.blackBorderObjectCount !== 0 || s.forbiddenCues.orangePerimeterCount !== 0 || s.forbiddenCues.sharpYardCornerCount !== 0 || s.forbiddenCues.visiblePlayerHelperLineCount !== 0) fail('forbidden PLAYER cues present in compact evidence'); return { playerDebugStringsFound: [], defaultRuntimeUnchanged: true, gameplayUnchanged: true }; }
function validatePreservation() { const m = manifest(); if (!m.acceptedRoofGeometryUnchanged || !m.v0322MediaUnchanged || m.v0322MediaSHA256Before !== '8901bb6a074e5c3cc01bf5e16572f21dac06a527a4ea15273d649c71c73faa84' || !m.v0324FallbackPreserved) fail('accepted preservation flags failed'); if (m.roofs.length !== 2 || m.roofs.some(row => row.invalidNormalCount !== 0 || row.selfIntersectionCount !== 0 || !row.chimneyContact || !row.ridgeCapContact)) fail('roof audit regressed'); return { acceptedRoofGeometryUnchanged: true, v0322MediaUnchanged: true, roofs: m.roofs }; }
function validateMedia() { const summary = readJson(path.join(upload, 'compact-evidence-summary.json')); const media = summary.finalMedia; if (media.codec !== 'h264' || media.width !== 1280 || media.height !== 720 || media.decodedFrameCount !== 264 || media.uniqueFrameCount < 238 || media.duration < 10 || media.duration > 12 || !media.postCopyHashVerified || !media.postValidationHashVerified) fail('continuous media contract failed'); return media; }
function validate() { validateFiles(); const result = { status: 'PASS_V0325_HUMAN_RIVER_NATURALIZATION', outcome: 'READY FOR HUMAN VISUAL ENVIRONMENT REVIEW', river: validateRiver(), yards: validateYards(), bridge: validateBridge(), player: validatePlayer(), preservation: validatePreservation(), media: validateMedia(), reviewPackFileCount: 10, defaultRuntimeUnchanged: true, gameplayUnchanged: true }; console.log(JSON.stringify(result, null, 2)); }
const command = process.argv[2] || 'validate';
try { if (command === 'validate') validate(); else if (command === 'validate-river-curvature') { validateFiles(); console.log(JSON.stringify({status:'PASS_V0325_RIVER_CURVATURE',river:validateRiver()}, null, 2)); } else if (command === 'validate-bank-visibility') { validateFiles(); const r=validateRiver(); console.log(JSON.stringify({status:'PASS_V0325_BANK_VISIBILITY',minimumVisibleBankSlopeWidth:r.minimumVisibleBankSlopeWidth}, null, 2)); } else if (command === 'validate-water-marks') { validateFiles(); const r=validateRiver(); console.log(JSON.stringify({status:'PASS_V0325_FORBIDDEN_WATER_MARKS',whiteWaterMarkObjectCount:r.whiteWaterMarkObjectCount,blackBorderObjectCount:r.blackBorderObjectCount}, null, 2)); } else if (command === 'validate-yards') { validateFiles(); console.log(JSON.stringify({status:'PASS_V0325_YARD_OUTLINES',yards:validateYards()}, null, 2)); } else if (command === 'validate-path-connectivity') { validateFiles(); console.log(JSON.stringify({status:'PASS_V0325_PATH_CONNECTIVITY',yards:validateYards()}, null, 2)); } else if (command === 'validate-bridge-abutments') { validateFiles(); console.log(JSON.stringify({status:'PASS_V0325_BRIDGE_ABUTMENTS',bridge:validateBridge()}, null, 2)); } else if (command === 'validate-player-hygiene') { validateFiles(); console.log(JSON.stringify({status:'PASS_V0325_PLAYER_HYGIENE',player:validatePlayer()}, null, 2)); } else if (command === 'validate-media') { validateFiles(); console.log(JSON.stringify({status:'PASS_V0325_FINAL_MEDIA',media:validateMedia()}, null, 2)); } else throw new Error(`unknown command ${command}`); } catch (error) { if (!process.exitCode) process.exitCode = 1; }
